decentraland/marketplace

webapp/src/components/NFTCard/NFTCard.css, webapp/src/components/NFTCard/NFTCard.tsx, webapp/src/components/NFTImage/NFTImage.css, webapp/src/components/NFTImage/NFTImage.tsx, webapp/src/components/NFTImage/NFTImage.types.ts, webapp/src/components/NFTPage/ENSDetail/ENSDetail.tsx, webapp/src/components/NFTPage/NFTPage.css
=> feat: show monospace names

webapp/.vscode/settings.json, webapp/src/components/Bid/AcceptButton/AcceptButton.tsx, webapp/src/components/Bid/AcceptButton/AcceptButton.types.ts, webapp/src/components/Bid/AcceptButton/index.ts, webapp/src/components/Bid/Bid.css, webapp/src/components/Bid/Bid.tsx, webapp/src/components/Bid/WarningMessage/WarningMessage.css, webapp/src/components/Bid/WarningMessage/WarningMessage.tsx, webapp/src/components/Bid/WarningMessage/WarningMessage.types.ts, webapp/src/components/Bid/WarningMessage/index.ts, webapp/src/components/Bid/utils.ts, webapp/src/modules/nft/hooks.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Fixes #135 
Fixes #138 
Fixes #139
=> feat: handle invalid bids

webapp/src/components/TransferPage/TransferPage.tsx
=> fix: check if is not the owner at transfer modal

indexer/src/data/wearables/community_contest.ts
Zombie suit seems to have the correct rarity
Closes #159
=> feat: change bitcoin eyewear rarity

webapp/package-lock.json, webapp/package.json, webapp/src/modules/wallet/sagas.ts
This PR depends on this https://github.com/decentraland/decentraland-dapps/pull/68 to be merged and released
=> chore: update decentraland-dapps

webapp/src/modules/nft/reducer.ts
=> chore: remove patch

webapp/.vscode/settings.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/BuyPage/BuyPage.tsx, webapp/src/components/SettingsPage/Authorization/Authorization.tsx, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/index.css, webapp/src/modules/authorization/actions.ts, webapp/src/modules/authorization/reducer.ts, webapp/src/modules/authorization/sagas.ts, webapp/src/modules/bid/actions.ts, webapp/src/modules/bid/sagas.ts, webapp/src/modules/bid/utils.ts, webapp/src/modules/contract/ContractFactory.ts, webapp/src/modules/nft/actions.ts, webapp/src/modules/nft/estate/utils.ts, webapp/src/modules/nft/sagas.ts, webapp/src/modules/order/actions.ts, webapp/src/modules/order/sagas.ts, webapp/src/modules/proximity/sagas.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/tile/sagas.ts
This PR upgrades `decentraland-dapps` and `typescript` to their latest version to enable Fortmatic.
=> feat: Fortmatic

webapp/src/components/IntroPopup/IntroPopup.css, webapp/src/components/IntroPopup/IntroPopup.tsx, webapp/src/components/IntroPopup/IntroPopup.types.ts, webapp/src/components/IntroPopup/index.ts, webapp/src/components/Navbar/Navbar.tsx, webapp/src/components/UserMenu/UserMenu.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: matic intro

webapp/src/components/AuthorizationModal/AuthorizationModal.container.ts, webapp/src/components/AuthorizationModal/AuthorizationModal.tsx, webapp/src/components/AuthorizationModal/AuthorizationModal.types.ts, webapp/src/components/CancelSalePage/CancelSalePage.container.ts, webapp/src/components/CancelSalePage/CancelSalePage.tsx, webapp/src/components/CancelSalePage/CancelSalePage.types.ts, webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/components/SellPage/SellModal/SellModal.types.ts, webapp/src/components/SellPage/SellPage.container.ts, webapp/src/components/SellPage/SellPage.tsx, webapp/src/components/SellPage/SellPage.types.ts, webapp/src/components/SettingsPage/Authorization/Authorization.container.ts, webapp/src/components/SettingsPage/Authorization/Authorization.tsx, webapp/src/components/SettingsPage/Authorization/Authorization.types.ts, webapp/src/components/SettingsPage/Authorization/index.ts, webapp/src/components/SettingsPage/SettingsPage.container.ts, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/components/SettingsPage/SettingsPage.types.ts, webapp/src/modules/order/reducer.ts
=> fix: proceed loading

webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.css, webapp/src/components/NFTImage/NFTImage.css, webapp/src/components/NFTProvider/NFTProvider.container.ts, webapp/src/components/NFTProvider/NFTProvider.tsx
=> fix: refresh nft detail

webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.css, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx
=> fix: right mana symbol and contract name

webapp/package-lock.json, webapp/package.json, webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.css, webapp/src/components/Mana/Mana.tsx
Fixes #312 
Also fixes the transaction links (uses the chainId to pick the right block explorer)
Also fixes wrong properties (using `contract.name` instead of `contract.address` to link to block explorer)
Also fixes the `networks.undefined` error in console
Also bumps `decentraland-dapps` which includes fixes in `decentraland-transactions` (new polygon contracts)
=> fix: stuff in activity page

webapp/package-lock.json, webapp/package.json, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/BidPage/BidModal/BidModal.types.ts, webapp/src/components/BidPage/BidPage.container.ts, webapp/src/components/BidPage/BidPage.tsx, webapp/src/components/BidPage/BidPage.types.ts, webapp/src/components/BuyPage/BuyPage.container.ts, webapp/src/components/BuyPage/BuyPage.tsx, webapp/src/components/BuyPage/BuyPage.types.ts, webapp/src/components/TransferPage/TransferPage.container.ts, webapp/src/components/TransferPage/TransferPage.tsx, webapp/src/components/TransferPage/TransferPage.types.ts, webapp/src/modules/bid/reducer.ts, webapp/src/modules/bid/sagas.ts, webapp/src/modules/nft/reducer.ts, webapp/src/modules/nft/sagas.ts, webapp/src/modules/vendor/decentraland/BidService.ts, webapp/src/modules/vendor/decentraland/NFTService.ts, webapp/src/modules/vendor/decentraland/bid/api.ts, webapp/src/modules/vendor/decentraland/nft/api.ts
Fixes #308 
Also adds loading state to Buy Page
=> fix: bids and transfer

webapp/src/components/NFTCard/NFTCard.css, webapp/src/components/NFTCard/NFTCard.tsx, webapp/src/components/NFTPage/OrderDetails/OrderDetails.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #299 
On card:
On detail:
=> feat: show network

webapp/src/modules/account/selectors.ts, webapp/src/modules/routing/sagas.ts
Fixes #323 
I also made a PR to the server that would avoid this from happening: https://github.com/decentraland/nft-server/pull/15
=> fix: load more

webapp/src/components/NFTList/NFTList.tsx
=> chore: track load more

webapp/src/modules/ui/nft/browse/reducer.ts
=> fix: ignore old requests

webapp/src/components/AccountSidebar/AccountSidebar.container.ts, webapp/src/components/AccountSidebar/AccountSidebar.types.ts, webapp/src/components/NFTBrowse/NFTBrowse.container.ts, webapp/src/components/NFTBrowse/NFTBrowse.types.ts, webapp/src/components/NFTList/NFTList.container.ts, webapp/src/components/NFTList/NFTList.types.ts, webapp/src/components/NFTPage/NFTPage.tsx, webapp/src/components/NFTPage/WearableDetail/WearableDetail.types.ts, webapp/src/components/Vendor/NFTDetail/NFTDetail.tsx, webapp/src/components/Vendor/NFTDetail/NFTDetail.types.ts, webapp/src/components/Vendor/NFTDetail/index.ts, webapp/src/components/Vendor/NFTFilters/NFTFilters.container.ts, webapp/src/components/Vendor/NFTFilters/NFTFilters.types.ts, webapp/src/components/Vendor/NFTSidebar/NFTSidebar.container.ts, webapp/src/components/Vendor/NFTSidebar/NFTSidebar.types.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.types.ts, webapp/src/components/Vendor/known_origin/NFTFilters/NFTFilters.types.ts, webapp/src/components/Vendor/makers_place/NFTFilters/NFTFilters.types.ts, webapp/src/components/Vendor/super_rare/NFTFilters/NFTFilters.types.ts, webapp/src/components/VendorStrip/VendorStrip.container.ts, webapp/src/components/VendorStrip/VendorStrip.types.ts, webapp/src/modules/nft/types.ts, webapp/src/modules/routing/actions.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/ui/nft/browse/reducer.ts, webapp/src/modules/vendor/decentraland/nft/types.ts, webapp/src/modules/vendor/known_origin/nft/types.ts, webapp/src/modules/vendor/makers_place/nft/types.ts, webapp/src/modules/vendor/super_rare/nft/types.ts
In preparation for https://github.com/decentraland/marketplace/pull/349
=> chore: extracts types and a component to their corresponding folders

indexer/src/handlers/estate.ts, indexer/src/handlers/parcel.ts
Closes https://github.com/decentraland/atlas-server/issues/43
=> feat: update updatedAt when parcel or estate metadata is updated

.github/workflows/node.yml
This PR adds a simple CI pipeline that builds and run tests for both packages included in this repository.
=> chore: Add CI pipeline

webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.types.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/nft/utils.ts, webapp/src/modules/vendor/decentraland/item/api.ts, webapp/src/modules/vendor/decentraland/nft/api.ts, webapp/src/modules/vendor/decentraland/order/api.ts
Closes #333 
Better merged after #381
=> feat: buy item transaction activity

webapp/src/modules/analytics/track.ts, webapp/src/modules/item/actions.spec.ts, webapp/src/modules/item/actions.ts
added analytics for fetching and buying items
=> chore: track items

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetPage/ENSDetail/ENSDetail.tsx, webapp/src/components/AssetPage/EstateDetail/EstateDetail.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/Network/Network.tsx, webapp/src/components/AssetPage/Network/Network.types.ts, webapp/src/components/AssetPage/Network/index.ts, webapp/src/components/AssetPage/OrderDetails/OrderDetails.tsx, webapp/src/components/AssetPage/ParcelDetail/ParcelDetail.tsx, webapp/src/components/AssetPage/PictureFrameDetail/PictureFrameDetail.tsx, webapp/src/components/AssetPage/WearableCollection/WearableCollection.module.css, webapp/src/components/AssetPage/WearableCollection/WearableCollection.tsx, webapp/src/components/AssetPage/WearableCollection/WearableCollection.types.ts, webapp/src/components/AssetPage/WearableCollection/index.ts, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.tsx, webapp/src/components/Vendor/NFTFilters/SelectFilter/SelectFilter.tsx, webapp/src/components/Vendor/NFTFilters/SelectFilter/SelectFilter.types.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/modules/routing/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: add collections to item and wearable details. browse

webapp/src/components/AssetPage/WearableDetail/WearableDetail.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: show issue number

webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
=> fix: show buy button to owners

webapp/src/components/AssetPage/Owner/Owner.tsx
=> fix: owner link

webapp/src/components/AssetPage/ItemDetail/ItemDetail.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx
Show supply next to available in item detail:
=> feat: show supply in available

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx
=> feat: keep wearable filters open

webapp/package-lock.json, webapp/package.json
bump `decentraland-dapps` to latest version
=> feat: bump dapps

.github/workflows/node.yml
This PR fixes the coverage report by adding the `base-path` parameter.
=> fix: Fix coverage report by changing the coverage path

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/Vendor/decentraland/NFTSections/NFTSections.tsx, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/vendor/decentraland/routing/types.ts, webapp/src/modules/vendor/utils.ts
=> fix: Accessories typo

webapp/src/modules/vendor/decentraland/NFTService.spec.ts, webapp/src/modules/vendor/decentraland/NFTService.ts
This PR fixes the transfer meta-txs that were failing due to the wrong domain and version
=> feat: fix transfer meta-tx

README.md
=> chore: fix LICENSE link

webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.tsx
**Description:**
Issue: #415 
For mid-resolutions the filters were outside of the container. This pr solves this problem.
**Screenshots:**
Before:
After:
=> Fix: Filters do not go outside of their container anymore

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetImage/AssetImage.css, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx
Added `WearablePreview` to `AssetImage` component
=> feat: added preview to AssetImage

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetImage/AssetImage.container.ts, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetImage/AssetImage.types.ts, webapp/src/components/AssetImage/index.ts
Use the skin color, hair color and body shape from the avatar (if possible)
=> feat: use skin hair and body shape from avatar

webapp/src/components/AccountPage/AccountBanner/AccountBanner.css, webapp/src/components/AccountPage/AccountBanner/AccountBanner.tsx
=> fix: blockie size

webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> chore: copies

webapp/src/components/AccountPage/AccountBanner/AccountBanner.tsx, webapp/src/components/AccountSidebar/CurrentAccountSidebar/CurrentAccountSidebar.tsx, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
To be enabled when store settings can be deployed
=> feat: Disable store settings related content

webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx
=> fix: issues

webapp/src/components/CollectionPage/CollectionPage.tsx
Problem : 
By using this link https://market.decentraland.org/collections/0xb96697fa4a3361ba35b774a42c58daccaad1b8e1 we should deselect the My store tab by either do not select any tab or by selecting the collectibles one.
Solution : Selects the collectibles one.
closes #517
=> Deselect 'my store' tab when seeing a collection

webapp/src/components/Bid/Bid.container.ts, webapp/src/components/Bid/Bid.css, webapp/src/components/Bid/Bid.tsx, webapp/src/components/Bid/Bid.types.ts, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/ConfirmInputValueModal/ConfirmInputValueModal.css, webapp/src/components/ConfirmInputValueModal/ConfirmInputValueModal.tsx, webapp/src/components/ConfirmInputValueModal/ConfirmInputValueModal.types.ts, webapp/src/components/ConfirmInputValueModal/index.ts, webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #143 
https://user-images.githubusercontent.com/8763687/150412919-25dfffce-86b3-4b40-bd2e-25d228cde692.mov
=> feat: Add confirm modal when placing/accepting bids

webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Adds a toast message when the store data is updated successfully
=> feat: Add success message store update

webapp/src/components/AssetPage/Actions/Actions.tsx, webapp/src/lib/environment.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Adds a new button so the user can navigate to the builder /names page.
=> feat: Add new Manage button to the name detail page

webapp/src/components/StoreSettings/StoreSettings.tsx, webapp/src/modules/store/sagas.ts, webapp/src/modules/store/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Uses react-router `Prompt` to prevent the router navigation and `onbeforeunload` to prevent closing/refreshing the tab when there are unsaved changes
https://user-images.githubusercontent.com/8763687/150797359-0bc9da04-37b9-4592-b210-abab9c2ae863.mov
=> feat: Prompt user when leaving My Store Settings page with unsaved changes

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetImage/AssetImage.tsx
⛳ ......... ⚪ 
.................................🏌️‍♂️
=> feat: upgraded decentraland-ui

webapp/src/components/AssetImage/AssetImage.container.ts, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetImage/AssetImage.types.ts, webapp/src/modules/analytics/track.ts, webapp/src/modules/store.ts, webapp/src/modules/ui/preview/actions.ts, webapp/src/modules/ui/preview/reducer.ts, webapp/src/modules/ui/preview/selectors.ts, webapp/src/modules/ui/reducer.ts
This PR makes the selection of the preview mode persistent. It also changes the default emote to the fashion one picked by the product team, and also added analytics for the new preview type.
=> feat: persistent try on

webapp/src/components/AssetImage/AssetImage.tsx
=> feat: random pose

webapp/.ci/.env.prd, webapp/.ci/.env.stg, webapp/src/components/AssetImage/AssetImage.tsx
remove hardcoded emotes & replace peer-lb with peer
=> remove hardcoded emotes & replace peer-lb with peer

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetImage/AssetImage.tsx
Upgrade `decentraland-ui` and `@dcl/schemas`, replace deprecated type `AvatarEmote`  with `PreviewEmote`.
=> chore: upgrade dcl-ui

webapp/package-lock.json, webapp/package.json
chore: upgrade dcl-ui and schemas
=> chore: upgrade dcl-ui and schemas

webapp/src/components/Navigation/Navigation.tsx, webapp/src/components/Navigation/Navigation.types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This will get merged to `feat/rankings` with the intention of using it as integration branch.
Closes #625
=> feat: Adds new Overview tab

webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.container.ts, webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx, webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.types.ts, webapp/src/components/AssetPage/CategoryBadge/index.ts, webapp/src/components/AssetPage/IconBadge/IconBadge.tsx, webapp/src/components/AssetPage/IconBadge/IconBadge.types.ts, webapp/src/components/AssetPage/SmartBadge/SmartBadge.container.ts, webapp/src/components/AssetPage/SmartBadge/SmartBadge.tsx, webapp/src/components/AssetPage/SmartBadge/SmartBadge.types.ts, webapp/src/components/AssetPage/SmartBadge/index.ts, webapp/src/components/GenderBadge/GenderBadge.container.ts, webapp/src/components/GenderBadge/GenderBadge.tsx, webapp/src/components/GenderBadge/GenderBadge.types.ts, webapp/src/components/GenderBadge/index.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/selectors.ts
The CategoryBadge, GenderBadge and SmartBadge components were changed to create the url and send it to the IconBadge component.
IconBadge was also modified to accept the url.
This is related to #622
=> feat: use links instead of divs for badges

webapp/src/components/HomePage/HomePage.tsx
=> feat: update the home to the new design

webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/lib/mana.ts
This PR fixes a few issues around the update price modal. 
- When updating a listing, the price was localized and used as the value of the input. This can cause parsing issues in certain languages.
- The expiration date value was not passed to the date field, so the date was not shown.
- The expiration date value was reduced by 1 day on every update.
- The submit button was enabled even when the price input was empty.
Fixes #659
Fixed #660
Fixed #661
=> fix: update price issues

webapp/package-lock.json, webapp/package.json
=> chore: bump dapps

webapp/src/components/CollectionPage/CollectionPage.container.ts, webapp/src/components/CollectionPage/CollectionPage.tsx, webapp/src/components/CollectionPage/CollectionPage.types.ts, webapp/src/components/CollectionPage/utils.ts, webapp/src/modules/collection/selectors.ts, webapp/src/modules/item/selectors.ts, webapp/src/modules/nft/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Support URLs like (ropsten):
```
/collections/0x52c98c80a5aad12056596d3B2dd4139c327BC501
/contracts/0x52c98c80a5aad12056596d3B2dd4139c327BC501/items/0
/0xbcf5784c4cfa38ba49253527e80c9e9510E01C67/tokens/105312291668557186697918027683670432318895095400549111254310977537
```
Closes #668
=> fix: support uppercase contract addresses

webapp/src/modules/store/utils.ts
=> fix: Deploying store with empty banner

webapp/src/modules/routing/sagas.ts
=> fix: remove wearables as the default category for the sales section

webapp/src/components/HomePage/HomePage.container.ts, webapp/src/components/HomePage/HomePage.tsx, webapp/src/components/HomePage/HomePage.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/reducer.ts, webapp/src/modules/sagas.ts, webapp/src/modules/ui/asset/homepage/reducer.ts, webapp/src/modules/ui/types.ts
=> feat: Add support for Rankings FF Variants

webapp/src/components/HomePage/HomePage.container.ts, webapp/src/components/HomePage/HomePage.tsx, webapp/src/components/HomePage/HomePage.types.ts, webapp/src/modules/features/selectors.ts
=> feat: remove home legacy code and enable rankings

webapp/src/components/AnalyticsVolumeDayData/AnalyticsVolumeDayData.css, webapp/src/components/AnalyticsVolumeDayData/utils.ts
=> feat: Round up sales per day stat

webapp/src/components/AssetPage/Expiration/Expiration.tsx
=> fix: Don't show expiration if the expiration value is not valid

webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/utils.ts
=> fix: Marketplace sort filters

webapp/package-lock.json, webapp/package.json, webapp/src/components/AccountSidebar/OtherAccountSidebar/OtherAccountSidebar.tsx, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/vendor/decentraland/item/api.ts, webapp/src/modules/vendor/decentraland/item/types.ts
This PR adds the emote section and categories to the `Originals` sidebar.
Closes #808
=> feat: Add emote categories to originals sidebar

webapp/src/components/AssetPage/ParcelDetail/ParcelDetail.tsx, webapp/src/components/CreateRentalModal/CreateListingStep/index.ts, webapp/src/components/CreateRentalModal/CreateOrEditListingStep/CreateOrEditListingStep.module.css, webapp/src/components/CreateRentalModal/CreateOrEditListingStep/CreateOrEditListingStep.tsx, webapp/src/components/CreateRentalModal/CreateOrEditListingStep/CreateOrEditListingStep.types.ts, webapp/src/components/CreateRentalModal/CreateOrEditListingStep/index.ts, webapp/src/components/CreateRentalModal/RentalModal.tsx, webapp/src/components/CreateRentalModal/RentalModal.types.ts, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.types.ts, webapp/src/modules/order/utils.spec.ts, webapp/src/modules/order/utils.ts, webapp/src/modules/rental/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds the basics to create the rental editing modal. It loads a rental into the form and, changes the titles and adds two new buttons, one to edit it and the other one to cancel it.
=> feat: Add edit listing modal

webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.tsx, webapp/src/components/AssetPage/CategoryBadge/CategoryBadge.types.ts, webapp/src/components/AssetPage/IconBadge/IconBadge.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/modules/routing/search.ts
=> feat: Add Emote Categories badge to the item detail page

webapp/src/components/RankingsTable/RankingItemRow/RankingItemRow.tsx, webapp/src/components/RecentlySoldTable/RecentlySoldTable.css, webapp/src/components/RecentlySoldTable/RecentlySoldTable.tsx
=> fix: Fix missing translations for recently sold emotes

webapp/src/components/AssetPage/IconBadge/IconBadge.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/images/emotes/play-loop.svg, webapp/src/images/emotes/play-once.svg, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Introduce the Emote loop badge

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetPage/IconBadge/IconBadge.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.tsx, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.types.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.container.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.types.ts, webapp/src/images/emotes/play-loop.svg, webapp/src/images/emotes/play-once.svg, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/routing/types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/vendor/decentraland/item/api.ts, webapp/src/modules/vendor/decentraland/item/types.ts, webapp/src/modules/vendor/decentraland/nft/api.ts, webapp/src/modules/vendor/decentraland/nft/types.ts, webapp/src/modules/vendor/utils.ts
This PR allows filter emotes by play mode in the pages Collectibles and My Assets
depends on https://github.com/decentraland/common-schemas/pull/133
=> feat: Filter emotes by play mode

webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.container.tsx, webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.css, webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.tsx, webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Add banner for the mvmf announcement

webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.css
=> feat: add MVMF support for mobile

webapp/src/components/Modals/RentalListingModal/ConfirmationStep/ConfirmationStep.tsx, webapp/src/components/Modals/RentalListingModal/ConfirmationStep/ConfirmationStep.types.ts, webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.tsx, webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.types.ts, webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.container.ts, webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.module.css, webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.tsx, webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.types.ts, webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/index.ts, webapp/src/components/Modals/RentalListingModal/RentalListingModal.module.css, webapp/src/components/Modals/RentalListingModal/RentalListingModal.tsx, webapp/src/modules/modal/sagas.spec.ts, webapp/src/modules/modal/sagas.ts, webapp/src/modules/nft/reducer.ts, webapp/src/modules/rental/actions.ts, webapp/src/modules/rental/reducer.spec.ts, webapp/src/modules/rental/reducer.ts, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts, webapp/src/modules/rental/types.ts, webapp/src/modules/rental/utils.spec.ts, webapp/src/modules/rental/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Introduce the Edit Rental Listing flow

webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.css
=> feat: Add new MVMF banner

webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.css
=> feat: Adapt festival banners to mobile

webapp/src/components/AssetPage/MVMFBadge/MVMFBadge.container.tsx, webapp/src/components/AssetPage/MVMFBadge/MVMFBadge.tsx, webapp/src/components/AssetPage/MVMFBadge/MVMFBadge.types.ts, webapp/src/components/MVMFPage/MVMFBanner/MVMFBanner.css
Using the new Feature Flag called `builder-mvmf-2022-tab`
=> feat: Enable the MVMF Badge alongside the Tab

indexer/README.md, indexer/package.json, indexer/schema.graphql, indexer/scripts/deploy.ts, indexer/src/handlers/estate.ts, indexer/src/modules/estate/index.ts
=> feat: Derive parcels in estate for performance

webapp/package-lock.json, webapp/package.json, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts
=> feat: add "target" field as the zero address for now

webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx, webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> fix: fix the fat finger protection for rentals

webapp/src/components/AssetCard/AssetCard.container.ts
=> fix: do not show listed tag in the home page

webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/ManageAssetPage/Sell/Sell.container.ts, webapp/src/components/ManageAssetPage/Sell/Sell.tsx, webapp/src/components/ManageAssetPage/Sell/Sell.types.ts
=> feat: Use the existing pages for the ManageAssetPage actions

webapp/src/components/ManageAssetPage/Sell/Sell.module.css, webapp/src/components/ManageAssetPage/Sell/Sell.tsx
=> fix: add the proper styles to the list for sell button

webapp/src/components/ManageAssetPage/Rent/Rent.module.css, webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.module.css, webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.tsx, webapp/src/modules/rental/sagas.ts
=> feat: Add fingerprint when accepting a estate rent

webapp/src/components/AssetPage/SaleRentActionBox/PeriodsDropdown/PeriodsDropdown.module.css
=> feat: fix the global CSS selector for the periodDropdown mana component

webapp/src/modules/analytics/track.ts
=> feat: Add tracking for rental events

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
=> fix: Make buy and bid buttons navigate to the pages

webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.tsx, webapp/src/components/Vendor/NFTFilters/NFTFilters.css
=> fix: smart item on phablet and tablet screen

webapp/src/modules/modal/sagas.spec.ts, webapp/src/modules/modal/sagas.ts, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts
=> feat: Add logic to wait until rental is executed and close modal

webapp/src/components/AssetBrowse/AssetBrowse.tsx
=> fix: hide the onRent based on the FF for mobile menu

webapp/src/modules/rental/reducer.spec.ts, webapp/src/modules/rental/reducer.ts, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts
=> feat: Updates the state after accepting a rental listing

webapp/src/components/Bid/AcceptButton/AcceptButton.tsx, webapp/src/components/Bid/AcceptButton/AcceptButton.types.ts, webapp/src/components/Bid/Bid.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Prevent bids from being accepted when an asset is being rented

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetPage/BaseDetail/BaseDetail.css, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds a banner on the bottom of the `SaleAndRentBox` to show the user that LAND is being rented.
Closes #951
=> feat: Rented until in LAND detail

webapp/src/components/OnSaleOrRentList/OnRentListElement/OnRentListElement.tsx, webapp/src/components/OnSaleOrRentList/OnSaleOrRentList.container.ts, webapp/src/modules/ui/browse/selector.spec.ts, webapp/src/modules/ui/browse/selectors.ts
=> feat: use "rentedDays" field to get the endDate of the rental

webapp/src/modules/rental/reducer.spec.ts, webapp/src/modules/rental/reducer.ts
=> fix: Update reducer when submitting the accept listing transaction

webapp/package-lock.json, webapp/package.json, webapp/src/modules/vendor/decentraland/ContractService.ts, webapp/src/modules/wallet/sagas.ts
This PR updates the authorizations saga to load authorizations from the rentals contract in mainnet.
=> fix: Add rentals mainnet contract

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/Bid/AcceptButton/AcceptButton.tsx, webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/modules/rental/utils.spec.ts, webapp/src/modules/rental/utils.ts
This PR refactors some rentals methods that were used in multiple places.
=> fix: Refactor rentals utilities

webapp/src/components/Atlas/Atlas.container.ts, webapp/src/components/Atlas/Atlas.tsx, webapp/src/components/Atlas/Atlas.types.ts
=> feat: show rented lands on the Atlas component

webapp/src/components/AssetPage/RentalHistory/RentalHistory.tsx
This PR fixes an issue where placeholders where left for the RentalHistory component, making the real data to not be shown.
=> fix: Rental history not showing days and price correctly

webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.tsx
=> fix: Edit confirmation step buttons not disabled when loading

webapp/src/components/Modals/RentalListingModal/RentalListingModal.tsx, webapp/src/modules/asset/utils.spec.ts, webapp/src/modules/asset/utils.ts, webapp/src/modules/bid/sagas.ts, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts, webapp/src/modules/rental/utils.spec.ts, webapp/src/modules/rental/utils.ts
- When accepting a bid, it should call the refresh to cancel a rental listing if opened
Closes #988
=> feat: Update the owner-by logic depending of the Rental scenario

webapp/package-lock.json, webapp/package.json, webapp/src/components/Atlas/Atlas.tsx, webapp/src/lib/error.ts, webapp/src/modules/account/sagas.ts, webapp/src/modules/analytics/sagas.ts, webapp/src/modules/bid/sagas.ts, webapp/src/modules/bid/utils.ts, webapp/src/modules/collection/sagas.ts, webapp/src/modules/contract/sagas.ts, webapp/src/modules/event/sagas.ts, webapp/src/modules/identity/sagas.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/nft/sagas.ts, webapp/src/modules/order/sagas.ts, webapp/src/modules/proximity/sagas.ts, webapp/src/modules/sale/sagas.ts, webapp/src/modules/store/sagas.ts, webapp/src/modules/tile/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Update TS to its latest version and check for errors to avoid crashing when there's an unknown error.
=> fix: Check is error and update TS

webapp/src/components/OnSaleOrRentList/OnRentListElement/OnRentListElement.css, webapp/src/components/OnSaleOrRentList/OnRentListElement/OnRentListElement.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> fix: Add the "rented period over" status on the on rent list

webapp/src/modules/contract/utils.ts, webapp/src/modules/wallet/sagas.ts
Fixes the issue where the loop of the authorizations gets stuck
=> fix: authorizations

webapp/src/components/OnSaleOrRentList/OnRentListElement/OnRentListElement.tsx, webapp/src/modules/nft/sagas.spec.ts, webapp/src/modules/nft/sagas.ts
=> feat: Cancel open listings on nft transfer

webapp/src/modules/order/reducer.spec.ts, webapp/src/modules/order/reducer.ts
=> fix: Remove order when renting

webapp/src/components/AssetPage/AssetPage.tsx, webapp/src/components/AssetProvider/AssetProvider.container.ts, webapp/src/components/AssetProvider/AssetProvider.tsx, webapp/src/components/AssetProvider/AssetProvider.types.ts, webapp/src/modules/features/selectors.ts
=> fix: Re-use the asset provider in the AssetPage

webapp/src/components/AssetCard/AssetCard.tsx
=> fix: Show rentals price up when there's no order

webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR changes the text `Not available for Sale` for `Currently not listed for sale` as its better than the old one.
Closes #994
=> fix: Change not listed for sale

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
=> fix: Users can bid on LANDs they own but are rented

webapp/src/modules/ui/browse/selector.spec.ts, webapp/src/modules/ui/browse/selectors.ts
=> fix: add open/executed status to the getOnRentNFTs selector

webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts
=> fix: add logic to wait until the rental and nft are updated after claiming

webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/components/ManageAssetPage/Sell/Sell.tsx, webapp/src/components/Modals/ClaimLandModal/ClaimLandModal.container.ts, webapp/src/components/Modals/ClaimLandModal/ClaimLandModal.tsx, webapp/src/components/OnSaleOrRentList/OnRentListElement/OnRentListElement.tsx, webapp/src/modules/analytics/track.ts, webapp/src/modules/modal/sagas.spec.ts, webapp/src/modules/modal/sagas.ts, webapp/src/modules/nft/utils.ts, webapp/src/modules/rental/actions.ts, webapp/src/modules/rental/reducer.spec.ts, webapp/src/modules/rental/reducer.ts, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts, webapp/src/modules/rental/selector.spec.ts, webapp/src/modules/rental/selectors.ts, webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/ui/browse/selector.spec.ts, webapp/src/modules/ui/browse/selectors.ts
=> feat: Rename LAND to Parcel/Estate

webapp/src/components/ManageAssetPage/Rent/Rent.module.css, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> fix: Add view listing button

webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.module.css, webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: add the tooltip in the rental listing expiration field

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/components/Modals/ClaimLandModal/ClaimLandModal.tsx, webapp/src/components/OnSaleOrRentList/OnRentListElement/OnRentListElement.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR fixes a couple of translation issues.
=> fix: Rentals translation issues

webapp/src/components/Modals/RentalListingModal/ConfirmationStep/ConfirmationStep.container.ts, webapp/src/components/Modals/RentalListingModal/ConfirmationStep/ConfirmationStep.tsx, webapp/src/components/Modals/RentalListingModal/ConfirmationStep/ConfirmationStep.types.ts, webapp/src/modules/rental/actions.ts, webapp/src/modules/rental/reducer.ts
Closes #1044
Rejecting the sign
Going back and continue again
=> feat: add logic to clear rental errors in the listing modal

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.container.ts, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/wallet/selector.spec.ts, webapp/src/modules/wallet/selectors.ts
=> fix: Block buy and rent button if there's no enough MANA

webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/modules/analytics/track.ts, webapp/src/modules/nft/actions.ts, webapp/src/modules/nft/sagas.spec.ts, webapp/src/modules/nft/sagas.ts
=> fix: fix logic of waiting for transfer transaction to finish

webapp/package-lock.json, webapp/package.json
=> fix: Update dcl dapps to update the waitForTx utility

webapp/src/components/ManageAssetPage/Sell/Sell.tsx
=> fix: Wrong is Land locked at Sell component

webapp/src/components/ManageAssetPage/Rent/Rent.module.css, webapp/src/components/ManageAssetPage/Rent/Rent.tsx
=> fix: Profile too close to text

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
This PR only shows the buy or rent button if there's enough MANA to buy or rent a LAND.
=> fix: Only show not enough MANA if logged in

webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/modules/rental/actions.spec.ts, webapp/src/modules/rental/actions.ts, webapp/src/modules/rental/reducer.spec.ts, webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds to the activity the accept rental transaction item that was missing.
Closes #1115
=> fix: Add accept rental transaction to activity

webapp/src/components/AssetBrowse/AssetBrowse.container.ts, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetBrowse/AssetBrowse.types.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/modules/ui/utils.ts
=> feat: Persist selected LAND view

webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.module.css
=> fixed style margin for one day rental

webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/modules/analytics/track.ts, webapp/src/modules/bid/actions.ts, webapp/src/modules/bid/sagas.spec.ts, webapp/src/modules/bid/sagas.ts
=> feat: add waitForTx to the accept bid flow

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css, webapp/src/components/BidPage/BidModal/BidModal.css, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/BidPage/BidModal/BidModal.types.ts, webapp/src/components/BidPage/BidPage.tsx, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
- Shows a message on the bids page if the land is being rented and the user wants to bid on it.
- Fixes a wrong margin on the `SalesRentActionBox`.
- Blocks the inputs in the `ConfirmRentModal` while it's loading.
Closes #1123
=> fix: Show message on biddable rented land

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/index.css, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Add link to builder if tenant

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.module.css
=> feat: make modals mobile available

webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts, webapp/src/modules/rental/utils.spec.ts, webapp/src/modules/rental/utils.ts
=> fix: Enforce signatures to have a V as 27 or 28

indexer/README.md, indexer/schema.graphql, indexer/src/handlers/nft.ts
Closes #1092 
Assigns the value of transferredAt on:
- handleTransfer
=> feat: Add transferredAt property to NFTs

webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/modules/contract/selectors.ts
=> fix: Blank page on settings while loading

webapp/src/components/AssetProvider/AssetProvider.container.ts, webapp/src/components/AssetProvider/AssetProvider.tsx, webapp/src/components/AssetProvider/AssetProvider.types.ts, webapp/src/modules/vendor/decentraland/contracts.ts
+ Don't refetch assets on AssetProvider
=> fix: Don't provide rental options to non land or estate nfts on AssetProvider

webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Update for minting to to buy

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/BrowsePage/BrowsePage.container.ts, webapp/src/components/BrowsePage/BrowsePage.tsx, webapp/src/components/BrowsePage/BrowsePage.types.ts, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.tsx, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.types.ts, webapp/src/components/Vendor/NFTFilters/NFTFilters.tsx, webapp/src/components/Vendor/NFTFilters/NFTFilters.types.ts, webapp/src/components/Vendor/NFTFilters/SelectFilter/SelectFilter.css, webapp/src/components/Vendor/NFTFilters/SelectFilter/SelectFilter.tsx, webapp/src/components/Vendor/NFTFilters/SelectFilter/SelectFilter.types.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.container.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.types.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
The cut in the middle of the video is because I refreshed the page to show that the selected collection is still displayed.
https://user-images.githubusercontent.com/24811313/209815002-b74a2aa1-f5b5-4a27-86ba-750de6099414.mov
=> feat: Search Input for collections now looks for options on demand

webapp/src/components/AssetBrowse/AssetBrowse.container.ts, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.container.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/modules/routing/utils.spec.ts, webapp/src/modules/routing/utils.ts, webapp/src/modules/ui/browse/selectors.ts
=> Fix: Don't show land map on account or current account

webapp/src/modules/vendor/decentraland/bid/api.spec.ts, webapp/src/modules/vendor/decentraland/bid/api.ts
=> fix: Show all bids instead of just 20

webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetBrowse/ToggleBox/ToggleBox.module.css, webapp/src/components/BackToTopButton/BackToTopButton.module.css, webapp/src/components/BackToTopButton/BackToTopButton.tsx, webapp/src/components/BackToTopButton/BackToTopButton.types.ts, webapp/src/components/BackToTopButton/index.ts, webapp/src/components/HomePage/HomePage.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #727
https://user-images.githubusercontent.com/8763687/210236876-1fcb934e-f7b0-4b69-9a37-6e231372d7f3.mov
This PR also fixes some style issues with the store/listings component, now looks like this:
=> feat: Add the "Back to top" button to the AssetBrowse

webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx
Disallow rents with the beneficiary as 0x0...0.
Closes #1177
=> fix: Don't allow renting with address zero

webapp/package-lock.json, webapp/package.json, webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Related to https://github.com/decentraland/decentraland-dapps/pull/335
=> feat: Map MANA purchases as transaction in the Activity Page

webapp/src/components/AssetBrowse/AssetBrowse.css
Set sidebar width to be 248 instead 320 (full width size)
=> fix: set correct sidebar width

webapp/src/components/BackToTopButton/BackToTopButton.module.css, webapp/src/components/BackToTopButton/BackToTopButton.tsx
Closes #1235
https://user-images.githubusercontent.com/8763687/210833057-81bef414-d322-4d50-8f09-0fb37d245ce6.mov
=> feat: Add styles for mobile to the back to top button

webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.css, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Better empty state for the asset browse component

webapp/src/components/AssetFilters/AssetFilters.tsx, webapp/src/components/AssetTopbar/AssetTopbar.tsx
Closes #1216
https://user-images.githubusercontent.com/8763687/211558595-fbe13e44-6635-4e3d-9762-59d3992d5580.mov
=> feat: Reset section when performing a search

webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/components/AssetTopbar/AssetTopbar.container.ts, webapp/src/components/AssetTopbar/AssetTopbar.module.css, webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/components/AssetTopbar/AssetTopbar.types.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> fix: clear search on clear filters and style adjustments

webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/vendor/decentraland/item/api.ts, webapp/src/modules/vendor/decentraland/item/types.ts
=> fix: add price filters params for the items fetch

webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/components/AssetTopbar/SelectedFilters/SelectedFilters.tsx
- REmove selected filters if the user is in map view
- Fix filter tag appearing when all lands are selected
=> fix: do not show selected filters on map view

webapp/src/components/AssetFilters/PriceFilter/PriceFilter.css, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx, webapp/src/components/AssetTopbar/AssetTopbar.module.css, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/themes/components/Menu.css
=> fix: some new Filters UI issues

webapp/src/components/AssetTopbar/AssetTopbar.module.css, webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/components/AssetTopbar/SelectedFilters/SelectedFilters.module.css
=> fix: Fix layout for clear filters in mobile

webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/AssetList/AssetList.css, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetTopbar/AssetTopbar.module.css, webapp/src/components/AssetTopbar/AssetTopbar.tsx
Closes #1297
##Solution
https://user-images.githubusercontent.com/8763687/212130097-f2bbe020-8b08-42ad-af46-68ece5dc73f7.mov
=> fix: Loading spinner position for AssetBrowse component

webapp/src/components/AssetPage/SaleActionBox/BuyNFTButtons/BuyNFTButtons.module.css, webapp/src/components/AssetPage/SaleActionBox/ItemSaleActions/ItemSaleActions.module.css, webapp/src/components/AssetPage/SaleActionBox/NFTSaleActions/NFTSaleActions.module.css, webapp/src/components/AssetPage/SaleActionBox/SaleActionBox.module.css, webapp/src/components/ManageAssetPage/Details/Details.module.css, webapp/src/components/ManageAssetPage/Details/Details.tsx, webapp/src/components/ManageAssetPage/Details/Info/Info.module.css, webapp/src/components/ManageAssetPage/Details/Info/Info.tsx, webapp/src/components/ManageAssetPage/Details/Info/Info.types.ts, webapp/src/components/ManageAssetPage/Details/Info/index.ts, webapp/src/modules/asset/utils.ts, webapp/src/modules/routing/locations.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Add detail box component in item detail

webapp/src/components/Navigation/Navigation.css
Closes #1213
https://user-images.githubusercontent.com/8763687/212329600-fb66ad28-69d7-4269-a999-c3dc33650912.mov
=> feat: flip tabs horizontally for mobile

webapp/package-lock.json, webapp/package.json, webapp/src/components/Chip/Chip.css, webapp/src/components/Chip/Chip.tsx, webapp/src/components/Chip/Chip.types.ts, webapp/src/components/Vendor/NFTFilters/ArrayFilter/ArrayFilter.css, webapp/src/components/Vendor/NFTFilters/ArrayFilter/ArrayFilter.tsx
=> feat: add outlines to missing elements

webapp/src/components/AssetPage/SaleActionBox/BuyNFTButtons/BuyNFTButtons.tsx, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.containter.ts, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.types.ts, webapp/src/components/BuyPage/BuyPage.css, webapp/src/components/BuyPage/CardPaymentsExplanation/CardPaymentsExplanation.tsx, webapp/src/components/BuyPage/CardPaymentsExplanation/CardPaymentsExplanation.types.ts, webapp/src/components/BuyPage/CardPaymentsExplanation/index.ts, webapp/src/components/BuyPage/MintItemModal/MintItemModal.containter.ts, webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx, webapp/src/components/BuyPage/MintItemModal/MintItemModal.types.ts, webapp/src/modules/routing/locations.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: add Buy with Card Page

webapp/src/components/Menu/DropdownMenu/DropdownMenu.tsx, webapp/src/components/Menu/MenuItem/MenuItem.css, webapp/src/components/Menu/MenuItem/MenuItem.tsx, webapp/src/components/Vendor/decentraland/NFTSections/NFTSectionsMenuItems/NFTSectionsMenuItems.tsx
- collapse dropdown menu item when clicked twice
- if the section doesn't change do not call onChange again
https://user-images.githubusercontent.com/11800206/212762453-985ba4b7-cad2-448e-b22f-411ab1f214df.mov
=> feat: add category dropdown collapsible option

webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx
Fixes the component logic, it was not comparing the min & max correctly (they are strings, so they need to be casted)
=> fix: price filter logic

webapp/src/components/AssetFilters/AssetFilters.css, webapp/src/components/Modals/AssetFiltersModal/AssetFiltersModal.container.ts, webapp/src/components/Modals/AssetFiltersModal/AssetFiltersModal.tsx, webapp/src/components/Modals/AssetFiltersModal/AssetFiltersModal.types.ts, webapp/src/components/Modals/AssetFiltersModal/CategoryFilter/CategoryFilter.css, webapp/src/lib/utils.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/utils.ts
Fix several ui issues in filter section
- Fix collection filter field overgrowing when filtering with a very large collection name
- Reset button not applied until user press save
- Add rounded corners to menu in mobile view
=> fix: filters ui issues

webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.containter.ts, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.types.ts, webapp/src/components/BuyPage/MintItemModal/MintItemModal.containter.ts, webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx, webapp/src/components/BuyPage/MintItemModal/MintItemModal.types.ts, webapp/src/components/Modals/BuyWithCardExplanationModal/BuyWithCardExplanationModal.module.css, webapp/src/components/Modals/BuyWithCardExplanationModal/BuyWithCardExplanationModal.tsx, webapp/src/modules/asset/utils.ts, webapp/src/modules/item/actions.spec.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/order/actions.spec.ts, webapp/src/modules/order/actions.ts, webapp/src/modules/order/sagas.spec.ts, webapp/src/modules/order/sagas.ts
=> feat: Open explanation modal only the 1st time

webapp/src/components/Modals/RentConfirmedModal/RentConfirmedModal.tsx
=> fix: builder link used to go to collections fixed to scenes

webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.module.css
closes #1318 
web:
tablet: 
phone:
=> fix: fixed icon position on different screens for list for sale date field

webapp/src/components/AssetFilters/AssetFilters.tsx, webapp/src/components/AssetFilters/utilts.ts, webapp/src/components/CollectionList/CollectionList.module.css, webapp/src/components/HomePage/Slideshow/Slideshow.css, webapp/src/components/HomePage/Slideshow/Slideshow.tsx
Improve slideshow arrows position
=> fix: slideshow arrows

webapp/src/components/ManageAssetPage/Sell/Sell.container.ts, webapp/src/components/ManageAssetPage/Sell/Sell.tsx, webapp/src/components/ManageAssetPage/Sell/Sell.types.ts, webapp/src/components/Modals/SellModal/SellModal.container.ts, webapp/src/components/Modals/SellModal/SellModal.tsx, webapp/src/components/Modals/SellModal/SellModal.types.ts
=> feat: edit and delete listing for sale

webapp/package-lock.json, webapp/package.json, webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/modules/asset/sagas.spec.ts, webapp/src/modules/asset/sagas.ts, webapp/src/modules/item/actions.spec.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/reducer.spec.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/order/actions.spec.ts, webapp/src/modules/order/actions.ts, webapp/src/modules/order/reducer.spec.ts, webapp/src/modules/order/sagas.spec.ts, webapp/src/modules/order/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Show NFT purchase in the activity page

webapp/src/components/Modals/SellModal/SellModal.tsx
=> fix: Accessing null value

.github/workflows/codeql.yml
Signed-off-by: Lautaro Petaccio <1120791+LautaroPetaccio@users.noreply.github.com>
=> chore: Add security job

webapp/package-lock.json, webapp/package.json, webapp/src/modules/routing/search.ts
=> feat(First Listed At): Use RECENTLY_LISTED when sorting by recently listed for items

webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts
=> fix: show not on sale LANDs as well

webapp/src/components/AssetFilters/AssetFilters.container.ts, webapp/src/components/AssetFilters/AssetFilters.tsx, webapp/src/components/AssetFilters/AssetFilters.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts
=> feat: Add Estate Size Filter FF and fix filters applied selector

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetFilters/EstateSizeFilter/EstateSizeFilter.tsx, webapp/src/components/AssetFilters/Inventory/Inventory.tsx, webapp/src/components/AssetFilters/Inventory/Inventory.types.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/utils.ts
and also remove the decimals for the small ranges (<10)
Closes #1405
=> fix: Remove estateSize filters on the Clear All Filters action

webapp/package-lock.json, webapp/package.json
Related to https://github.com/decentraland/decentraland-dapps/pull/365
=> chore: Bump dapps to close Transak widget on back to app

webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx, webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx
=> fix: Don't show costless tx msg when buying nft with card

webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx, webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx
=> fix: Don't open authorization modal when buying nfts with card

webapp/src/components/AssetFilters/LocationFilter/LocationFilter.module.css, webapp/src/components/AssetFilters/LocationFilter/LocationFilter.spec.tsx, webapp/src/components/AssetFilters/LocationFilter/LocationFilter.tsx
Fix mobile layout for location filter
=> fix: add correct style to box

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetFilters/AssetFilters.tsx, webapp/src/components/AssetFilters/EstateSizeFilter/EstateSizeFilter.tsx, webapp/src/components/AssetFilters/EstateSizeFilter/EstateSizeFilter.types.ts, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.container.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.types.ts, webapp/src/modules/vendor/decentraland/nft/api.ts
=> feat: sync land filters between them

webapp/src/components/AssetFilters/AssetFilters.tsx
=> fix: on sale toggle sortBy

webapp/src/components/AssetFilters/CreatorsFilter/CreatorsFilter.css, webapp/src/components/AssetFilters/CreatorsFilter/CreatorsFilter.tsx, webapp/src/components/AssetFilters/CreatorsFilter/utils.spec.ts, webapp/src/components/AssetFilters/CreatorsFilter/utils.ts, webapp/src/components/AssetTopbar/SelectedFilters/SelectedFilters.tsx, webapp/src/components/BackToTopButton/BackToTopButton.module.css, webapp/src/components/Modals/AssetFiltersModal/AssetFiltersModal.tsx, webapp/src/lib/profiles.spec.ts, webapp/src/lib/profiles.ts, webapp/src/modules/account/reducer.spec.ts, webapp/src/modules/account/reducer.ts, webapp/src/modules/account/sagas.spec.ts, webapp/src/modules/account/sagas.ts, webapp/src/modules/account/selectors.spec.ts, webapp/src/modules/account/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Enhancements for the creators filter

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetBrowse/AssetBrowse.container.ts, webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetBrowse/AssetBrowse.types.ts, webapp/src/components/AssetBrowse/MapTopbar/MapTopbar.container.ts, webapp/src/components/AssetBrowse/MapTopbar/MapTopbar.module.css, webapp/src/components/AssetBrowse/MapTopbar/MapTopbar.tsx, webapp/src/components/AssetBrowse/MapTopbar/MapTopbar.types.ts, webapp/src/components/AssetBrowse/MapTopbar/index.ts, webapp/src/components/AssetFilters/AssetFilters.css, webapp/src/components/AssetFilters/RentalPeriodFilter/RentalPeriodFilter.tsx, webapp/src/components/AssetImage/AssetImage.css, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetTopbar/AssetTopbar.module.css, webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/components/Atlas/Atlas.css, webapp/src/components/Atlas/Atlas.tsx, webapp/src/components/Atlas/Atlas.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/themes/components/Checkbox.css
Add the possibility to filter in map view by: `Parcels for sale` `Parcels to rent` or `owned by me` 
Closes #1464
=> feat: add map view filters

webapp/src/components/AssetFilters/PriceFilter/PriceFilter.container.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/vendor/decentraland/rentals/api.spec.ts, webapp/src/modules/vendor/decentraland/rentals/api.ts, webapp/src/modules/vendor/decentraland/rentals/utils.spec.ts, webapp/src/modules/vendor/decentraland/rentals/utils.ts
Add rentals price filter inventory chart
=> feat: add price chart to rentals

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetBrowse/MapBrowse/MapBrowse.container.ts, webapp/src/components/AssetBrowse/MapBrowse/MapBrowse.tsx, webapp/src/components/AssetBrowse/MapBrowse/MapBrowse.types.ts, webapp/src/components/AssetBrowse/MapBrowse/index.ts, webapp/src/components/AssetBrowse/MapBrowse/utils.spec.ts, webapp/src/components/AssetBrowse/MapBrowse/utils.ts, webapp/src/components/AssetBrowse/MapTopbar/MapTopbar.tsx, webapp/src/modules/ui/browse/selector.spec.ts, webapp/src/modules/ui/browse/selectors.ts
This pr does various fixes to map view in land section:
- Adds the possibility to zoom out more
- Fix click outside when closing filters popover in mobile
- Zoom to nearest land when filters are toggled
=> fix: add more zoom to map

webapp/package-lock.json, webapp/package.json
Bump new ui version so that it includes chart fix https://github.com/decentraland/ui/pull/312
=> feat: bump ui version

webapp/src/components/AssetBrowse/AssetBrowse.container.ts, webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetBrowse/AssetBrowse.types.ts, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/components/AssetList/utils.spec.ts, webapp/src/components/AssetList/utils.ts, webapp/src/modules/routing/reducer.ts, webapp/src/modules/routing/selectors.ts
Scroll to selected item when going from detail page to collectibles
https://user-images.githubusercontent.com/11800206/228032880-769f34b9-4896-418e-ad24-38fcd8ca9332.mov
=> feat: save scroll when going back

webapp/package-lock.json, webapp/package.json, webapp/src/components/AccountPage/AccountBanner/AccountBanner.tsx, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/lib/copyText.spec.ts, webapp/src/lib/copyText.tsx
@LautaroPetaccio here is a new pull request!, hope this time we got it!
=> refactor: removed copy-to-clip lib

README.md
This PR adds a "how to contribute" section explaining how to contribute to the Marketplace.
=> feat: How to contribute

webapp/src/modules/analytics/track.ts, webapp/src/utils/events.ts
=> feat: Track events related to the pick/unpick mechanism

webapp/src/components/FavoritesCounter/FavoritesCounter.module.css, webapp/src/components/FavoritesCounter/FavoritesCounter.spec.tsx, webapp/src/components/FavoritesCounter/FavoritesCounter.tsx, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #1527 
Normal state: 
Hovering the asset card:
Hovering the counter:
Detail Page:
=> feat: New styles for the favorites counter

webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/AssetList/AssetList.css
Fixed the loader vertically, and centered it horizontally:
=> fix: Fix styles on loading an empty states

webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Show error message on fetching assets failure

webapp/src/modules/vendor/utils.ts
=> fix: creator filter not working for nfts page

webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx
=> feat: removed MANA authorization for free items

webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #1474 
IMPORTANT: This should be merged once the `builder-dcl-controller-v2` flag is enabled.
=> feat(Names): Update dao message to include name minting fees

webapp/package-lock.json, webapp/package.json, webapp/src/index.css, webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #1562 
Closes #1563 
Closes #1565
Closes #1574
=> fix: Fix Lists related toast styles

webapp/src/components/Modals/FavoritesModal/FavoritesModal.container.ts, webapp/src/components/Modals/FavoritesModal/FavoritesModal.spec.tsx, webapp/src/components/Modals/FavoritesModal/FavoritesModal.tsx, webapp/src/components/Modals/FavoritesModal/FavoritesModal.types.ts, webapp/src/components/Modals/FavoritesModal/index.ts, webapp/src/modules/favorites/reducer.spec.ts, webapp/src/modules/favorites/reducer.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/modules/sagas.ts, webapp/src/modules/vendor/decentraland/favorites/api.spec.ts, webapp/src/modules/vendor/decentraland/favorites/api.ts
=> feat: Get who fav an item with auth

webapp/src/components/FavoritesCounter/FavoritesCounter.module.css
Closes #1596 
[Preview](https://www.loom.com/share/2f8dff7927ab42eab0cf085842ccda99)
=> fix: Apply effect only when hovering the bubble in the detail page

webapp/package-lock.json, webapp/package.json
=> chore: Upgrade UI

webapp/src/components/HomePage/Slideshow/Slideshow.css
Closes #1598 
[Preview](https://www.loom.com/share/a88c0f1edc6142f6b9abc2d0f2c77a4e)
=> fix: Change css so the arrows appear in the same place without overlapping the space of the card

webapp/src/components/FavoritesCounter/FavoritesCounter.container.ts, webapp/src/components/FavoritesCounter/FavoritesCounter.module.css, webapp/src/components/FavoritesCounter/FavoritesCounter.tsx, webapp/src/components/FavoritesCounter/FavoritesCounter.types.ts, webapp/src/modules/favorites/selectors.spec.ts, webapp/src/modules/favorites/selectors.ts
Closes #1588 
[Preview](https://www.loom.com/share/960abbfdfe23439e86796d88bf58e5ff)
Mobile:
Desktop:
=> feat: Show loader when picking & unpicking

webapp/src/components/AssetCard/AssetCard.spec.tsx, webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/modules/favorites/actions.spec.ts, webapp/src/modules/favorites/actions.ts, webapp/src/modules/favorites/reducer.spec.ts, webapp/src/modules/favorites/reducer.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/modules/favorites/selectors.spec.ts, webapp/src/modules/favorites/selectors.ts, webapp/src/modules/favorites/types.ts, webapp/src/modules/ui/browse/reducer.spec.ts, webapp/src/modules/ui/browse/reducer.ts, webapp/src/modules/ui/browse/sagas.spec.ts, webapp/src/modules/ui/browse/sagas.ts, webapp/src/modules/ui/browse/selector.spec.ts, webapp/src/modules/ui/browse/selectors.ts, webapp/src/modules/ui/browse/utils.spec.ts, webapp/src/modules/ui/browse/utils.ts, webapp/src/modules/ui/sagas.ts, webapp/src/modules/vendor/decentraland/favorites/api.spec.ts, webapp/src/modules/vendor/decentraland/favorites/api.ts
This PR adds the capability of unpicking items in the My List section.
Closes #1566
=> feat: Unpick items in My List

webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/modules/routing/selectors.ts
=> fix: Wait until finish loading to render assets

webapp/src/components/AssetList/AssetList.css, webapp/src/components/FavoritesCounter/FavoritesCounter.module.css, webapp/src/components/ListsPage/ListsPage.module.css, webapp/src/components/ListsPage/ListsPage.tsx
Closes #1622
Closes #1626
Closes #1627 
Closes #1628
Closes #1630
=> fix: Favorites visual fixes

webapp/src/components/Modals/FavoritesModal/FavoritesModal.tsx
=> fix: Slice address correctly at the Favorites Modal

webapp/package-lock.json, webapp/package.json, webapp/src/modules/wallet/sagas.spec.ts, webapp/src/modules/wallet/sagas.ts
=> fix: Reload when changing account or disconnecting

webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetTopbar/AssetTopbar.container.ts, webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/modules/favorites/actions.spec.ts, webapp/src/modules/favorites/actions.ts, webapp/src/modules/favorites/reducer.spec.ts, webapp/src/modules/favorites/reducer.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/modules/item/reducer.spec.ts, webapp/src/modules/item/reducer.ts, webapp/src/modules/ui/browse/reducer.spec.ts, webapp/src/modules/ui/browse/reducer.ts, webapp/src/modules/ui/browse/sagas.spec.ts, webapp/src/modules/ui/browse/sagas.ts
This PR refactors how we retrieve and process favorited items to fix #1624.
=> refactor: Refactor fetch favorited items

webapp/src/lib/error.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/vendor/decentraland/favorites/api.spec.ts, webapp/src/modules/vendor/decentraland/favorites/api.ts
=> fix: Ignore item already picked as favorite API error

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.container.ts, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.types.ts, webapp/src/components/HOC/withAuthorizedAction/withAuthorizedAction.tsx, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.container.ts, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.types.ts, webapp/src/modules/rental/selector.spec.ts, webapp/src/modules/rental/selectors.ts
Move authorization check after rent confirmation instead of before
https://user-images.githubusercontent.com/11800206/235533101-d807b89b-a7de-43a8-a728-9389e453442f.mov
=> fix: authorization after rent confirmation

webapp/package-lock.json, webapp/package.json, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.container.ts, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.spec.tsx, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.types.ts, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/utils.tsx, webapp/src/components/HOC/withAuthorizedAction/withAuthorizedAction.tsx, webapp/src/modules/contract/selectors.ts, webapp/src/modules/contract/utils.spec.ts, webapp/src/modules/contract/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
- Add logic to call new authorization flow saga that will handle all steps of authorization.
- Add not enough allowance error
=> fix: authorization flow states

webapp/package-lock.json, webapp/package.json
This PR upgrades the `decentraland-dapps` and `decentraland-ui` packages to fix the click priority in the navbar and track users' clicks on the navbar menu and submenus.
=> chore: Upgrade decentraland-dapps and decentraland-ui packages

webapp/package-lock.json, webapp/package.json, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.container.ts, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.spec.tsx, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/AuthorizationModal.tsx, webapp/src/components/HOC/withAuthorizedAction/AuthorizationModal/utils.tsx, webapp/src/components/HOC/withAuthorizedAction/withAuthorizedAction.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Add reuathorize flow for ethereum when users sets a cap that is lower to the current item value
https://user-images.githubusercontent.com/11800206/236993940-15ea1167-d5e2-4563-b1c3-f5e46d140654.mov
=> feat: add reauthorize flow for ethereum

webapp/src/components/AssetList/AssetList.css, webapp/src/components/HomePage/Slideshow/Slideshow.css, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/modules/item/reducer.spec.ts, webapp/src/modules/item/reducer.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/utils.spec.ts, webapp/src/modules/routing/utils.ts, webapp/src/modules/vendor/decentraland/catalog/api.ts
This PR includes:
Also: 
- When an item is already in the state and it's requested again, the success action will merge the results (to preserve any extra data that is missing in the second request). This happens when the catalog is fetched and then an item is fetched using the Item API .
=> feat: Add new catalog cards to My List, Accounts and HomePage

webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/AssetCard/AssetCard.css, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/AssetFilters/AssetFilters.tsx, webapp/src/components/AssetTopbar/AssetTopbar.tsx
=> feat: catalog styles for the new cards in mobile

webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts
Closes #1674
https://github.com/decentraland/marketplace/assets/8763687/56df1b9e-604c-4480-94c0-726a635777c4
https://github.com/decentraland/marketplace/assets/8763687/89538cac-4df1-419e-8532-61a963f2b666
=> fix: Add fetch assets from route action to Going back router action

webapp/src/modules/favorites/actions.spec.ts, webapp/src/modules/favorites/actions.ts, webapp/src/modules/favorites/reducer.spec.ts, webapp/src/modules/favorites/reducer.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/modules/favorites/selectors.spec.ts, webapp/src/modules/favorites/selectors.ts, webapp/src/modules/vendor/decentraland/favorites/api.spec.ts, webapp/src/modules/vendor/decentraland/favorites/api.ts
=> feat: Get List sagas

webapp/src/components/AssetCard/AssetCard.css, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/AssetCard/utils.tsx, webapp/src/components/AssetImage/AvailableForMintPopup.tsx, webapp/src/components/AssetPage/BestBuyingOption/BestBuyingOption.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/ListingsTable/ListingsTable.module.css, webapp/src/components/AssetPage/ListingsTable/ListingsTable.tsx, webapp/src/components/AssetPage/ListingsTable/utils.tsx, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx, webapp/src/components/AssetPage/TransactionHistory/utils.tsx, webapp/src/components/Table/TableContainer/TableContainer.css, webapp/src/components/Table/TableContent/TableContent.css, webapp/src/components/Table/TableContent/TableContent.tsx
=> feat: add mobile styles for the new item detail page

webapp/src/components/AssetPage/BuyNFTBox/BuyNFTBox.tsx
=> fix: added not for sale case

webapp/src/components/AssetCard/AssetCard.css, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/AssetImage/AssetImage.css, webapp/src/components/AssetPage/Description/Description.module.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.module.css
Fix several UI bugs in mobile and updates some logic changed by the product team
=> fix: catalog styles for mobile

webapp/package-lock.json, webapp/package.json, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx, webapp/src/components/BuyPage/MintItemModal/MintItemModal.tsx, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Bump decentraland dapps version that includes the logic to move translation to each dapp to customize AuthorizationModal texts
=> fix: bump decentraland dapps

webapp/src/components/AuthorizationModal/AuthorizationModal.container.ts, webapp/src/components/AuthorizationModal/AuthorizationModal.css, webapp/src/components/AuthorizationModal/AuthorizationModal.tsx, webapp/src/components/AuthorizationModal/AuthorizationModal.types.ts, webapp/src/components/AuthorizationModal/index.ts, webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/components/SellPage/SellModal/SellModal.types.ts, webapp/src/components/SellPage/SellPage.container.ts, webapp/src/components/SellPage/SellPage.tsx, webapp/src/components/SellPage/SellPage.types.ts, webapp/src/modules/order/selectors.spec.ts, webapp/src/modules/order/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Reverts decentraland/marketplace#1753
Revert as its failing when selling names
=> Revert "feat: add authorization modal to sell action"

webapp/src/components/Navigation/Navigation.css
https://github.com/decentraland/marketplace/assets/32873485/a4792c21-9acf-457b-9180-8fab4e9c96dd
=> feat: added animation to pride tab

webapp/src/components/AssetCard/utils.tsx
=> fix: mint is in range card bug

webapp/src/components/AssetProvider/AssetProvider.tsx, webapp/src/components/SuccessPage/SuccessPage.container.ts, webapp/src/components/SuccessPage/SuccessPage.spec.tsx, webapp/src/components/SuccessPage/SuccessPage.tsx, webapp/src/components/SuccessPage/SuccessPage.types.ts, webapp/src/components/SuccessPage/utils.ts
Change issuedId for tokenId as in some cases the values are not the same
=> fix: change issued id for tokenId

webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
=> fix: Use the length of the item ids set as the "first" qs in the catalog request

webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Show notification after successfully updating a list

webapp/src/components/ListsPage/ListsPage.module.css, webapp/src/components/ListsPage/ListsPage.tsx
=> fix: fixed dropdown styles

webapp/src/components/ListPage/ListPage.container.ts, webapp/src/components/ListPage/ListPage.spec.tsx, webapp/src/components/ListPage/ListPage.tsx, webapp/src/components/ListPage/ListPage.types.ts, webapp/src/components/Routes/Routes.tsx, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
Merge after releasing https://github.com/decentraland/marketplace-favorites-server/pull/170
Closes #1793 
Closes #1792 
There is a visual bug when signing out because of a re-rendering.
https://www.loom.com/share/b8e3bc2dbb414c939e655f9abf6da1b4?sid=e745f041-71c1-4a5b-89cd-ee4ca94d8766
=> fix: Unprotect list detail page

webapp/src/components/AssetImage/AssetImage.css, webapp/src/components/AssetPage/EmoteDetail/EmoteDetail.module.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.module.css
=> fix: styles on list card mobile

webapp/src/components/ListPage/ListPage.tsx, webapp/src/components/Modals/ShareListModal/ShareListModal.spec.tsx, webapp/src/components/Modals/ShareListModal/ShareListModal.tsx, webapp/src/modules/analytics/track.ts, webapp/src/utils/events.ts
=> feat: Add tracking for lists v1

webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditListModal.module.css, webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditListModal.tsx
=> fix: create list modal button styles

webapp/src/components/InfoTooltip/InfoTooltip.tsx, webapp/src/components/InfoTooltip/InfoTooltip.types.ts, webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditListModal.module.css, webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditListModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: Show tooltip next to the private checkbox

webapp/src/components/SuccessPage/SuccessPage.spec.tsx
=> fix: success page test

webapp/src/components/Modals/SaveToListModal/SaveToListModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> fix: Use the 'Save changes' label for multiple edits

webapp/src/components/ListsPage/ListsPage.module.css, webapp/src/components/ListsPage/ListsPage.tsx
=> fix: Avoid repeating cards keys + avoid getting lists outside the card group

webapp/src/modules/favorites/reducer.spec.ts, webapp/src/modules/favorites/reducer.ts
=> fix: Removing last item from list

webapp/src/components/ListsPage/ListCard/ListCard.spec.tsx, webapp/src/components/ListsPage/ListCard/ListCard.tsx, webapp/src/components/ListsPage/ListCard/ListCard.types.ts, webapp/src/components/ListsPage/ListsPage.tsx, webapp/src/components/Modals/ShareListModal/ShareListModal.tsx
=> fix: make cards enable actions

webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditList.spec.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> chore: Change private checkbox wording

webapp/src/components/Modals/ShareListModal/ShareListModal.tsx
=> fix: Blur after opening the new tab to share on twitter

webapp/src/components/ListsPage/ListCard/ListCard.module.css
=> fix: Change the fixed height of the AssetImage inside the ListCards

webapp/src/components/ListsPage/ListsPage.module.css, webapp/src/components/ListsPage/ListsPage.tsx, webapp/src/components/PageLayout/PageLayout.module.css, webapp/src/components/PageLayout/PageLayout.tsx
=> fix: Remove padding from the page layout css

webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
=> fix: Redirect to list after creating one

webapp/src/components/AssetBrowse/AssetBrowse.tsx
=> fix: made fetch assets from route in asset browse when going back into a list

webapp/src/components/ListPage/ListPage.module.css, webapp/src/components/ListPage/ListPage.tsx
=> fix: List description too long breaking styles

webapp/src/modules/favorites/actions.spec.ts, webapp/src/modules/favorites/actions.ts, webapp/src/modules/favorites/reducer.spec.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/modules/item/reducer.spec.ts, webapp/src/modules/item/reducer.ts, webapp/src/modules/vendor/decentraland/favorites/types.ts
Closes #1893 
Merge https://github.com/decentraland/marketplace-favorites-server/pull/186 first
=> fix: Fetch preview items also in the Get List sagas

webapp/src/components/Modals/ShareListModal/ShareListModal.spec.tsx, webapp/src/components/Modals/ShareListModal/ShareListModal.tsx
=> fix: Use a timer of 300 ms before opening twitter avoiding segment callback

webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditListModal.container.ts, webapp/src/components/Modals/CreateOrEditListModal/CreateOrEditListModal.types.ts, webapp/src/components/Modals/SaveToListModal/SaveToListModal.container.ts, webapp/src/components/Modals/SaveToListModal/SaveToListModal.tsx, webapp/src/components/Modals/SaveToListModal/SaveToListModal.types.ts
=> feat: make create list modal adaptable when opening it inside save list modal

webapp/package-lock.json, webapp/src/modules/analytics/track.ts, webapp/src/utils/category.ts
Add category info to buy nft event
Closes #1899
=> feat: add category to buy event

webapp/src/lib/asset.spec.ts, webapp/src/lib/asset.ts
This PR fetches the SW permissions from the content client.
=> feat: Fetch SW Permissions

webapp/src/config/env/dev.json
This shouldn't be merged until the whole migration is done
=> feat: replace goerli with sepolia

webapp/src/components/AssetPage/BuyNFTBox/BuyNFTBox.tsx, webapp/src/components/AssetPage/EmoteDetail/EmoteDetail.tsx, webapp/src/components/AssetPage/ListingsTable/ListingsTable.tsx, webapp/src/components/AssetPage/ListingsTableContainer/ListingsTableContainer.tsx, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx
=> fix: remove warning

webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.module.css
=> fix: Resize required permission chip text

webapp/src/modules/routing/sagas.ts
Fixes a race-condition given by an extra Items fetch by `creator` which is unnecesary
=> feat: fix modal fetching items by creator along the nfts on sale

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx
This PR fixes an issue that's causing the `AssetCard` component to collide with the CSS that comes from the `AssetCard` component in the UI.
=> fix: Cards glowing issue

webapp/src/components/CollectionPage/CollectionPage.tsx
The tabs logic was missing so clicking on them was not doing anything, the emotes were not visible.
=> fix: collecitons page tabs not working

.github/workflows/build-release.yaml, webapp/package.json, webapp/scripts/prebuild.js, webapp/src/modules/analytics/sentry.ts
Based on https://www.youtube.com/watch?v=vAGHl0t9x1U&list=PLOwEowqdeNMr-cq9dH1AKvehShd6WfYxC&index=8&ab_channel=Sentry & https://github.com/marketplace/actions/sentry-release
=> feat: Add step to upload release to Sentry

webapp/src/components/AssetPage/YourOffer/YourOffer.module.css, webapp/src/components/AssetPage/YourOffer/YourOffer.tsx
This PR fixes the YourOffer component that had two problems:
- It was being shown whenever the user wasn't logged in (and it should only be shown when the user is logged in).
- It broke the mobile UI.
Before:
After:
=> fix: YourOffer breaking mobile styles

webapp/src/components/AssetCard/EmoteTags/EmoteTags.module.css, webapp/src/components/AssetCard/EmoteTags/EmoteTags.tsx
=> feat: add sound icon to card

webapp/src/components/AssetImage/AssetImage.container.ts, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetImage/AssetImage.types.ts, webapp/src/components/Modals/SmartWearableVideoShowcaseModal/SmartWearableVideoShowcaseModal.spec.tsx, webapp/src/components/Modals/SmartWearableVideoShowcaseModal/SmartWearableVideoShowcaseModal.tsx, webapp/src/components/Modals/SmartWearableVideoShowcaseModal/SmartWearableVideoShowcaseModal.types.ts, webapp/src/modules/vendor/decentraland/nft/types.ts
=> fix: Avoid showing play showcase if the SW does not have a video

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetFilters/EmoteAttributesFilter/EmoteAttributesFilter.spec.tsx, webapp/src/components/AssetFilters/EmoteAttributesFilter/EmoteAttributesFilter.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.container.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.types.ts, webapp/src/components/AssetPage/IconBadge/IconBadge.css, webapp/src/components/AssetTopbar/SelectedFilters/SelectedFilters.tsx, webapp/src/modules/vendor/decentraland/nft/api.ts, webapp/src/modules/vendor/decentraland/nft/types.ts
=> feat: add logic for emotes 2.0 for prices endpoint

webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts
=> fix: wait for identity success action before fetching catalog (#1974)

webapp/src/components/AssetTopbar/AssetTopbar.tsx
Remove search dropdown on account views to use simple search
=> fix: remove search dropdown on account views

webapp/src/components/ManageAssetPage/Sell/Sell.tsx, webapp/src/components/Modals/SellModal/SellModal.tsx
Fix manage land expiration date
=> fix manage land expiration date

webapp/src/components/AssetList/AssetList.css, webapp/src/components/AssetList/AssetList.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Change empty state description for campaign tab
=> feat: change empty state for campaign

indexer/README.md, indexer/package-lock.json, indexer/package.json, indexer/src/handlers/estate.ts
Update search text when updating an estate
=> fix: estate update change searchText

webapp/src/config/env/dev.json, webapp/src/config/env/stg.json, webapp/src/modules/store.ts
Set basepath depending on host
=> fix: basepath for subdomains

webapp/src/modules/analytics/track.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/transaction/utils.ts, webapp/src/utils/events.ts
This PR adds track event for the rejection of a cross-chain purchase
=> feat: track if user rejects tx in cross chain operation

webapp/package-lock.json, webapp/package.json
Update decentraland ui dependency
=> feat: update decentraland UI

webapp/src/components/AssetTopbar/AssetTopbar.tsx
=> fix: clear the search after empty result

.github/workflows/build-release.yaml, webapp/package.json
This PR updates the Marketplace's build process to Node 18.
=> fix: Update build process to node 18

webapp/src/components/NamesPage/ClaimNamePage/ClaimNamePage.module.css, webapp/src/components/NamesPage/ClaimNamePage/ClaimNamePage.tsx
=> feat: hide builder redirect and add gradient effect

webapp/package-lock.json, webapp/package.json
This PR fixes navbar2 notifications locale error
=> fix: Upgrade navbar2 notifications locale

webapp/README.md
This PR is to rerun the build and publish job
=> fix: Rerun publish job

webapp/package-lock.json, webapp/package.json
This PR overrides some `@walletconnect` dependencies
=> fix: Wallet connect dependencies version

webapp/src/components/HomePage/Slideshow/Slideshow.css
=> fix: slideshow bug on wide screens

.github/workflows/audit.yml, webapp/package-lock.json, webapp/package.json, webapp/vite.config.ts
This PR removes the need to use the dev server using HTTPS.
=> fix: Remove HTTPS from local server

webapp/package-lock.json, webapp/package.json, webapp/src/components/TransferPage/TransferPage.container.ts, webapp/src/components/TransferPage/TransferPage.css, webapp/src/components/TransferPage/TransferPage.tsx, webapp/src/components/TransferPage/TransferPage.types.ts, webapp/src/modules/features/selectors.spec.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts
Add AddressField to asset transfer page
=> feat: add AddressField for transfer

webapp/package-lock.json, webapp/package.json
Update decentraland dapps to latest version
=> feat: update decentraland dapps

webapp/src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.css, webapp/src/components/SuccessPage/SuccessPage.tsx
=> feat: add styles for the claim name modal in mobile

webapp/src/components/HomePage/HomePage.tsx
=> fix: add correct parameters to homepage newest items view all

webapp/src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.css, webapp/src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.tsx
=> fix: align fat finger header to the left

webapp/src/modules/features/selectors.spec.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts
=> fix: Add feature flag

webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/nft/sagas.spec.ts, webapp/src/modules/nft/sagas.ts
This PR avoids executing the `fetchSmartWearableRequiredPermissionsRequest` action when it is not required.
=> fix: Fetch smart-wearables permissions

webapp/package-lock.json, webapp/package.json, webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.types.ts, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.spec.tsx, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: add logic to show cross chain tx link in activity and success toast

webapp/src/components/AssetPage/SaleActionBox/BuyNFTButtons/BuyNFTButtons.tsx, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.container.ts, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.types.ts, webapp/src/components/Atlas/Popup/Popup.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyNftWithCryptoModal/BuyNftWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyNftWithCryptoModal/BuyNftWithCryptoModal.types.ts, webapp/src/components/Modals/BuyWithCryptoModal/PaymentSelector/PaymentSelector.tsx, webapp/src/components/Modals/BuyWithCryptoModal/hooks.ts, webapp/src/components/SuccessPage/SuccessPage.tsx, webapp/src/modules/analytics/track.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
(note: buy now button hardcoded, it should render the BUY MANA one since I don't have enough balance)
=> feat: Add cross chain payments for LANDs

webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> fix: adapt wording to not show buy with card if its not available

.github/workflows/lint.yaml, webapp/.eslintrc.cjs, webapp/package.json, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/components/NamesPage/ClaimNamePage/ClaimNamePage.tsx, webapp/src/components/OnSaleOrRentList/AssetCell/AssetCell.tsx, webapp/src/components/RankingsTable/RankingsTable.tsx, webapp/src/lib/timer.spec.ts, webapp/src/modules/analytics/reducer.ts, webapp/src/modules/collection/reducer.ts, webapp/src/modules/event/reducer.ts, webapp/src/modules/favorites/reducer.ts, webapp/src/modules/identity/sagas.ts, webapp/src/modules/nft/hooks.spec.tsx, webapp/src/modules/routing/sagas.ts, webapp/src/modules/sale/reducer.ts, webapp/src/modules/store/reducer.ts, webapp/src/modules/ui/browse/reducer.ts, webapp/src/modules/vendor/services.ts
This PR fixes some non-automatic linting rules and changes the script command used in the CI so it also lints tsx files.
=> fix: Linting rules one (no-empty, no-yield, no-case-declarations and no-unused-vars)

webapp/.eslintrc.cjs, webapp/src/components/AssetProvider/AssetProvider.container.ts, webapp/src/components/AssetProvider/AssetProvider.tsx, webapp/src/components/Menu/DropdownMenu/DropdownMenu.tsx, webapp/src/components/Menu/DropdownMenu/DropdownMenu.types.ts, webapp/src/components/Menu/MenuItem/MenuItem.tsx, webapp/src/components/Menu/MenuItem/MenuItem.types.ts, webapp/src/components/Modals/BuyWithCryptoModal/PaymentSelector/PaymentSelector.tsx, webapp/src/components/Modals/FavoritesModal/FavoritesModal.spec.tsx, webapp/src/components/RankingsTable/RankingsTable.tsx, webapp/src/lib/pagination.ts, webapp/src/modules/bid/sagas.spec.ts, webapp/src/modules/bid/sagas.ts, webapp/src/modules/contract/sagas.ts, webapp/src/modules/nft/sagas.spec.ts, webapp/src/modules/nft/sagas.ts, webapp/src/modules/routing/locations.ts, webapp/src/modules/store.ts, webapp/src/modules/store/utils.ts, webapp/src/modules/vendor/VendorFactory.ts, webapp/src/modules/vendor/decentraland/nft/api.ts, webapp/src/modules/vendor/decentraland/nft/authApi.ts, webapp/src/modules/vendor/decentraland/rentals/api.ts, webapp/src/modules/vendor/utils.ts, webapp/src/utils/output.ts
This PR fixes the following rules:
- unbound-method
- no-base-to-string
- restrict-template-expressions
- no-non-null-asserted-optional-chain
=> fix: Linting fixes (unbound-method, no-base-to-string, ...)

webapp/.eslintrc.cjs, webapp/src/components/AccountSidebar/AccountSidebar.types.ts, webapp/src/components/AccountSidebar/OtherAccountSidebar/OtherAccountSidebar.types.tsx, webapp/src/components/AssetFilters/PriceFilter/utils.ts, webapp/src/components/AssetFilters/StatusFilter/StatusFilter.tsx, webapp/src/components/AssetImage/AssetImage.types.ts, webapp/src/components/AssetImage/AvailableForMintPopup.tsx, webapp/src/components/AssetTopbar/SelectedFilters/SelectedFilters.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/components/SuccessPage/SuccessPage.tsx, webapp/src/modules/nft/utils.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/store/utils.ts, webapp/src/modules/ui/sagas.ts, webapp/src/modules/vendor/utils.ts, webapp/src/utils/enums.spec.ts, webapp/src/utils/enums.ts
This PR enables two new linting rules:
- no-non-null-assertion
- no-unsafe-enum-comparisson
=> fix: Linting rules (no-non-null-assertion and no-unsafe-enum-comparisson)

webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: update cross-chain wording

webapp/src/components/CollectionPage/utils.tsx
This PR fixes an issue where the minting and edit price weren't outputed correctly.
=> fix: Minting URL

.github/workflows/audit.yml, .github/workflows/build-release.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, webapp/package-lock.json, webapp/package.json
This PR updates the build process to use node 20.
=> fix: Update build process to node 20

webapp/src/components/AssetPage/AssetPage.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.types.ts, webapp/src/components/AssetPage/WearableDetail/WearableDetail.module.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/components/AssetProvider/AssetProvider.tsx, webapp/src/components/AssetProvider/AssetProvider.types.ts, webapp/src/components/AssetProviderPage/AssetProviderPage.tsx, webapp/src/components/AssetProviderPage/AssetProviderPage.types.ts, webapp/src/modules/asset/types.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/reducer.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/item/types.ts, webapp/src/modules/nft/sagas.spec.ts, webapp/src/modules/nft/sagas.ts, webapp/src/modules/nft/types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/vendor/decentraland/peer/api.ts
Show VRM export block icon on wearables
=> feat: add vrm block badge

webapp/src/components/RankingsTable/RankingsTable.container.ts, webapp/src/components/RankingsTable/RankingsTable.tsx, webapp/src/components/RankingsTable/RankingsTable.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts
This PR removes the exotic rarity feature flag which is no longer used.
=> fix: Remove exotic rarity FF

webapp/src/components/AccountPage/AccountPage.tsx, webapp/src/components/ActivityPage/ActivityPage.tsx, webapp/src/components/AssetPage/AssetPage.tsx, webapp/src/components/BidPage/BidPage.tsx, webapp/src/components/BrowsePage/BrowsePage.tsx, webapp/src/components/BuyPage/StatusPage/StatusPage.tsx, webapp/src/components/Campaign/CampaignBrowserPage/CampaignBrowserPage.tsx, webapp/src/components/CancelSalePage/CancelSalePage.tsx, webapp/src/components/CollectionPage/CollectionPage.tsx, webapp/src/components/HomePage/HomePage.tsx, webapp/src/components/LandsPage/LandsPage.tsx, webapp/src/components/LandsPage/LandsPage.types.ts, webapp/src/components/LegacyNFTPage/LegacyNFTPage.tsx, webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/PageLayout/PageLayout.tsx, webapp/src/components/PageLayout/PageLayout.types.ts, webapp/src/components/Routes/Routes.tsx, webapp/src/components/SellPage/SellPage.tsx, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/components/SignInPage/SignInPage.tsx, webapp/src/components/SuccessPage/SuccessPage.tsx, webapp/src/components/TransferPage/TransferPage.tsx
=> feat: use PageLayout in all pages

webapp/package-lock.json, webapp/package.json, webapp/src/components/AssetPage/EmoteDetail/EmoteDetail.module.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.module.css
This PR updates the decentraland-ui dependency to change the utility icon.
=> fix: Update the utility icon

webapp/src/components/AccountPage/AccountBanner/AccountBanner.css, webapp/src/components/AccountPage/AccountBanner/AccountBanner.tsx
This PR links the profile from the user's market.
=> feat: Link profile from market

webapp/src/components/Bid/AcceptButton/AcceptButton.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/wallet/utils.ts
Fix address coming as null in `addressEquals` helpers. Do not allow to accept a trade when there is no more available stock
=> fix: address null

webapp/src/components/Bid/AcceptButton/AcceptButton.tsx, webapp/src/components/Bid/Bid.css, webapp/src/components/Bid/Bid.tsx, webapp/src/components/Bids/Bids.css, webapp/src/modules/bid/sagas.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
fix toast position when placing a bid and add created date to bids list
=> fix: bid placed toast position

webapp/package-lock.json, webapp/package.json, webapp/src/lib/asset.ts
Fix version of catalyst client as the newest version use nodejs crypto library and there is still no polyfill available
=> fix: catalyst client version

indexer/.prettierrc, indexer/.subgraph.yaml, indexer/src/modules/analytics/index.ts
Apply the same patch from here onto the marketplace subgraph: https://github.com/decentraland/collections-graph/pull/109
=> fix: set correct buyer for sales done by thid parties

webapp/src/components/AssetFilters/PriceFilter/PriceFilter.container.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.types.ts
Call marketplace server prices endpoint when offchain items are nfts are enabled
=> feat: change prices endpoint to the marketplacE

webapp/src/components/ManageAssetPage/Sell/Sell.container.ts, webapp/src/components/Modals/SellModal/SellModal.container.ts, webapp/src/components/Modals/SellModal/SellModal.tsx, webapp/src/modules/order/sagas.ts, webapp/src/modules/translation/locales/en.json
=> feat: add cancel listing step to LANDs flow

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css
=> fix: fix UI bug in rent and sale box

webapp/src/modules/analytics/sagas.spec.ts, webapp/src/modules/analytics/sagas.ts, webapp/src/modules/vendor/VendorFactory.ts, webapp/src/modules/vendor/decentraland/AnalyticsService.ts, webapp/src/modules/vendor/decentraland/analytics/api.ts, webapp/src/modules/vendor/decentraland/rankings/api.ts, webapp/src/modules/vendor/services.ts
This PR changes the selection of the URL that is used in the analytics and the rankings clients via feature flag.
=> fix: Select via FF the URL where to grab the analytics or the rankings

webapp/package-lock.json, webapp/package.json
Upgrade `decentraland-ui` to have the new Navbar with extra button configurable via Contentful:
=> chore: upgrade navbar

webapp/src/modules/bid/utils.ts
This PR fixes the authorizeOptions for the bids actions
=> fix: AuthorizeActionOptions for bids

webapp/package-lock.json, webapp/package.json, webapp/src/components/Routes/Routes.tsx
This PR updates the intercom component used to a new one with data augmented to have a better knowledge of the users reporting an error, improving the support team flow
=> feat: Update intercom component

webapp/src/modules/transak/sagas.ts
This PR changes the calldata building process to the correct one.
=> fix: Buying NFT orders with transak

webapp/src/components/SettingsPage/Authorization/Authorization.container.ts, webapp/src/components/SettingsPage/Authorization/Authorization.tsx, webapp/src/components/SettingsPage/Authorization/Authorization.types.ts, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/modules/contract/sagas.spec.ts, webapp/src/modules/contract/sagas.ts, webapp/src/modules/vendor/decentraland/contracts.ts
=> feat: add CreditsManager authorization in settings page

webapp/src/components/AssetFilters/AssetFilters.container.ts, webapp/src/components/AssetFilters/AssetFilters.tsx, webapp/src/components/AssetFilters/AssetFilters.types.ts, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.container.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.css, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.tsx, webapp/src/components/AssetFilters/PriceFilter/PriceFilter.types.ts, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/SaleActionBox/BuyNFTButtons/BuyNFTButtons.tsx, webapp/src/components/AssetPage/SaleActionBox/BuyNFTButtons/BuyWithCryptoButton/BuyWithCryptoButton.tsx, webapp/src/components/AssetPage/SaleActionBox/BuyNFTButtons/BuyWithCryptoButton/BuyWithCryptoButton.types.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/routing/types.ts, webapp/src/modules/routing/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: introduce the With Credits filter in the PriceComponent

webapp/src/components/AssetImage/Preview/Preview.tsx, webapp/src/config/env/dev.json, webapp/src/config/env/prod.json, webapp/src/config/env/stg.json
This PR fixes the Wearable Preview URL in the config files
=> fix: Wearable Preview URL

webapp/src/components/AssetImage/Preview/Preview.tsx
This PR fixes the WearablePreview babylon props
=> fix: Wearable Preview Babylon type

webapp/src/modules/contract/sagas.ts
This PR correctly initiates the credits contract which was failing due to it using the wallet chain id, which usually is the mainnet one and, as credits does not exist in mainnet, it ends up failing.
=> fix: Credits contract not being initiated correctly
