decentraland/marketplace

webapp/src/components/TransferPage/TransferPage.css, webapp/src/components/TransferPage/TransferPage.tsx
Shows the errors in `--danger` color, also fixes a bug where the transfer button was enabled even when the input was empty or when you were not the owner of the asset
=> fix: enable transfer button only when allowed

webapp/package-lock.json, webapp/package.json, webapp/src/components/NFTListPage/ArrayFilter/ArrayFilter.tsx, webapp/src/modules/nft/actions.ts, webapp/src/modules/nft/sagas.ts, webapp/src/modules/ui/reducer.ts
This PR adds a check in the `ui/reducer` to ignore old `FETCH_NFTS_SUCCESS` actions. Also updates decentraland libraries and removes a warning.
=> fix: ignore old fetch requests

webapp/src/components/NFTListPage/NFTListPage.tsx
=> fix: hide sort dropdown on mobile

.gitlab-ci.yml
This PR changes the `npm install` command for a `npm ci`, preventing any minor versions from breaking the CI procedure.
=> fix: Do a CI install instead of a plain one

.gitlab-ci.yml
This PR replaces the `npm install` command used to install and build the webapp with `npm ci`
=> fix: Replace webapp installation script with npm ci

webapp/src/components/NFTPage/EstateDetail/EstateDetail.tsx, webapp/src/components/NFTPage/EstateDetail/ParcelCoordinates/ParcelCoordinates.container.ts, webapp/src/components/NFTPage/EstateDetail/ParcelCoordinates/ParcelCoordinates.tsx, webapp/src/components/NFTPage/EstateDetail/ParcelCoordinates/ParcelCoordinates.types.ts, webapp/src/components/NFTPage/EstateDetail/ParcelCoordinates/index.ts
This PR fixes the issue of receiving a lower amount of parcels for a estate because of limitations in the API by loading the parcels from the pre-loaded tiles.
Closes #360
=> fix: Show all parcels in estate using tiles

webapp/src/components/Navigation/Navigation.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR renames the `Decentraland` tab to "Collectibles".
Closes #328
=> chore: Rename "Decentraland" tab to collectibles

webapp/src/components/Vendor/PriceChangeNotice/PriceChangeNotice.css
This PR fixes the overlapping of two components, the `PriceChangeNotice` and the `NFTList`.
This was due to a difference on how the CSS is loaded between development and production.
Closes #374
=> fix: Overlapping PriceChangeNotice component

webapp/src/components/NFTBrowse/NFTBrowse.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds a missing filter on mobile to change the type of the item.
The dropdown labels were changed to fit the mobile screens.
=> fix: Add missing item filter

indexer/README.md, indexer/package.json
I replaced the `deploy` command with `deploy:ropsten` and `deploy:mainnet`, which performs a build prior to deploying, to prevent deploying the wrong network to a subgraph.
=> feat: prevent deploying wrong network

webapp/src/modules/vendor/decentraland/NFTService.spec.ts, webapp/src/modules/vendor/decentraland/NFTService.ts
- Adds tests for the NFT Service.
- Rewrites the fetch method, fixing a bug where the accounts were not computed correctly.
=> chore: Add NFT Service tests

webapp/src/modules/vendor/decentraland/NFTService.spec.ts, webapp/src/modules/vendor/decentraland/NFTService.ts
We were using an ABI from the files generated by web3x which at some point changed from being a plain ABI to be a class, which made the transfer stopped working. Now it's using the ERC721 contract data from `decentraland-transactions`. I also used that one for collections on polygon since the `transferFrom` method is the same for those too.
=> fix: use ERC721 from decentraland-transaction for all transfers

webapp/src/components/OnSaleList/OnSaleList.tsx
This is to avoid possible duplications between the nft id and the item id.
=> fix: Add prefix to key depending if nft or item

.gitignore, .vscode/settings.json, webapp/.vscode/settings.json, webapp/src/components/AssetPage/AssetPage.tsx, webapp/src/components/AssetPage/ErrorBoundary/ErrorBoundary.tsx, webapp/src/components/AssetPage/ErrorBoundary/ErrorBoundary.types.ts, webapp/src/components/AssetPage/ErrorBoundary/index.ts, webapp/src/components/AssetPage/EstateDetail/EstateDetail.css, webapp/src/components/AssetPage/EstateDetail/EstateDetail.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds an [Error Boundary](https://reactjs.org/docs/error-boundaries.html) component to catch unexpected errors in item/nft details that could be caused by rejected items, or race conditions between items and collections in the estate (ie, a collections is approved after I open the marketplace, so it's not loaded in memory, but the items are already available in the browse section).
I also fixed the EstateDetail when an estate has been dissolved (it used to blow up because it was using `estate.parcel[0]` which was undefined), and I modified the header on those estates to show notice that the estate has been dissolved, otherwise the map ends up centered on the genesis plaza:
=> feat: error boundary

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetPage/ENSDetail/ENSDetail.tsx, webapp/src/components/AssetPage/EstateDetail/EstateDetail.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/ParcelDetail/ParcelDetail.tsx, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.css, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.types.ts, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/components/Navigation/Navigation.tsx, webapp/src/components/OnSaleList/AssetCell/AssetCell.tsx, webapp/src/components/OnSaleList/OnSaleList.tsx, webapp/src/components/OnSaleList/OnSaleListElement/OnSaleListElement.css, webapp/src/components/OnSaleList/OnSaleListElement/OnSaleListElement.tsx, webapp/src/components/Sales/Activity/Activity.css, webapp/src/components/Sales/Activity/Activity.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #504
This PR:
- Fixes the responsiveness of the `Sales` and `On Sale` sections of `My Store`. 
- Since the `CurrentAccountSidebar` was completely removed on mobile, it was not possible to navigate the `My Store` page, so I added some `Tabs` to allow navigation on this view on mobile.
- Added the sale `type` to the sales information in `Sales`, `On Sale`, and `TransactionHistory`.
- I also took the chance to get rid of the deprecated `Responsive` component and replace it with `Mobile` and `NotMobile`. 
- Finally, I modified the `TransactionHistory` component to use the new `/sales` API, added pagination to it, and made it so it support both `NFT` and `Item`, so I added it to the `ItemDetail` as well:
My Store responsive tables:
ItemDetail with latest sales:
=> fix: user stores responsiveness + transation history

webapp/src/components/AccountPage/AccountPage.tsx
Checks if the address is valid using [ether.js utils method](https://docs.ethers.io/v5/api/utils/address/#utils-isAddress) `isAddress`, redirecting to the root page in case it returns `false`.
https://user-images.githubusercontent.com/8763687/149975358-3c599526-574e-474f-98b2-d753d98dad38.mov
=> fix: Redirect to root page if address is not valid

webapp/src/components/AssetPage/BaseDetail/BaseDetail.css
On mobile, the badge was not the same distance from the top than from the right because of some old media query, removed it so it is placed accordingly.
This
Instead of
=> fix: Listed badge style on detail

webapp/src/modules/store/sagas.ts
Closes #573 
This was due to the `takeLatest` effect being used to handle the action. As two fetches are being dispatched, only the latest is considered so 2 REQUESTS are in the loading store but only one is removed at the end because only one SUCCESS or FAILURE is called.
Happened arbitrarily, not only when the user was not connected.
=> fix: Profiles not loading

package-lock.json, webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/routing/utils.ts
In order to perform this task, we took out three saga (buildBrowseURL, getCurrentBrowseOptions, getAddress) and put them in utils (buildBrowseURL) and the rest in selectors. 
As part of the process we created selectors that group other selectors, mainly the ones that get parameters from the url (getPaginationUrlParams, getAssetsUrlParams, getLandsUrlParams, getWearablesUrlParams), so we can use them in the getCurrentBrowseOptions selector.
Once this process was finished, the sagas that use these new selectors were updated.
Then we added in the AssetList.container.ts file the urlNext property to send the url to use in the href of the anchor tag.
=> feat: change button for link in pagination

webapp/src/components/ConfirmInputValueModal/ConfirmInputValueModal.tsx, webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/components/SellPage/SellModal/utils.spec.ts, webapp/src/components/SellPage/SellModal/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR makes 2 improvements to the confirmation modal:
1) Remove the trailing zeros from the confirmed value. Since the input to set the price allows for up to two decimals, a user could enter a value like "1.00":
And the confirmation modal would show the parsed number in the text, but the raw value in the confirmation, like this:
Making the user have to type "1.00" to continue. This PR changes that so the value is parsed and trailling zeros are removed: 
2) For land listings (parcels and estates) with a value of 100 or less, a warning is shown. We've had cases of users who though for some reason that the input was in thousands, so they thought a value like "5" meant "5k" so they went through all the way even the confirmation modal. With this, at least they will get a warning:
=> feat: improve confirmation modal

webapp/src/modules/proximity/sagas.ts
This was broken after switching deployments to rollouts
=> fix: use PUBLIC_URL so json can be fetched from CDN once it is deployed

webapp/src/components/BuyPage/BuyPage.tsx
This PR disables the buy button and shows the error message when the user doesn't have enough mana.
Closes: #578
=> fix: Disable the buy button when the user doesn't have enough mana for an order or an asset

webapp/src/components/AssetPage/ParcelDetail/ParcelDetail.tsx
This PR fixes an issue where the `ParcelDetail` view was broken due to it being unable to load the rentals contract for the ethereum mainnet.
=> fix: Parcel details is broken without rental contract

webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts
This PR adds tests for the browse sagas when setting the `onlyOnRent` or `onlyOnSell` filters.
=> fix: Add browse tests

webapp/src/components/AssetProviderPage/AssetProviderPage.tsx, webapp/src/components/AssetProviderPage/AssetProviderPage.types.ts, webapp/src/components/Bid/Bid.tsx
This PR fixes the some issues related to how the parameters are passed to the `AssetProvider` children once it gets rendered. After adding the `rental` property, the arguments changed positions, breaking some components.
=> fix: Asset provider parameters not being used correctly

webapp/src/components/AssetImage/AssetImage.container.ts, webapp/src/components/AssetImage/AssetImage.css, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetImage/AssetImage.types.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/src/modules/ui/preview/actions.ts, webapp/src/modules/ui/preview/reducer.spec.ts, webapp/src/modules/ui/preview/reducer.ts, webapp/src/modules/ui/preview/selectors.ts, webapp/src/modules/ui/sagas.ts
This PR adds zoom in/out and play/stop controls to emotes on the try-on screen.
https://user-images.githubusercontent.com/3170051/190712374-f24b58f3-7bf4-44b4-8103-b01ea004d6b9.mov
Closes #736
=> feat: Add emote controls in the try-on screen

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.tsx, webapp/src/components/Vendor/NFTFilters/FiltersMenu/FiltersMenu.types.ts, webapp/src/components/Vendor/NFTFilters/NFTFilters.tsx, webapp/src/components/Vendor/NFTFilters/NFTFilters.types.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.types.ts, webapp/src/modules/routing/sagas.ts
This PR shows the collections that contain items with the event `MVMF22` tag
=> feat: Use MVMF collections in the mvmf event page

webapp/src/components/AssetImage/AssetImage.css
This PR centers the icons of the zoom buttons in the emote preview, and also makes the corners round as the rest of the buttons.
Before:
After:
=> fix: zoom button style

webapp/src/components/HomePage/HomePage.css, webapp/src/components/HomePage/HomePage.tsx, webapp/src/components/HomePage/Slideshow/ItemsSection.tsx, webapp/src/components/HomePage/Slideshow/Slideshow.css, webapp/src/components/HomePage/Slideshow/Slideshow.tsx, webapp/src/components/HomePage/Slideshow/Slideshow.types.ts
This PR adds the wearables and emotes tabs for the newest and listing sliders on the homepage.
Newest Slider:
- Desktop: 
- Mobile:
Listing Slider:
- Desktop: 
- Mobile: 
Closes #852
=> feat: Add wearables and emotes tabs for newest and listing sliders on homepage

webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts, webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds toasts to the following rental actions:
- Claiming back a land
- Updating or creating a new rental listing
- Removing a rental listing
It also moves the upsert toast into the toasts file.
Closes #831
=> feat: Add rental toasts

webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/modules/wallet/sagas.ts
The error was introduced recently, when a change was added to filter the authorizations that were already in the array. It included a condition to check whether they were wearables/emotes so it was leaving the LANDs/Estates out. This PRs adds them back.
=> fix: Add the LAND authorizations to array

webapp/src/components/Vendor/NFTFilters/NFTFilters.css, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.container.ts, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.types.ts
This PR fixes the following:
- The LAND filters appearing in collectibles.
- The on sale toggle being uncentered.
Before:
After:
=> fix: LAND filters in collectibles

webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx
This PR fixes the `TransactionHistory` component total pages computing.
Closes #935
=> fix: TransactionHistory pagination

webapp/src/components/HomePage/HomePage.tsx, webapp/src/components/HomePage/Slideshow/Slideshow.css, webapp/src/components/HomePage/Slideshow/Slideshow.tsx, webapp/src/components/HomePage/Slideshow/Slideshow.types.ts, webapp/src/components/RankingsTable/RankingsTable.container.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #742 
For Trending Wearables:
For the rest of the sections (the message is configurable):
=> feat: Render empty state component in home page section slideshows

webapp/src/components/AssetProviderPage/AssetProviderPage.tsx, webapp/src/components/ManageAssetPage/Details/Details.tsx, webapp/src/components/ManageAssetPage/Details/Details.types.ts, webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/modules/vendor/utils.ts
Closes #970
Closes #964
- Parcel details: `/v1/nfts?contractAddress=0x25b6b4bac4adb582a0abd475439da6730777fbf7&tokenId=115792089237316195423570985008687907841019819456486779354776098140369474027560&rentalStatus[]=executed&rentalStatus[]=open&rentalStatus[]=cancelled`
- Manage Aset page: `/v1/nfts?contractAddress=0x25b6b4bac4adb582a0abd475439da6730777fbf7&tokenId=115792089237316195423570985008687907841019819456486779354776098140369474027560&rentalStatus[]=executed&rentalStatus[]=open&rentalStatus[]=cancelled`
- My assets
- On Rent: `/v1/nfts?first=1000&skip=0&sortBy=newest&owner=0x747c6f502272129bf1ba872a1903045b837ee86c&isOnRent=true&isLand=true&rentalStatus=open&rentalStatus=executed`
- Lands: 
```v1/nfts?first=24&skip=0&sortBy=newest&owner=0x747c6f502272129bf1ba872a1903045b837ee86c&isLan …
```
=> feat: Add rentalStatus params to nfts requests

webapp/src/components/AssetCard/AssetCard.container.ts, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.container.ts, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.types.ts, webapp/src/components/AssetProviderPage/AssetProviderPage.tsx, webapp/src/components/ManageAssetPage/ManageAssetPage.container.ts, webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/ManageAssetPage/ManageAssetPage.types.ts, webapp/src/components/ManageAssetPage/Rent/Rent.container.ts, webapp/src/components/ManageAssetPage/Rent/Rent.module.css, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/modules/asset/utils.ts
- In `AssetCard.container.ts` we weren't considering when the rental is not null. This was changed to consider it.
- Changed `ownedBy` to receive a rental in order to check for the lessor to ensure that the user is the owner of the asset.
- Fixes the owner check in the `SaleRentActionBox.tsx` so it considers the owner as the lessor.
- Blocks the `Rent` button when the asset is on rent (when a rental exists).
- Changes the `AssetProviderPage` to have a memoized version of the status array to prevent multiple requests.
- Fixes the styling between the message and the rental data in the `Rent.tsx` component.
=> fix: Various rentals fixes

webapp/src/components/CancelSalePage/CancelSalePage.container.ts, webapp/src/components/CancelSalePage/CancelSalePage.types.ts, webapp/src/components/ManageAssetPage/Sell/Sell.container.ts, webapp/src/components/ManageAssetPage/Sell/Sell.tsx, webapp/src/components/ManageAssetPage/Sell/Sell.types.ts, webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/components/SellPage/SellModal/SellModal.types.ts, webapp/src/components/SellPage/SellPage.container.ts, webapp/src/components/SellPage/SellPage.tsx, webapp/src/components/SellPage/SellPage.types.ts
This PR fixes the following:
- Adds functionality to go back when clicking on cancel on the sell or cancel order page.
- Adds an icon to cancel a sell order (the functionality was missing).
=> fix: Various sell component fixes

webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR does two things:
- Disallows using the "open in builder" button until the Land is claimed, as the builder won't show the Land you don't currently own.
- Changes the mobile hook to `useMobileMediaQuery`.
Closes #1000
=> fix: Don't open in builder if not claimed

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
This PR makes the rentals tab selected first when there are no open orders and there's a rental.
Closes #1013
=> fix: Show rentals when there are no orders

webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx
When getting for the first time into the LAND section of the Marketplace, the user has to unselect the map to go to the list view. Clicking the list button makes the user use a not available filter for `All Land`, so now whenever a user comes in for the first time, they'll load the `Available to buy` land first.
Closes #993
=> fix: View the LAND available to buy as default

webapp/src/components/ManageAssetPage/Rent/Rent.module.css, webapp/src/components/Modals/RentalListingModal/ConfirmationStep/ConfirmationStep.tsx, webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR fixes an issue where there was an error verifying the old price and re-works the way we check if the old price and the new one are the same, being as strict as possible to avoid wrongful user updates that cost gas.
Closes #1026 
Closes #1028
=> fix: Update rental price checks

webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/TransferPage/TransferPage.container.ts, webapp/src/components/TransferPage/TransferPage.tsx, webapp/src/components/TransferPage/TransferPage.types.ts
This PR disables the `Cancel` button in the Transferring and Bid pages.
=> fix: Prevent cancelling transfer or bidding

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
This PR fixes an issue which prevented users that were not logged into view the Parcel or Estate details because there was no wallet object being instantiated.
The PR also condenses all the contract gathering procedure into a `useMemo` function to perform it once.
Closes #1052
=> fix: SaleRentActionBox failing to load if not logged in

webapp/src/components/AssetProvider/AssetProvider.tsx
Closes #1050 
Right now, the `useEffect` depends on `isLoadingFeatureFlags`, which toggles between `false` and `true` on every single request (one per minute). We just need to know the first time if loads.
=> fix: add a flag to save the first loading status of the FFs

webapp/src/components/AssetPage/BaseDetail/BaseDetail.tsx, webapp/src/components/AssetPage/BaseDetail/BaseDetail.types.ts, webapp/src/components/AssetPage/EstateDetail/EstateDetail.tsx, webapp/src/components/AssetPage/ParcelDetail/ParcelDetail.tsx, webapp/src/components/AssetPage/RentalHistory/RentalHistory.tsx, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx, webapp/src/components/Bid/Bid.tsx, webapp/src/components/LinkedProfile/LinkedProfile.tsx, webapp/src/components/LinkedProfile/LinkedProfile.types.ts, webapp/src/components/LinkedProfile/index.ts, webapp/src/components/ManageAssetPage/Details/Details.tsx, webapp/src/components/ManageAssetPage/ManageAssetPage.tsx, webapp/src/components/ManageAssetPage/Rent/Rent.tsx, webapp/src/components/RankingsTable/RankingCollectorRow/RankingCollectorRow.tsx, webapp/src/components/RankingsTable/RankingCreatorRow/RankingCreatorRow.tsx, webapp/src/components/RankingsTable/RankingItemRow/RankingItemRow.tsx, webapp/src/components/RecentlySoldTable/RecentlySoldTable.tsx, webapp/src/components/Sales/Activity/Activity.tsx
This PR fixes the owner label in the `SalesAndRentBox` and adds a `LinkedProfile` component that is used all through the application.
The issue was caused because we weren't giving the rental to the BaseDetail component.
Closes #1068
=> fix: Wrong owner for rented LAND in the SalesAndRentBox

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
This PR changes the way we were comparing rental and order prices so the website doesn't crash when converting a floating point number into a big number.
=> fix: Parse current mana into wei to compare prices

webapp/src/components/AssetPage/AssetPage.tsx, webapp/src/components/AssetProviderPage/AssetProviderPage.module.css, webapp/src/components/AssetProviderPage/AssetProviderPage.tsx, webapp/src/components/AssetProviderPage/AssetProviderPage.types.ts
=> fix: loading indicator missplaced in the asset page

webapp/src/components/Modals/RentalListingModal/EditConfirmationStep/EditConfirmationStep.tsx
=> fix: Prevent edit modal from closing in the second step

webapp/src/components/StoreSettings/StoreSettings.tsx, webapp/src/modules/store/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
Closes #1105 
Users can update the old Discord url to the new one by writing the channel id in the input field.
Using the example of Uniswap https://discord.gg/FCfyBSbCU5 to the invite page.
Also changed the text to Invite ID instead of channel ID
=> feat: Update discord prefix

webapp/src/components/AssetPage/SaleRentActionBox/PeriodsDropdown/PeriodsDropdown.tsx, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.module.css, webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx
This PR changes the sale rent box styles to match the new styles.
It also removes a default value on a dropdown that shouldn't be there and was causing some warnings to pop up.
Closes #1120
=> fix: Change sale rent box styles

webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx, webapp/src/components/AssetProvider/AssetProvider.container.ts, webapp/src/components/AssetProvider/AssetProvider.tsx, webapp/src/components/CollectionProvider/CollectionProvider.container.ts, webapp/src/components/CollectionProvider/CollectionProvider.tsx, webapp/src/components/CollectionProvider/CollectionProvider.types.tsx, webapp/src/config/env/dev.json, webapp/src/config/env/prod.json, webapp/src/config/env/stg.json, webapp/src/modules/collection/actions.ts, webapp/src/modules/collection/sagas.ts, webapp/src/modules/collection/selectors.spec.ts, webapp/src/modules/collection/selectors.ts, webapp/src/modules/item/selectors.spec.ts, webapp/src/modules/item/selectors.ts, webapp/src/modules/rental/utils.ts
This PR reduces the NFT server requests by:
- Increasing the delay used when waiting for a rental to be changed.
- Changes the `TransactionHistory` component so it doesn't re-trigger the request when the asset instance changes.
- Changes the `CollectionProvider` component so it fetches items and and collections separately, removing the need to fetch the collection again when fetching items.
- Changes the `AssetProvider` component so it doesn't re-fetch assets when they were already fetched.
Closes #1128
=> fix: Reduce NFT server requests

webapp/src/components/Vendor/decentraland/NFTFilters/NFTFilters.tsx, webapp/src/modules/routing/search.ts
This PR adds the cheapest sort under the `MAX_RENTAL_PRICE`.
As of today, the maximum value of the rental price on all periods is the same as the minimum one, but we're using the maximum value everywhere due to the chance of someone registering the values manually.
=> feat: Add cheapest filter for rentals

webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/sagas.ts
This PR fixes the issue where rental listings couldn't be accepted by the contracts because of ending in 0 or 1, making the validation fail due to an invalid V value.
=> fix: Fix rentals signature with V different from 27 or 28

webapp/src/components/ManageAssetPage/Details/Details.tsx, webapp/src/components/ManageAssetPage/Details/Details.types.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds the missing order and rental expiration dates in the details.
Closes #1141
=> fix: Show expiration date on rentals and orders

webapp/src/modules/rental/sagas.spec.ts, webapp/src/modules/rental/utils.spec.ts, webapp/src/modules/rental/utils.ts
This PR removes the length check from the ECDSA V check.
=> fix: Remove lenght check from V check

webapp/src/components/Modals/RentalsLaunchModal/RentalsLaunchModal.module.css, webapp/src/components/Modals/RentalsLaunchModal/RentalsLaunchModal.tsx
This PR changes the following:
- Makes the Rentals Launch Modal dim up to 50% (was not dimmed at all before).
- Center the Rentals Launch Modal.
- Makes the `browse list` button go to the rentals without having the map or the fullscreen set.
=> fix: Show lands as lists, center the modal and add dimming up to 50%

webapp/src/components/SettingsPage/SettingsPage.container.ts, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/components/SettingsPage/SettingsPage.types.ts, webapp/src/modules/contract/actions.ts, webapp/src/modules/contract/reducer.spec.ts, webapp/src/modules/contract/reducer.ts, webapp/src/modules/contract/sagas.spec.ts, webapp/src/modules/contract/sagas.ts, webapp/src/modules/contract/selectors.ts
Closes #1167 
- Fetched contracts only once per session, meaning that as long as you are navigating with the same account contracts will be fetched once no matter how many times you enter the settings page.
- Fixed issue were disconnecting while inside the settings page broke everything 🚀
=> feat: Only fetch contracts on same session

webapp/src/components/SellPage/SellModal/SellModal.tsx
Was being signed as an erc721 instead of a decentraland collection
=> fix: Emote authorization for selling was not working on meta transactions

webapp/src/components/Vendor/VendorMenu/VendorMenu.tsx, webapp/src/modules/nft/types.ts, webapp/src/modules/tile/sagas.ts, webapp/src/modules/vendor/decentraland/nft/api.ts, webapp/src/modules/vendor/decentraland/nft/types.ts
Closes #1190 
Also removes contracts property on nft fetch params which is not used.
Adds contracts property to nft fetch filters as it was always provided but incorrectly parsed.
https://user-images.githubusercontent.com/24811313/209884465-e2de17e0-9fa0-476b-9f47-22fe0c2ba5ab.mov
=> fix: Collections search on My Assets

webapp/src/components/ManageAssetPage/Rent/Rent.module.css, webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.module.css, webapp/src/components/Modals/RentalListingModal/CreateOrEditListingStep/CreateOrEditListingStep.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds a missing editing cost warning message when editing the rental listings.
Closes #1146
=> fix: Add missing editing cost warning message

webapp/src/components/AssetCard/AssetCard.css, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/AssetImage/AssetImage.container.ts, webapp/src/components/AssetImage/AssetImage.css, webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetImage/AssetImage.types.ts
This PR fixes the order tag that was unaligned when showing assets in different screens.
The PR changes where the order listing tag is shown so it gets rendered alongside the `AssetImage`, grabbing its parent height and using the `bottom` property to position it at the bottom.
Closes #1196
=> fix: Order tag unalined

webapp/src/components/AssetBrowse/AssetBrowse.css, webapp/src/components/BackToTopButton/BackToTopButton.module.css
Without these changes, it looks like this:
=> fix: hide assetbrowse left sidebar on mobile

webapp/src/components/Atlas/Atlas.tsx, webapp/src/components/Atlas/Atlas.types.ts, webapp/src/components/Atlas/Popup/Popup.css, webapp/src/components/Atlas/Popup/Popup.tsx, webapp/src/modules/rental/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR adds the capability to process rental listing that come from the atlas server and show them painted as light blue (the same color as the ones for sale) in the map. It also changes the popups to show the rental price.
=> feat: Add rentals to tile map

webapp/src/components/Menu/MenuItem/MenuItem.tsx, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts
Closes #1241
When clicking clear filters the URL will have `onlyOnSale=true`:
```
http://localhost:3000/browse?assetType=nft&section=wearables_facial_hair&vendor=decentraland&page=1&sortBy=recently_listed&onlyOnSale=true&viewAsGuest=false
```
=> fix: onSale reset behavior and keyboard usage for category menu

webapp/src/components/AssetTopbar/AssetTopbar.module.css
Add some margin to asset topbar on mobile
=> fix: add margin to asset topbar

.github/workflows/build-release.yaml
The GH runner is runnig out of memory space when running the `npm run build`, we need to override the default value to use more memory.
=> feat: add more memory to GH action runner

webapp/src/components/CollectionProvider/CollectionProvider.container.ts, webapp/src/components/CollectionProvider/CollectionProvider.tsx, webapp/src/components/CollectionProvider/CollectionProvider.types.tsx
=> fix: prevent CollectionProvider from looping forever when collection is not found

webapp/src/modules/nft/utils.spec.ts, webapp/src/modules/nft/utils.ts
This PR fixes the wrong gender text shown in the gender badge
Female gender badge:
Male gender badge:
Closes #1376
=> fix: Wearable asset page show incorrect gender badge text

webapp/src/components/AssetImage/AssetImage.tsx
This PR avoids sending a preview emote to the WearablePreview with an undefined avatar.
Closes #1377
=> fix: Validate wearable has a valid representation for the current avatar

webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx, webapp/src/modules/wallet/utils.spec.ts, webapp/src/modules/wallet/utils.ts
It works both for small numbers and for the max amount of MANA that a user could have.
=> fix: Remove scientific notation in small numbers

webapp/src/components/ManageAssetPage/Rent/Rent.tsx
This PR fixes an issue where rented lands that expired were not able to be listed for rent again (the button was not visible).
=> fix: Show list for rent button after expired rental listing

webapp/src/components/AssetImage/AssetImage.css
In order to improve accessibility and avoid name scams, this PR changes the color of the name detail in the ENS names cards.
Before:
After:
Closes #1467
=> fix: Make small name brighter in the names cards

webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/AssetList/AssetList.types.ts, webapp/src/components/InfiniteScroll/InfiniteScroll.spec.tsx, webapp/src/components/InfiniteScroll/InfiniteScroll.tsx, webapp/src/components/InfiniteScroll/InfiniteScroll.types.ts, webapp/src/components/InfiniteScroll/index.ts
Add infinite scroll to asset lists with the possibility to limit the amount of pages in infinite scroll and adding "Load more button" after those pages
https://user-images.githubusercontent.com/11800206/228586746-fddf2856-26b2-4543-b421-cadca03a0484.mov
=> feat: add infinite scroll to asset list

.github/workflows/set-rollout.yaml
This PR updates the Ubuntu version that was deprecated in the Github Actions.
=> fix: Update Ubuntu version on rollouts

.github/workflows/set-rollout-manual.yaml
Set ubuntu version on manual rollout to be latest instead of 18.04 as it is deprecated
=> fix: ubuntu version on manual rollout

webapp/package-lock.json, webapp/package.json
This PR updates the decentraland dapps dependency to include the fix for the issue with dropped transactions when changing networks.
=> chore: Update decentraland dapps

webapp/src/components/ActivityPage/ActivityPage.tsx, webapp/src/components/Bids/Bids.tsx, webapp/src/components/Navbar/Navbar.container.ts, webapp/src/components/Navbar/Navbar.tsx, webapp/src/components/Navbar/Navbar.types.ts, webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/modules/routing/locations.ts, webapp/src/modules/ui/sagas.ts
Add `redirectTo` query param in signin page so when sign in finishes it redirects to the desired page instead of always redirecting to account view
=> feat: redirect after log in

webapp/src/components/AssetList/AssetList.container.ts
This PR fixes an early message that showed that there weren't any results instead of a loader when the favorites were being loaded before querying the nft-server for the items.
=> fix: Loading my lists

webapp/src/modules/vendor/utils.ts
The `address` param for My assets page will have the current address, so it's not what we want. It should always use the `creators` param which is read from the URL.
=> fix: Creators filter NFT params

webapp/src/components/Modals/FavoritesModal/FavoritesModal.module.css, webapp/src/components/Modals/FavoritesModal/FavoritesModal.tsx, webapp/src/modules/vendor/decentraland/favorites/api.spec.ts, webapp/src/modules/vendor/decentraland/favorites/api.ts
- Adds a bar to split the modal text from the list.
- Changes the styles of the Profile component so the user's address / text is bigger and is centered.
- Fixes how picks were fetched.
=> fix: Modal styles and data loading

webapp/src/components/ListsPage/ListsPage.module.css, webapp/src/components/ListsPage/ListsPage.tsx
- Changes the `Footer` and `AssetBrowse` component props removing `isFullscreen` which is used when the map is shown and broke the screen.
- Removes unused CSS
- Removes unused header component
Closes #1557
=> fix: My lists overflows

webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
This PR fixes an issue where loading more than 20 items broke the My List pagination due to the nft-server waiting for the `first` parameter to come along with the queried ids.
Closes #1580
=> fix: Loading more than 20 items in my lists broke pagination

webapp/src/components/AccountPage/AccountPage.tsx, webapp/src/components/ListsPage/ListsPage.tsx, webapp/src/components/Navbar/Navbar.tsx
This PR changes the Navbar to avoid adding multiple redirections to the sign in page to itself when clicking the `sign-in` button while being in the Sign in page.
It also adds redirection to the My Lists and the My Assets page.
=> fix: Re-redirect when being in the sign in page

webapp/src/components/ListsPage/ListsPage.tsx
This PR prevents the favorites request to be performed when the user is not connected.
Although the `useEffect` was in place, the `AssetBrose` got executed and favorites was tried to get requested without a wallet.
=> fix: Requesting favorites without wallet

webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
This PR fixes an error that prevented users with no favorited items from loading the tab correctly.
The fix puts either the `fetchItemsRequest` or the `fetchItemsSuccess` depending on if the favorites API response resulted in more than one id or not.
Closes #1590
=> fix: Loading empty list of favorited items

webapp/src/components/FavoritesCounter/FavoritesCounter.module.css
=> fix: Avoid underlining the counter when has 0 picks

webapp/src/components/AssetCard/AssetCard.container.ts, webapp/src/components/AssetList/AssetList.container.ts, webapp/src/components/CollectionList/CollectionList.container.ts, webapp/src/components/Sales/Activity/Activity.container.ts, webapp/src/modules/routing/locations.ts, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/routing/types.ts, webapp/src/modules/ui/browse/sagas.spec.ts, webapp/src/modules/ui/browse/sagas.ts
This PR introduces the `getPageName` selector which replaces the `getView` selector in cases where we want to know what the page the user is in.
Closes #1592
=> fix: Use page name instead of view

webapp/src/index.css
=> fix: Incrase the content width of the toasts on all screens but mobile

webapp/src/components/AssetCard/AssetCard.css, webapp/src/components/AssetCard/AssetCard.tsx, webapp/src/components/AssetTopbar/SelectedFilters/SelectedFilters.tsx, webapp/src/components/Vendor/NFTSidebar/NFTSidebar.tsx, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts
This PR fixes:
- Navigation between "Names" and "Wearables"/"Emotes"
- Cards should not grow if not extra info will be displayed
- Status filter now has a Pill so it can be removed (only if !== to `ON_SALE`)
- Remove `RECENTLY_LISTED` sort option duplicated when applying `Only Listings` status
- For "Not on sale" cards, always show the amount of owners (it was only on hover before)
=> fix: bugs related to status filter and assetType being set wrongly

webapp/src/components/AssetList/AssetList.tsx, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
This PR mitigates the case where there's no identity loaded and the user wants to perform a favorites action.
Closes #1638
=> feat: Force getting the identity for the favorites feature

webapp/src/components/AssetImage/AssetImage.tsx
=> fix: not show on sale and rent land on asset view

webapp/src/components/AssetList/AssetList.css, webapp/src/components/AssetList/AssetList.tsx
This PR fixes an issue where when loading a set of assets, the Assets would shift a bit down the page until. This was caused because the sticky position of the loader made the site take into consideration the height of it, making it grow although it was in other position.
As the loading is always paired with an overlay, this PR creates a new overlay that is transparent with absolute position where the loader can sit without increasing the size while being in the center.
Closes #1659
=> fix: Asset list changing positions when loading

webapp/src/components/AssetPage/EmoteDetail/EmoteDetail.tsx, webapp/src/components/AssetPage/ListingsTable/ListingsTable.tsx, webapp/src/components/AssetPage/ListingsTable/ListingsTable.types.ts, webapp/src/components/AssetPage/ListingsTable/utils.tsx, webapp/src/components/AssetPage/OwnersTable/OwnersTable.tsx, webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
=> feat: added other listings table

webapp/package-lock.json, webapp/package.json, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.containter.ts, webapp/src/components/BuyPage/BuyNFTModal/BuyNFTModal.tsx, webapp/src/modules/order/actions.ts, webapp/src/modules/order/sagas.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx
Add new param `silent` in `executeOrderRequest` saga so that it doesn't show a toast if transaction fails. We are using this as true only when the action was triggered by the authorization modal, as we are already showing the error in the modal so there is no need to show also the toast
=> feat: remove error toast on authorization modal

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetList/AssetList.tsx, webapp/src/components/CollectionProvider/CollectionProvider.container.ts, webapp/src/modules/collection/sagas.spec.ts, webapp/src/modules/collection/sagas.ts, webapp/src/modules/item/actions.spec.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/reducer.spec.ts, webapp/src/modules/item/reducer.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts, webapp/src/modules/ui/browse/reducer.spec.ts, webapp/src/modules/ui/browse/reducer.ts
Since the data is already in the store going back from the detail to the /browse again, we don't need to fetch it again. This PR avoids the re-fetch of the items.
The `fetchItemsRequest` is triggered in the detail page to get the collection items and it resets the `ui` state so I had to either:
- pass a flag to avoid reseting the `ui` state (so it doesn't fetch again the items)
- create a new action that doesn't override the `ui`. (fetching collection items for the detail shouldn't update the `ui`)
=> fix: do not fetch assets if they are in the store

webapp/src/modules/account/sagas.spec.ts, webapp/src/modules/account/sagas.ts, webapp/src/modules/account/utils.spec.ts, webapp/src/modules/account/utils.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR also adds the label `$name (currently $actualName)`  in case there is a match of the ENS but they have another ENS set in their profile. Like the following image:
`kj` is the search term. There is a match with `rickJames` but in their profile they have `Jessie` now, so we need to clarify why `Jessie` is shown.
Closes #1735
=> feat: add mechanism to fetch all ens that match the creator search

webapp/src/modules/ui/browse/reducer.spec.ts, webapp/src/modules/ui/browse/reducer.ts
This PR fixes the lists pagination that was caused because of the store not saving the current pagination.
=> fix: Pagination not storing the current page

webapp/src/components/ListsPage/ListsPage.spec.tsx
This PR fixes an issue where the lists mocks for the ListsPage because they didn't have ids, when rendering the lists, they came up with missing `key` errors.
=> fix: Key usage in lists page tests

webapp/src/components/UserMenu/UserMenu.container.ts, webapp/src/components/UserMenu/UserMenu.tsx, webapp/src/components/UserMenu/UserMenu.types.ts
This PR changes the `UserMenu` component so the user gets redirected to the `My Lists` page after clicking on it.
Closes #1828
=> fix: User menu lists doesn't redirect to my lists

webapp/src/components/ListsPage/ListCard/ListCard.module.css
=> fix: Allow list cards to grow up to the 100% of the available space

webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts
This PR changes the actions that were being raced in the `handleBulkPickStart` saga.
The race now handles the `BULK_PICK_REQUEST` action that would occur when the users picked some lists without creating one, ending the saga. Without handling this action, the saga would hang and, whenever any of the other actions occurred, it would continue all of them.
Closes #1868
=> fix: End bulk sagas when closing the modal or failing the creation of a list

webapp/src/components/Modals/ShareListModal/ShareListModal.tsx, webapp/src/modules/analytics/track.ts, webapp/src/modules/favorites/actions.ts, webapp/src/modules/favorites/sagas.spec.ts, webapp/src/modules/favorites/sagas.ts, webapp/src/utils/events.ts
This PR takes the bulk picks and unpicks and translates them into smaller actions which will get tracked. It also simplifies the `SHARE_LIST` event so it holds the type of sharing that it was used (twitter, link copied).
Closes #1804
=> feat: Split bulk picks and unpicks

webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.container.ts, webapp/src/modules/asset/reducer.spec.ts, webapp/src/modules/asset/reducer.ts, webapp/src/modules/asset/selectors.spec.ts, webapp/src/modules/asset/selectors.ts
This PR refactors fetching SW requiredPermissions to use the urn instead of the item/token id
=> fix: Refactor fetching SW required permissions

webapp/src/components/LinkedProfile/LinkedProfile.container.ts, webapp/src/components/LinkedProfile/LinkedProfile.tsx, webapp/src/components/LinkedProfile/LinkedProfile.types.ts, webapp/src/components/LinkedProfile/index.ts, webapp/src/config/env/dev.json, webapp/src/config/env/prod.json, webapp/src/config/env/stg.json, webapp/src/lib/environment.ts, webapp/src/modules/features/selectors.spec.ts, webapp/src/modules/features/selectors.ts, webapp/src/modules/features/types.ts, webapp/src/modules/sagas.ts
This PR updates the LinkedProfile component to redirect to the profile dApp when the FF: `dapps-profile` is enabled.
Closes https://github.com/decentraland/profile/issues/73
=> feat: Add profile dApp redirection

webapp/package-lock.json, webapp/package.json
The new version updates the style of the iframe so it cannot be seen anymore.
=> fix: Update sso client

webapp/src/components/AssetImage/AssetImage.tsx
This PR fixes the button `Play Emote` opening the VideoShowcase modal
Error:
https://github.com/decentraland/marketplace/assets/3170051/4b61433f-2ca2-48fb-83e8-375fb8613f8e
Fix:
https://github.com/decentraland/marketplace/assets/3170051/cd201d2d-14a9-476c-86fd-0117b5c193cd
=> fix: Show SmartWearables video showcase

webapp/package.json
We are not using the source maps in Sentry yet. I removed the generation from the build script and I'll work on it later.
=> fix: Remove sourcemap generation for now

webapp/src/components/AssetBrowse/AssetBrowse.tsx
This PR fixes an issue that prevented users from selecting a section in the My Assets page while on mobile.
=> fix: Can't select section to load in My Assets

webapp/src/components/ClaimYourName/ClaimYourName.module.css, webapp/src/components/ClaimYourName/ClaimYourName.tsx
The claim name button looked like this on bigger screens:
Fixed it to look like this:
=> fix: Claim Name button styles

webapp/src/components/AccountSidebar/CurrentAccountSidebar/CurrentAccountSidebar.tsx
=> fix: Expand the only smart section by default in the current account sidebar

webapp/src/components/AssetImage/AssetImage.tsx
Add `disableDefaultWearables` prop so that it doesn't add wearables that are not equipped when showing user profile
=> fix: disable default wearables

webapp/src/components/AssetImage/AssetImage.tsx
Remove `disableDefaultWearables` property as the usecase was already added on the wearable-preview side and this is causing emotes for not logged in users to appear without any clothes
=> feat: add default wearables back

webapp/src/modules/routing/selectors.ts, webapp/src/modules/routing/utils.ts
Fix pills not appearing when the only filter is by props or sound
Fix "Clear all filters" so that it removes emoteHasSound and emoteHasGeometry properties from filters too
=> fix: emote 2.0 filter pills

webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/components/AssetTopbar/SearchBarDropdown/SearchBarDropdown.tsx
- Fix issue when clearing search input it would not reload the page with all items
- Fix double call to catalog endpoint when using search dropdown. It was being called once with the previous searchUUID and once with the correct searchUUID
=> fix: empty search catalog

webapp/src/components/HomePage/Slideshow/Slideshow.css, webapp/src/index.css
This PR fixes the space between components in ultra-wide screens.
The `max-width` was removed from the containers in this previous [PR](https://github.com/decentraland/marketplace/pull/2090/files#diff-53c401ad1b9e0890ce8feea1af4aa5003516508ae4b2da8e9b3e7ad14518df0aL57)
bug:
fixed:
Fixes: https://github.com/decentraland/dapps-issues/issues/119
=> fix: Container width and navbar full-width

webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/utils.spec.ts, webapp/src/components/Modals/BuyWithCryptoModal/utils.ts
=> fix: fix the formatPrice fn to show at least 1 relevant decimal

webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyNftWithCryptoModal/BuyNftWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.types.ts, webapp/src/components/Modals/BuyWithCryptoModal/MintNameWithCryptoModal/MintNameWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/MintNftWithCryptoModal/MintNftWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/hooks.spec.ts, webapp/src/components/Modals/BuyWithCryptoModal/hooks.ts, webapp/src/components/Modals/BuyWithCryptoModal/utils.ts
- Adds a fix to the `AssetImage` component where it was fetching the item of parcel, estates or ens NFTs.
- Changes the way we load the default chains in the development environment. It now loads the default chains using the `getDefaultChains` function which discriminates between the development and the production environment.
- Simplifies the gas hooks by removing the `providerTokens` variable which was used to get the chain native token. The chain native token is now computed in the modal.
- Simplifies the gas hooks by removing the `selectedChain` variable, as it can be retrieved from the `selectedToken`.
- Simplifies the `useShouldUseCrossChainProvider` by removing the `selectedChain` variable that can be retrieved from the `selectedToken`.
- Splits the …
=> fix: Add gas cost and token balance hooks tests and simplify functions

webapp/package-lock.json, webapp/package.json, webapp/src/components/SuccessPage/SuccessPage.container.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/routing/locations.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts
This PR adds the logic to:
- Track both txs when is a reall cross-chain purchase (not only cross-token)
=> feat: add logic to track both chains txs

webapp/package-lock.json, webapp/package.json, webapp/src/components/ActivityPage/Transaction/Transaction.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx, webapp/src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.types.ts, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/components/SuccessPage/SuccessPage.container.ts, webapp/src/config/env/dev.json, webapp/src/config/env/prod.json, webapp/src/config/env/stg.json, webapp/src/modules/ens/sagas.spec.ts, webapp/src/modules/ens/sagas.ts, webapp/src/modules/item/actions.ts, webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts, webapp/src/modules/routing/locations.ts, webapp/src/modules/routing/sagas.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/sagas.ts, webapp/src/modules/store.ts, webapp/src/modules/toast/sagas.spec.ts, webapp/src/modules/toast/sagas.ts, webapp/src/modules/toast/toasts.tsx
This PR uses the new version of the transactions module, which fetches and waits for pending cross chain transactions.
It removes all the logic created to work with cross chain transactions once they were launched.
=> feat: Use new cross chain transaction payload action

webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.container.ts, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx
This PR fixes:
- Add logic to buy the MANA of the network which the NFT belongs
- Show insufficient selected token first instead of the gas one.
=> fix: add nft network to mana buy modal trigger

webapp/.eslintrc.cjs, webapp/src/components/AssetPage/BestBuyingOption/BestBuyingOption.spec.tsx, webapp/src/components/AssetTopbar/SearchBarDropdown/SearchBarDropdown.spec.tsx, webapp/src/components/FavoritesCounter/FavoritesCounter.spec.tsx, webapp/src/components/Menu/DropdownMenu/DropdownMenu.tsx, webapp/src/components/Menu/MenuItem/MenuItem.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.tsx, webapp/src/components/Modals/SaveToListModal/SaveToListModal.spec.tsx, webapp/src/components/Modals/ShareListModal/ShareListModal.spec.tsx, webapp/src/components/StoreSettings/CoverPicker/CoverPicker.tsx, webapp/src/components/Table/TableContent/TableContent.spec.tsx, webapp/src/index.tsx, webapp/src/lib/timer.spec.ts, webapp/src/lib/utils.ts, webapp/src/modules/rental/contract.spec.ts, webapp/src/modules/routing/sagas.ts, webapp/src/modules/vendor/TokenConverter.ts, webapp/src/modules/vendor/decentraland/builder/api.spec.ts, webapp/src/modules/vendor/decentraland/rentals/api.spec.ts
This PR fixes the following linting rules:
- no-async-promise-executor
- no-misused-promises
- no-unnecessary-type-contraint
- no-prototype-builtins
- require-await
=> fix: Linting rules (no-async-promise-executor, no-misused-promises, no-unnecessary-type-contraint, ...)

webapp/.eslintrc.cjs, webapp/src/modules/routing/search.ts, webapp/src/modules/routing/selectors.ts
Add naming-convention rule again, but enable PascalCase for functions so we can follow react convention for functional components
=> fix: naming convention rule accept PascalCase

webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.container.ts, webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.spec.tsx, webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.tsx, webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.types.ts, webapp/src/modules/asset/actions.spec.ts, webapp/src/modules/asset/actions.ts, webapp/src/modules/asset/reducer.spec.ts, webapp/src/modules/asset/reducer.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json, webapp/vite.config.ts
This PR prevents the re-fetching of the smart items required permissions if it fails.
=> fix: Don't refetch required permissions

webapp/package-lock.json, webapp/package.json, webapp/src/lib/asset.ts
This PR removes the download content check when downloading content from the Catalyst. This is a temporary fix for the real issue, which is that the hashing library is built in some way that crypto is loaded as the node crypto package, which fails.
=> fix: Remove download content check

webapp/src/modules/wallet/utils.spec.ts, webapp/src/modules/wallet/utils.ts
When MM is blocked, this saga keeps waiting for ever since it won't succed or failed. This PR adds a timeout to avoid that
=> fix: add timeout when MM active method hangs

webapp/src/modules/ui/asset/homepage/selectors.spec.ts, webapp/src/modules/ui/asset/homepage/selectors.ts
the emote in this image is an nft instead of an item
after the fix, it's not in the carousel any more, instead the item that has that same `itemId` as the `nftId` from above, is shown:
=> fix: add mapper to getHomepage to it looks for nfts or items

webapp/src/components/AssetImage/AssetImage.tsx, webapp/src/components/AssetPage/AssetPage.css, webapp/src/components/AssetPage/EmoteDetail/EmoteDetail.module.css, webapp/src/components/AssetPage/EmoteDetail/EmoteDetail.tsx, webapp/src/components/AssetPage/ItemDetail/ItemDetail.module.css, webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/AssetPage/ListingsTable/ListingsTable.module.css, webapp/src/components/AssetPage/RequiredPermissions/RequiredPermissions.module.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.module.css, webapp/src/components/AssetPage/WearableDetail/WearableDetail.tsx, webapp/src/components/SellPage/SellPage.css
This PR has multiple fixes of the Wearables, Emotes and Items detail pages:
- It fixes the AssetImage in the Wearables, Emotes and Item details pages, which had a big margin when they had a listing available and where viewed by the owner.
- It fixes how the owner, collections, description and utils is organized, making them have a table shaped style.
- It fixes the listing table in the Wearables and Emotes detail pages, which had a button of a bigger size that what they could fit.
- It fixes the AssetPage padding in mobile devices, which added a big blank space at the top.
=> fix: Styles in the Wearables, Emotes and Items detail page

webapp/src/components/RankingsTable/RankingCreatorRow/RankingCreatorRow.css
=> fix: subtitle overlapping the creators name in the homepage table

webapp/src/components/AssetBrowse/AssetBrowse.tsx, webapp/src/components/AssetBrowse/AssetBrowse.types.ts, webapp/src/components/AssetTopbar/AssetTopbar.tsx, webapp/src/components/AssetTopbar/AssetTopbar.types.ts, webapp/src/components/NamesPage/NamesPage.tsx, webapp/src/modules/routing/selectors.spec.ts, webapp/src/modules/routing/selectors.ts
This PR fixes an issue where:
1. When in the name's browse site, other assets would be loaded when loading more names.
2. The search bar dropdown showed wearables instead of names.
By:
1. Setting the correct section when the user is in the names browse section so the browse sagas can set the correct category (ENS).
2. Adding the capability to **not** show the search bar dropdown for names, as the feature does not work with names for the time being.
=> fix: Names search showing other assets

webapp/src/modules/vendor/decentraland/marketplace/api.ts
This PR fixes the marketplace-api balance url and the testnet polygon amoy name
=> fix: Fetching balances endpoint url and polygon amoy name

webapp/src/components/StoreSettings/CoverPicker/CoverPicker.tsx
In order to prevent the site from fetching a blob, read the image content and store it as a data url when previewing it.
=> fix: Use inline images when loading a cover

webapp/package-lock.json, webapp/package.json, webapp/src/modules/bid/utils.ts, webapp/src/utils/trades.spec.ts, webapp/src/utils/trades.ts
This PR changes the way we're building the trade object to be signed to correctly set the parameters of byte values (extra and the external check values). The issue seems to have come from the usage of `ethers.utils.hexlify` `ethers.utils.toUtf8Bytes` to allow building the trade signature without failures when the byte parameters where set as empty strings, which the signature function would not recognize as empty byte arrays (the real type).
This PR replaces the usage of those functions in favor of setting the value `'0x'`, the empty bytes value, when the bytes parameters is empty or the set value when it's set.
Depends on: https://github.com/decentraland/decentraland-dapps/pull/656
=> fix: Incorrectly building trade byte parameters

webapp/src/components/AssetPage/ItemDetail/ItemDetail.tsx, webapp/src/components/CancelSalePage/CancelSalePage.tsx, webapp/src/components/ConfirmInputValueModal/ConfirmInputValueModal.tsx, webapp/src/components/Modals/SellModal/SellModal.container.ts, webapp/src/components/Modals/SellModal/SellModal.tsx, webapp/src/components/SellPage/SellModal/SellModal.tsx, webapp/src/modules/modal/sagas.spec.ts, webapp/src/modules/modal/sagas.ts, webapp/src/modules/vendor/decentraland/nft/authApi.ts
This PR fixes the following issues:
- The cancel sell page was not disabling the cancel button when cancelling an order.
- The ConfirmInputValue, which is used to confirm the process of placing an order was not correctly disabling the inputs when loading.
- The sell modal was not preventing users from closing it when cancelling the order.
- When creating an order, the site reloaded the NFT to get information about the order, but, as the request is now cached, the user wasn't seeing the NFT on sale for the duration of the cache.
- When cancelling an order, specially on lands, the modal was not closed after finishing the process.
- (Not an off chain issue) Removes the owner div on L1 items, thus aligning the components to look nicer.
=> fix: Multiple off chain issues

webapp/package-lock.json, webapp/package.json, webapp/src/modules/ens/sagas.ts
Fix the issue with the Axelar modal caused due to `decentraland-transactions` working only with ethers v5.
=> fix: upgrade decentraland-transactions

webapp/src/components/HomePage/HomePage.tsx, webapp/src/components/HomePage/hooks.ts
Adds logic to load home page sections when they enter in the user viewport
=> feat: add intersection observer to homepage sections

webapp/package-lock.json, webapp/package.json
This PR updates `decentraland-connect` and `decentraland-dapps` to use the new Magic's OAuth V2 provider.
=> BREAKING: Update decentraland-connect

webapp/src/components/SettingsPage/SettingsPage.tsx, webapp/src/modules/contract/sagas.spec.ts, webapp/src/modules/contract/sagas.ts, webapp/src/modules/vendor/decentraland/contracts.ts
This PR adds the off chain marketplace to the settings page to allow or revoke the handling of MANA.
There's one slight issue with the settings handling. The name of the contracts is the same for all of the marketplace's contracts. This should be addressed in another PR.
=> feat: Add off chain marketplace to contract settings

webapp/src/components/Modals/BuyWithCryptoModal/utils.spec.ts, webapp/src/components/Modals/BuyWithCryptoModal/utils.ts, webapp/src/utils/trades.spec.ts, webapp/src/utils/trades.ts
This PR fixes the gas estimations used in the BuyWithCryptoModal for trades. We weren't considering that the estimation should be done using the offchain marketplace contract if there's a trade available.
=> fix: Gas estimations for trades

webapp/package-lock.json, webapp/package.json, webapp/src/components/Modals/BuyWithCryptoModal/BuyNftWithCryptoModal/BuyNftWithCryptoModal.container.ts, webapp/src/components/Modals/BuyWithCryptoModal/BuyNftWithCryptoModal/BuyNftWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/BuyNftWithCryptoModal/BuyNftWithCryptoModal.types.ts, webapp/src/components/Modals/BuyWithCryptoModal/MintNameWithCryptoModal/MintNameWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/MintNftWithCryptoModal/MintNftWithCryptoModal.container.ts, webapp/src/components/Modals/BuyWithCryptoModal/MintNftWithCryptoModal/MintNftWithCryptoModal.tsx, webapp/src/components/Modals/BuyWithCryptoModal/MintNftWithCryptoModal/MintNftWithCryptoModal.types.ts, webapp/vite.config.ts
This PR uses the changes in the `decentraland-dapps` package that allow as to mark as manual the authorizations that require the user to pay gas. These authorization that require gas are for the purchase of L1 assets or L2 assets on the native network.
=> feat: Manually sign authorizations that require gas when using Magic

webapp/src/components/AssetPage/BidsTable/BidsTableContent/BidsTableContent.container.ts, webapp/src/components/AssetPage/BidsTable/BidsTableContent/BidsTableContent.tsx, webapp/src/components/AssetPage/BidsTable/BidsTableContent/BidsTableContent.types.ts, webapp/src/components/Bid/Bid.tsx, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx, webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.container.ts, webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.tsx, webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.types.ts, webapp/src/components/SellPage/SellModal/SellModal.tsx
This PR changes the auth modal behavior so it shows the authorization modal on operations that consume gas for the Magic users.
=> feat: Use manual contract authorization modal on operations that require gas

webapp/package-lock.json, webapp/package.json, webapp/src/components/BidPage/BidModal/BidModal.tsx, webapp/src/components/SellPage/SellModal/SellModal.tsx
This PR removes the manual authorization for actions that only require paying for the authorization. This means that, bidding, for example, which requires approving the contract to operate MANA on your behalf should not show the authorization modal, as the bid is then done off-chain.
This PR also updates the `decentraland-dapps` dependency which adds internationalization to the Web2TransactionModal.
=> fix: Remove auth for actions that only require paying for authorization

webapp/src/components/Modals/BuyWithCryptoModal/hooks.ts
This PR fixes buying assets with native currency. This feature was failing because the service we're using to retrieve the tokens and chains changed the address that was used for the native token to be lowercased, thus breaking the native currency check used to fetch the balance using our RPCs.
=> fix: Buying assets with native currency

webapp/src/components/Modals/BuyWithCryptoModal/BuyWithCryptoModal.spec.tsx, webapp/src/components/Modals/BuyWithCryptoModal/ChainAndTokenSelector/ChainAndTokenSelector.tsx, webapp/src/components/Modals/BuyWithCryptoModal/hooks.ts, webapp/src/components/Modals/BuyWithCryptoModal/utils.spec.ts, webapp/src/components/Modals/BuyWithCryptoModal/utils.ts
This PR changes the BuyWithCryptoModal to use the RPCs to get the user's token balance instead of using the old API.
To do so, it uses the `InView` component from  `react-intersection-observer`, which will tell us when each token in the list is shown for the first time so we can trigger the token balance fetch.
There are two differences between the API solution:
1. We don't have the price in USD anymore => we don't get that from the balance contract call.
2. We can't order the tokens by the amount the user owns => We don't query the balance of all of the tokens at once.
=> fix: Retrieve user balance in the BuyWithCryptoModal

webapp/package-lock.json, webapp/package.json
This PR introduces a new feature flag (`launcherLinks`) that enables fetching dynamic launcher download links. These links will be used in the Navbar's "Download" button, allowing the client to update download targets without requiring code changes.
Depends on: https://github.com/decentraland/decentraland-dapps/pull/709
=> feat: Add feature flag to fetch dynamic launcher links for Navbar's Download button

webapp/src/modules/ens/sagas.spec.ts, webapp/src/modules/ens/sagas.ts, webapp/src/modules/translation/locales/en.json, webapp/src/modules/translation/locales/es.json, webapp/src/modules/translation/locales/zh.json
This PR changes the way we're claiming a name from using the compiled contract to using the contract from `decentraland-transactions` and the `sendTransaction` method. This change makes it possible to show the gas cost modal for Magic users, as this modal exclusively depends on the `sendTransaction` method.
=> fix: Claiming name not showing the gas cost modal

webapp/src/modules/item/sagas.spec.ts, webapp/src/modules/item/sagas.ts
This PR removes the usage of FFs to load item data from our APIs which when getting an item, in some cases, fetched the item before the FF was loaded.
As we haven't used our old API for a long time, this PR removes all FFs in the items sagas.
=> fix: Item fetched from other API on FF load
