decentraland/marketplace

webapp/src/components/HomePage/Map/ParcelsMap/ParcelPopup/ParcelPopup.css
webapp/src/components/HomePage/Map/ParcelsMap/ParcelPopup/ParcelPopup.js
webapp/src/components/HomePage/Map/ParcelsMap/ParcelsMap.js
webapp/src/lib/parcelUtils.js
webapp/src/modules/address/reducer.js
webapp/src/modules/address/sagas.js
webapp/src/modules/wallet/reducer.js

Show parcel name and description in popup. 
I also added two dictionaries to the wallet selector (`parcelsById` and `contributionsById`) to speed up the lookup in `getParcelAttributes` (used a lot to render the map), otherwise it will get slow specially for people with 100s or 1000s of parcels

[feature] Show parcel name and description

---

src/Contribution/Contribution.js
src/server.js

Group contributions by district

---

README.md

Update Front-End Setup README

---

src/Parcel/Parcel.service.js
src/Parcel/Parcel.spec.js

Update the decentraland-contracts API to the newest version

---

webapp/src/components/HomePage/HomePage.js
webapp/src/components/Modal/Modal.js
webapp/src/components/Toast/Toast.container.js
webapp/src/components/Toast/Toast.css
webapp/src/components/Toast/Toast.js
webapp/src/components/Toast/index.js
webapp/src/components/types.js
webapp/src/modules/ui/actions.js
webapp/src/modules/ui/reducer.js
webapp/src/modules/ui/toast/actions.js
webapp/src/modules/ui/toast/reducer.js

Not implemented as a result of any action, waiting for https://github.com/decentraland/marketplace/pull/39

Toast messages

---

src/Parcel/Parcel.service.js
src/Parcel/Parcel.spec.js
src/database/database.js
src/lib/asyncBatch.js
src/server.js
webapp/src/components/HomePage/Map/ParcelsMap/ParcelPopup/ParcelPopup.js
webapp/src/components/HomePage/Map/ParcelsMap/ParcelsMap.js
webapp/src/components/HomePage/Sidebar/ExpandedSidebar/WalletParcels/ParcelRow/ParcelRow.js
webapp/src/components/HomePage/Sidebar/ExpandedSidebar/WalletParcels/ParcelRowData/ParcelRowData.js
webapp/src/components/HomePage/Sidebar/ExpandedSidebar/WalletParcels/ParcelRowEdit/ParcelRowEdit.js
webapp/src/components/HomePage/Sidebar/ExpandedSidebar/WalletParcels/ParcelTable/ParcelTable.js
webapp/src/components/HomePage/Sidebar/ExpandedSidebar/WalletParcels/WalletParcels.css
webapp/src/components/Icon/Icon.css
webapp/src/lib/api.js
webapp/src/lib/parcelUtils.js
webapp/src/modules/parcels/reducer.js
webapp/src/modules/parcels/sagas.js

Removes name and description from the db.
Adds asyncBatch as a helper.
Maybe related: https://github.com/decentraland/commons/issues/27

Add metadata support onchain on the frontend and the backend.

---

webapp/src/components/HomePage/Sidebar/CollapsedSidebar/SidebarStats/SidebarStats.css
webapp/src/components/HomePage/Sidebar/CollapsedSidebar/SidebarStats/SidebarStats.js
webapp/src/lib/utils.js

Add a text-overflow and a title to long MANA values on the sidebar

---

webapp/src/components/HomePage/Map/ParcelsMap/ParcelsMap.js

[This](https://github.com/decentraland/marketplace/pull/62/files#diff-7abddebcc9b83c131a896449ac7059b6R319) fixes rollbar's `Uncaught TypeError: Cannot read property 'addLayer' of null` and `TypeError: e is null`, also simplifies the debouncing the map render method

[fix] Uncaught TypeError: Cannot read property 'addLayer' of null

---

package.json
scripts/seed.js

Let me know if this helps (will not be able to generate Publications until #60 )
```bash
cd scripts
./seed.js generate Contribution --amount 2
```

Seed data script for tables

---

src/Parcel/Parcel.js
src/Parcel/Parcel.service.js
src/Parcel/Parcel.spec.js
src/Publication/Publication.js
src/Publication/Publication.service.js
src/Publication/Publication.spec.js
src/Publication/PublicationRequestFilters.js
src/Publication/index.js
src/database/database.js
src/server.js

**Depends on**
https://github.com/decentraland/commons/pull/45
**Publication**
```javascript
{
tx_hash: String, // blockchain tx hash. primary key
address: String, // owner
x: Number,
y: Number,
price: String,   // in MANA
tx_status: oneOf(txUtils.TRANSACTION_STATUS), // commons/blob/master/src/ethereum/txUtils.js#L16
is_sold: Boolean, // Default false
expires_at: Date,
created_at: Date
}
```
**Endpoints**
```
GET '/api/addresses/:address/publications'
GET '/api/publications?limit=&offset=&sort_by=created_at&sort_order=desc[asc,desc]'```

Publications backend

---

.circleci/config.yml
package.json
webapp/package.json
webapp/src/components/EditParcelPage/EditParcelForm/EditParcelForm.css
webapp/src/components/Modal/TransferModal/TransferModal.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelActions/ParcelActions.css
webapp/src/components/PublishPage/PublicationForm/PublicationForm.css
webapp/src/components/PublishPage/PublicationForm/PublicationForm.js
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.css
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.js
webapp/src/modules/parcels/sagas.js
webapp/src/modules/publication/sagas.js
webapp/src/modules/transfer/sagas.js
webapp/src/modules/wallet/sagas.js
webapp/src/modules/wallet/utils.js
webapp/src/themes/components/Button.css

It also adds the **real** marketplace publish method !

[Chore] Update commons

---

src/Parcel/Parcel.js
src/Parcel/Parcel.spec.js
src/Publication/Publication.js
src/server.js
webapp/src/components/HomePage/Map/Map.container.js
webapp/src/components/HomePage/Map/Map.js
webapp/src/components/HomePage/Map/ParcelsMap/ParcelsMap.js
webapp/src/lib/api.js
webapp/src/modules/parcels/actions.js
webapp/src/modules/parcels/reducer.js
webapp/src/modules/parcels/sagas.js
webapp/src/modules/ui/map/sagas.js

Blocked by #70 (continuation)
@cazala What do you think of this: https://github.com/decentraland/marketplace/commit/514d8cb9cea87d4ac340282b102ede5863c8e3e7
I removed both the parcel data endpoint _and_ the hover event in an attempt to make things simpler, but that means no more "realtime" data on the server. You'll need to refresh to get the latest data.

[Feature] Parcel publications endpoint

---

scripts/initDb.js
scripts/monitor/handlers/index.js
scripts/seed.js
src/server.js
webapp/src/components/Navbar/utils.js
webapp/src/components/ProfilePage/ProfilePage.container.js
webapp/src/components/TransferParcelPage/TransferParcelForm/TransferParcelForm.js
webapp/src/modules/wallet/sagas.js

@cazala I don't like this commit :(
I tried to only add the `lowercase` on external addresses, for example when we're getting it from MetaMask or on the server. Let me know if you have a better idea, or if I missed something

chore: add toLowerCase to all externally obtained addresses

---

package.json
webapp/src/components/SettingsPage/SettingsForm/DerivationPathDropdown/DerivationPathDropdown.js
webapp/src/components/SettingsPage/SettingsForm/DerivationPathDropdown/index.js
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.css
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.js
webapp/src/components/SettingsPage/SettingsPage.container.js
webapp/src/components/SettingsPage/SettingsPage.js
webapp/src/modules/storage/middleware.js
webapp/src/modules/storage/reducer.js
webapp/src/modules/storage/selectors.js
webapp/src/modules/wallet/actions.js
webapp/src/modules/wallet/reducer.js
webapp/src/modules/wallet/sagas.js
webapp/src/modules/wallet/utils.js
webapp/src/reducer.js

Depends on https://github.com/decentraland/commons/pull/53

feat: Add a dropdown to change your derivation path and persist it on localstorage

---

migrations/1520897388584_pubications-price-to-string.js
src/Parcel/Parcel.js
webapp/src/components/BuyParcelPage/BuyParcelPage.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelDetail.js
webapp/src/components/ParcelDetailPage/ParcelDetailPage.css
webapp/src/components/types.js
webapp/src/lib/utils.js

Drops the DISTINCT in favor of a sub-query.
**Fixes** the publication proptype problem.
**Requires** migration

[Perf] In range query

---

webapp/src/components/SettingsPage/SettingsForm/DerivationPathDropdown/DerivationPathDropdown.js
webapp/src/components/SettingsPage/SettingsPage.js
webapp/src/modules/wallet/utils.js

Depends on https://github.com/decentraland/commons/pull/55.
If you deem this PR worthy and merge commons, please bump it on this package json

fix: Correctly set the derivation path. Send provider url via env.

---

src/Translation/locales/en.json
src/Translation/locales/fr.json
webapp/src/components/AtlasPage/Map/Map.container.js
webapp/src/components/MarketplacePage/MarketplacePage.container.js
webapp/src/components/Navbar/Navbar.container.js
webapp/src/components/ProfilePage/ProfilePage.container.js
webapp/src/components/SignInPage/SignInPage.container.js
webapp/src/components/SignInPage/SignInPage.js
webapp/src/components/SignInPage/index.js

Depends on #90  !!!
will need rebase.
@cazala I tried to stray from adding an `onConnect` method to the `SignIn` page but didn't find a way to "reload" a route. I didn't want to add more redirects either :/
Do you have a better solution?

[Feature] Retry button sign in page

---

.vscode/settings.json
src/Translation/locales/en.json
src/Translation/locales/fr.json
webapp/src/components/ActivityPage/ActivityPage.css
webapp/src/components/ActivityPage/Transaction/Transaction.js
webapp/src/components/AddressLink/AddressLink.js
webapp/src/components/BuyParcelPage/BuyParcelPage.css
webapp/src/components/BuyParcelPage/BuyParcelPage.js
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.js
webapp/src/components/TxStatus/TxStatusIdle/TxStatusIdle.js
webapp/src/components/TxStatus/TxStatusParcel/TxStatusParcel.js
webapp/src/components/TxStatus/TxStatusText/TxStatusText.js
webapp/src/modules/wallet/utils.js

web3 breaks with 2^256-1, had to settle with 2^180
Bunch of other fixes, like missing translations.

[Feat] MANA autorization value to max possible

---

scripts/monitor/persistEvents.js

feat: delete older publications for the same x,y,owner before creating a new one

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
webapp/src/components/Footer/Footer.js
webapp/src/components/Modal/BaseModal/BaseModal.css
webapp/src/components/Modal/Modal.container.js
webapp/src/components/Modal/Modal.js
webapp/src/components/Modal/TermsModal/TermsModal.js
webapp/src/components/TermsPage/TermsPage.js

This adds the terms and conditions to the footer, and fixes a bug where the modal was still visible while the user was in the terms or privacy page.

feat: added terms on footer

---

webapp/src/themes/components/Header.css
webapp/src/themes/components/Menu.css

chore: ditch Lato

---

webapp/src/components/ActivityPage/Transaction/Transaction.css
webapp/src/modules/transaction/sagas.js
webapp/src/modules/translation/utils.js
webapp/src/modules/wallet/reducer.js

Also watch tx hashes from pending transactions from `state.data` if they are not present in `state.loading`

fix: watch pending transactions

---

webapp/src/components/HomePage/HomePage.container.js
webapp/src/components/MarketplacePage/utils.js

Fixes the order of the newest LAND on sale. This also fixes the Home Page.

fix: now newest means newest

---

webapp/src/components/AtlasPage/Map/ParcelsMap/ParcelsMap.js

https://rollbar.com/decentraland/Marketplace/items/26/

fix: null error on `this.map` when panning

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json

Added copyright symbol to footer

chore: Added copyright symbol to footer

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/ParcelDetailPage/ParcelDetailPage.js

feat: Added a link to the Atlas from the ParcelPreview in ParcelDetailPage

---

webapp/src/components/Mana/Mana.js

fix: show 0 balance

---

scripts/seed.js
src/Publication/PublicationRequestFilters.js

fix: pagination after page 9

---

webapp/src/modules/storage/middleware.js
webapp/src/modules/storage/reducer.js
webapp/src/modules/storage/selectors.js
webapp/src/modules/transaction/sagas.js
webapp/src/store.js

feat: only store the useful parts of a transaction

---

webapp/src/index.js
webapp/src/modules/storage/middleware.js
webapp/src/modules/storage/reducer.js
webapp/src/modules/storage/selectors.js
webapp/src/store.js

This reverts commit 963125563de9ba398d1206c19eca7a7bdf200457.

fix: language change and state trimming

---

src/Publication/Publication.spec.js
src/Publication/PublicationRequestFilters.js
src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/MarketplacePage/utils.js

feat: remove "most expensive" sort

---

webapp/src/lib/utils.js
webapp/src/modules/wallet/utils.js

Depends on https://github.com/decentraland/commons/pull/64

feat: only connect to the Ledger wallet if we're on a desktop browser

---

package.json
webapp/package.json

In preparation to a change on dependencies (see https://github.com/decentraland/commons/pull/63)

chore: manually install pg, rollbar, et al (commons #63)

---

webapp/src/modules/translation/utils.js

Give more priority to Chinese and Korean

chore: update lang order

---

package.json
scripts/mktcli.js
scripts/monitor/utils.js
scripts/seed.js
scripts/utils.js
src/BlockchainEvent/BlockchainEvent.js

Usage:
`mktcli.js encode '(1,2)'`
`mktcli.js decode 3.40282366920938463463374607431768211457e+38`

feat: add command line helper tool for encoding decoding assetId

---

migrations/1522426178964_publications-add-block_number.js
scripts/monitor/processEvents.js
src/Publication/Publication.js

feat: store block_numbers on publications

---

migrations/1521221953449_blockchain-events-add-log-index.js
scripts/monitor/handlers/index.js

```
ALTER TABLE blockchain_events DROP CONSTRAINT blockchain_events_pkey
ALTER TABLE blockchain_events ADD PRIMARY KEY (tx_hash, log_index)
```

fix: change the PK to use block_number and log_index

---

webapp/src/index.js

fix: polyfill localstorage

---

webapp/src/lib/webworker/WebWorkerOnMessage.js

fix: don't use Object.assing on webworker

---

README.md
package-lock.json
package.json
scripts/translate.js
src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json

feat: added script to translate automatically using Google Translate

---

scripts/translate.js

- Support `{keys}` at translation script

feat: translation script support {keys}

---

scripts/translate.js

- Use first parameter at `replace`

Improve translation script

---

webapp/src/Routes.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelActions/ParcelActions.js
webapp/src/components/ParcelDetailPage/ParcelDetailPage.js
webapp/src/components/ProfilePage/ProfilePage.js
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.js
webapp/src/modules/address/sagas.js

- Show Mortgage Feature when env  is `development`
- https://trello.com/c/G2OXWGRh/297-hide-mortgages-when-env-development

feat: show mortgages feature when env is development

---

webapp/src/components/ParcelCard/ParcelCard.js

- Remove duplication when displaying `aquire_at`

fix: bad merge at parcel card

---

src/lib/blacklist.js

Fixes the transaction history in the parcel detail

fix: transaction history

---

src/Translation/locales/zh.json

updated the latest version of zh.json

Fix chinese translation

---

package.json
scripts/initDb.js
scripts/monitor/MonitorCli.js
scripts/monitor/program.js
scripts/renewBlockchainData.js
scripts/sanityCheck.js
webapp/package.json

```
npm run sanity-check -- --self-heal
```

feat: Sanity self heal

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/AtlasPage/Map/Map.container.js
webapp/src/components/AtlasPage/Map/Map.js
webapp/src/components/Page/TranslationProvider/TranslationProvider.container.js
webapp/src/components/Page/TranslationProvider/TranslationProvider.js
webapp/src/components/SignInPage/SignInPage.js
webapp/src/modules/wallet/utils.js

This PR removes the spinner on AtlasPage while connecting to Ethereum, and fixes a bug that prevented translations to be fetched while connecting to Ethereum, making first time visitors to have to wait before they can access the marketplace.
I also decremented the retries to 5 (3 for MetaMask, 2 for Ledger) and the sleep time to 125 ms.

fix: loading

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/SignInPage/SignInPage.js

feat: suggest mobile wallets when using mobile instead of metamask

---

webapp/src/components/MarketplacePage/MarketplacePage.js

fix: scroll to top when changing mkt page

---

package-lock.json
package.json
scripts/renewBlockchainData.js

chore: add progress bar to renew blockchain process

---

scripts/seed.js

Added asset_id, block_number and support both timestamp and ms dates

chore: update seed.js script to current publication model

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/ActivityPage/ActivityPage.container.js
webapp/src/components/ActivityPage/ActivityPage.js

feat: change text on mana approved user with no activity

---

src/Map/Map.router.js

fix [API maps.png endpoint with center](https://trello.com/c/lRRwEJ2I/338-at-maprouter-change-getcoords-function-line-238-to-if-coordinatesisvalidparam)

fix: use correct params

---

webapp/src/components/SettingsPage/SettingsPage.js
webapp/src/modules/wallet/sagas.js

fix: connect button on sing-in page

---

package-lock.json
shared/asset.js
shared/estate.js
src/Map/Map.router.js
webapp/src/components/ActivityPage/Transaction/Transaction.js
webapp/src/components/EstateCard/EstateCard.js
webapp/src/components/EstateDetailPage/EditEstateMetadata/EstateModal/EstateModal.js
webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.js

Fixes #359 
This PR fixes several places where we showed estate previews on the UI and the server (`/estates/:id/map.png` endpoint).
The problem was that Estates with an even number of parcels in the X or Y axis were not center appropriately, like this:
2x1 LAND (wrong):
2x2 LAND (wrong):
3x3 LAND (ok):
With this PR it looks like this:
2x1 LAND (ok):
2x2 LAND (ok):
3x3 LAND (ok):
It also works with an arbitrary number of LAND:
This PR fixes this problem in several places were we used estate previews:
My LAND:
Transfer Estate:
Activity:
My LAND:
Transfer Estate:
Activity:

fix: center estate previews

---

src/BlockchainEvent/BlockchainEvent.model.js
src/Publication/Publication.model.js

fix: event name comparison

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/ActivityPage/Transaction/Transaction.js

fix: #356 and #358

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/Routes.js
webapp/src/components/DeleteEstatePage/DeleteEstatePage.js
webapp/src/components/EstateDetailPage/EditEstateMetadata/EstateModal/EstateModal.js
webapp/src/components/EstateDetailPage/EstateDetail.css
webapp/src/components/EstateDetailPage/EstateDetail.js
webapp/src/components/EstateDetailPage/EstateSelect/EstateSelect.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelActions/ParcelActions.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelDetail.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelOwner/ParcelOwner.css
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelOwner/ParcelOwner.js
webapp/src/components/ParcelDetailPage/ParcelDetailPage.container.js
webapp/src/components/ParcelDetailPage/ParcelDetailPage.js
webapp/src/components/TransferEstatePage/TransferEstatePage.js
webapp/src/locations.js

closes #358 #360 #362 #363 #371 #372

fix: several issues

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/ActivityPage/Transaction/Transaction.js

Closes #357 Shows estate names instead of ids in activity

show estate names

---

webapp/src/components/ParcelDetailPage/ParcelDetailPage.js

fix: fetch parcel publications when moving between parcels

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/TransferManaPage/TransferManaForm/TransferManaForm.js
webapp/src/modules/wallet/utils.js

This PR adds a warning message in the Transfer MANA screen and disables the submit button if the address entered by the user is the MANA contract address
Closes #376

feat: prevent transfering mana to contract

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/TransferAssetForm/TransferAssetForm.css
webapp/src/components/TransferAssetForm/TransferAssetForm.js
webapp/src/components/TransferEstatePage/TransferEstatePage.js
webapp/src/components/TransferParcelPage/TransferParcelPage.js

feat: show warning

---

monitor/reducers/mortgageReducer.js
shared/asset.js
src/Asset/Asset.spec.js
src/Asset/Type/type.js
src/Asset/index.js
src/Estate/Estate.router.js
src/MarketplaceEvent/MarketplaceEvent.js
src/Mortgage/Mortgage.spec.js
src/Parcel/Parcel.router.js
src/Parcel/Parcel.spec.js
src/Publication/Publication.service.js
src/Publication/Publication.spec.js
webapp/src/components/ParcelPreview/ParcelCanvas/utils.js

chore: pluralize constants

---

src/Translation/locales/fr.json

feel free to ask in discord french channel for help next time !

clean some fuzzy french translation

---

webapp/src/components/Asset/Asset.js
webapp/src/components/Parcel/Parcel.js
webapp/src/components/ParcelDetailPage/ParcelDetailPage.container.js
webapp/src/components/ParcelDetailPage/ParcelDetailPage.js
webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.js
webapp/src/modules/mortgage/sagas.js
webapp/src/modules/publication/sagas.js

First commit closes #423 and second commit closes #424 
I did some refactor to use sagas to orchestrate the fetching of additional resources instead of using the component's life cycle hooks.

fix: rollbar

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/TxStatus/TxStatusAsset/TxStatusAsset.js
webapp/src/components/TxStatus/TxStatusText/TxStatusText.js

fix: add missing translations

---

monitor/MonitorCli.js
src/BlockchainEvent/BlockchainEvent.model.js

fix: support from-block latest correctly

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json

fix: reword translation

---

shared/asset.js
webapp/src/components/EditParcelPage/EditParcelForm/EditParcelForm.js
webapp/src/components/EstateDetailPage/EditEstateMetadata/EditEstateMetadataForm/EditEstateMetadataForm.js

fix: check name/descriptions correctly

---

webapp/src/modules/estates/reducer.js

fix: remove empty estate from the state

---

webapp/src/components/EstateCard/EstateCard.css
webapp/src/components/ParcelCard/ParcelCard.css

fix: don't clip tooltips

---

webapp/src/components/ActivityPage/ActivityPage.css
webapp/src/components/EstateDetailPage/EditEstateMetadata/EditEstateMetadataForm/EditEstateMetadataForm.css
webapp/src/components/EstateDetailPage/EditEstateMetadata/EditEstateMetadataForm/EditEstateMetadataForm.js
webapp/src/components/EstateDetailPage/EditEstateMetadata/EstateModal/EstateModal.css
webapp/src/components/EstateDetailPage/EstateDetail.css
webapp/src/components/ParcelModal/ParcelModal.css

fix: mobile consistency and horizontal scroll

---

shared/parcel.js
src/Parcel/Parcel.model.js
src/Parcel/Parcel.service.js
webapp/package.json
webapp/src/lib/webworker/webworker.js
webapp/src/modules/parcels/reducer.js

fix: use all parcels to determine connections

---

webapp/src/components/BlockDate/BlockDate.js
webapp/src/components/EtherscanLink/EtherscanLink.js

fix: use anchors for external links instead of react-router <Link>

---

webapp/src/components/ParcelName/ParcelName.css

fix: parcel name in multiple lines

---

src/Translation/locales/en.json
webapp/src/components/BuyParcelByMortgagePage/BuyParcelByMortgagePage.js
webapp/src/components/Estate/Estate.container.js
webapp/src/modules/estates/sagas.js

- `locations` now are functions
- missing parcels on estate transfer

fix: locations and payload for tx

---

webapp/src/index.js
webapp/src/lib/localStorage.js
webapp/src/modules/storage/middleware.js
webapp/src/modules/storage/reducer.js
webapp/src/store.js

close #437 
We should add at the `.env` file for the webapp
`REACT_APP_LOCAL_STORAGE_KEY=decentraland-marketplace`

feat: versioning localStorage

---

webapp/src/modules/wallet/reducer.js
webapp/src/modules/wallet/sagas.js

fix #454 
IDK how to test it yet. please don't merge it

fix: rtx when buying mana

---

webapp/src/components/Footer/Footer.js

fix: footer links

---

monitor/MonitorCli.js
monitor/program.js
scripts/mktcli.js

fix: let monitor die

---

webapp/src/components/EstateDetailPage/EstateSelect/EstateSelect.js

fix: can not update an estate with one land

---

webapp/src/components/BuyManaPage/BuyManaForm/BuyManaForm.js
webapp/src/components/BuyManaPage/BuyManaPage.js
webapp/src/components/BuyParcelPage/BuyParcelPage.container.js
webapp/src/components/BuyParcelPage/BuyParcelPage.js
webapp/src/components/DeleteEstatePage/DeleteEstatePage.js
webapp/src/components/EditParcelPage/EditParcelForm/EditParcelForm.js
webapp/src/components/EstateDetailPage/EditEstateMetadata/EditEstateMetadataForm/EditEstateMetadataForm.js
webapp/src/components/EstateDetailPage/EditEstateMetadata/EstateModal/EstateModal.css
webapp/src/components/EstateDetailPage/EditEstateMetadata/EstateModal/EstateModal.js
webapp/src/components/EstateDetailPage/EstateSelect/EstateSelectActions/EstateSelectActions.js
webapp/src/components/ManageParcelPage/ManageParcelForm/ManageParcelForm.js
webapp/src/components/ParcelModal/ParcelModal.css
webapp/src/components/ParcelModal/ParcelModal.js
webapp/src/components/ParcelName/ParcelName.css
webapp/src/components/PublishPage/PublicationForm/PublicationForm.js
webapp/src/components/TransferAssetForm/TransferAssetForm.js
webapp/src/index.js
webapp/src/modules/parcels/selectors.js
webapp/src/modules/publication/selectors.js

fix: consistent tx idle and name states

---

package-lock.json
webapp/package.json
webapp/src/components/ActivityPage/ActivityPage.container.js
webapp/src/components/ActivityPage/ActivityPage.js
webapp/src/components/ActivityPage/Transaction/Status/Status.js
webapp/src/modules/authorization/reducer.js

This PR fixes a few things:
- ~Race condition on which `authorization.data` is empty (2ecb57af0c7ccefd5758860743ecbd5fac162615)~ Fixed by (23059cccbb34d89347b05d9cab3e5286bee288e5)
- Prevent calling `setState` on `Status` component after it has been unmounted due to `await` (2ecb57af0c7ccefd5758860743ecbd5fac162615)
- Fix the `CLEAR HISTORY` button (was missing the `address`) and also bump `decentraland-dapps` to `v3.4.1` which includes the `CLEAR_TRANSACTION(S)` actions in the list of actions that triggers a localStorage save (6e4b462a7b41bbd7e878a401f4150f41e9d05351)

fix: minor issues

---

webapp/src/components/Asset/Asset.js
webapp/src/components/Estate/Estate.js
webapp/src/components/Parcel/Parcel.js

feat: request estate data when navigate

---

webapp/src/components/AssetTransactionHistory/AssetTransactionHistory.css
webapp/src/components/AtlasPage/Map/Map.container.js
webapp/src/components/AtlasPage/Map/Map.js
webapp/src/components/EstateDetailPage/EstateDetail.css
webapp/src/components/EstateDetailPage/EstateDetail.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelActions/ParcelActions.js

Closes #411 
Closes #415 
Shows the amount of land in an estate, and when clicked it takes you to the atlas, highlighting that estate

feat: show land amount and link to atlas

---

webapp/src/components/ActivityPage/Transaction/Transaction.css

fix: ellipsis transactions with too much text in desktop Activity

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.css
webapp/src/components/SettingsPage/SettingsForm/SettingsForm.js

chore: new settings organization and texts

---

webapp/src/components/MarketplacePage/MarketplacePage.css
webapp/src/components/MarketplacePage/MarketplacePage.js

fix: marketplace page tabs/dropdown on mobile

---

webapp/src/modules/analytics/track.js
webapp/src/modules/estates/actions.js

Separate Segment events per asset type

fix: separate segment events per asset type

---

package-lock.json
package.json
webapp/package-lock.json
webapp/package.json

feat: bump decentraland-eth

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/ColorKeyPage/ColorKeyPage.css
webapp/src/components/ColorKeyPage/ColorKeyPage.js
webapp/src/index.css

feat: yours on sale color key

---

webapp/src/components/ActivityPage/Transaction/Transaction.css
webapp/src/components/ActivityPage/Transaction/Transaction.js

fix: activity transaction styles

---

webapp/src/modules/parcels/reducer.js

Fix reactive transaction when parcel is published

fix: rtx parcel publication

---

src/lib/asyncBatch.js

fix: don't use more than 150 items per batch

---

monitor/reducers/parcelReducer.js
sanity/doctors/EstateDoctor.js
sanity/doctors/ParcelDoctor.js
sanity/doctors/PublicationDoctor.js
src/BlockchainEvent/BlockchainEvent.model.js
src/BlockchainEvent/BlockchainEvent.queries.js
src/Marketplace/Marketplace.js
src/Publication/Publication.model.js
src/Publication/Publication.queries.js

fix: restore estate_ids on sanity

---

shared/asset.js
src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/CreateEstatePage/EditEstate/EditEstateForm/EditEstateForm.css
webapp/src/components/EditEstatePage/EditEstateMetadata/EditEstateMetadataForm/EditEstateMetadataForm.js
webapp/src/components/EditEstatePage/EditEstatePage.js
webapp/src/components/EditParcelPage/EditParcelForm/EditParcelForm.css
webapp/src/components/EditParcelPage/EditParcelForm/EditParcelForm.js
webapp/src/index.css

feat: add error message when length is exceeded

---

shared/parcel.js
webapp/src/components/EstateDetailPage/EstateDetail.js
webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelDetail.js
webapp/src/modules/analytics/track.js

- `Manage Permissions for {asset_type}` event name
- `hasTags` helper

refactor: hasTags helper and change track name for manage permission

---

scripts/mktcli.js

feat: new mkt cli

---

monitor/reducers/mortgageReducer.js
src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json

- More precision when updating mortgages
- Improve translation

fix: borrower when updating mortgages

---

.github/ISSUE_TEMPLATE.md

chore: issue template

---

webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelActions/ParcelActions.js

fix: show create estate when publication is open

---

webapp/src/components/EditParcelPage/EditParcelPage.container.js

fix: edit parcel page

---

scripts/exportToJson.js

```./scripts/exportToJson.js district --help```

feat: export to json

---

package-lock.json
package.json
scripts/mktcli.js
webapp/package-lock.json
webapp/package.json
webapp/src/modules/publication/sagas.js
webapp/src/modules/wallet/utils.js

- Support overloaded methods
We should need to test all contract interactions

Feat: decentraland-eth breaking change

---

src/Asset/Parcel/Parcel.model.js
src/Asset/Parcel/Parcel.router.js
src/Marketplace/Marketplace.js
src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/AssetPreviewHeader/AssetPreviewHeader.js
webapp/src/components/AtlasPage/Map/Map.js
webapp/src/components/AuctionPage/AuctionPage.container.js
webapp/src/components/AuctionPage/AuctionPage.css
webapp/src/components/AuctionPage/AuctionPage.js
webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.js
webapp/src/components/types.js
webapp/src/lib/api.js
webapp/src/modules/auction/reducer.js
webapp/src/modules/auction/sagas.js
webapp/src/modules/auction/selectors.js
webapp/src/modules/parcels/actions.js
webapp/src/modules/parcels/sagas.js

It's missing one thing, the map doesn't re-center when the new x,y coordinates arrive. cc: @cazala 
Also, a question, do you guys think we should decrease the amount of available parcels when the user clicks on one? or is it just me being annoying?
Closes: #669

feat: find available parcel

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/AuctionPage/AuctionPage.container.js
webapp/src/components/AuctionPage/AuctionPage.js
webapp/src/components/Modal/AuctionModal/AuctionModal.container.js
webapp/src/components/Modal/AuctionModal/AuctionModal.css
webapp/src/components/Modal/AuctionModal/AuctionModal.js
webapp/src/components/Modal/AuctionModal/index.js
webapp/src/components/Modal/BaseModal/BaseModal.css
webapp/src/components/Modal/Modal.js
webapp/src/components/Modal/TermsModal/TermsModal.js
webapp/src/themes/components/Button.css

feat: auction welcome modal

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/AuctionPage/AuctionPage.css
webapp/src/components/AuctionPage/AuctionPage.js
webapp/src/components/MarketplacePage/MarketplacePage.css
webapp/src/components/Modal/AuctionModal/AuctionModal.js
webapp/src/modules/auction/utils.js

Sorry about the messy history, the files changed should be ok. I had to skip a huge rebase
Closes: #616

feat: auction empty page

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/Modal/AuctionModal/AuctionModal.js

chore: updated copy

---

monitor/reducers/auctionReducer.js
package-lock.json
package.json
webapp/package-lock.json
webapp/package.json

Reverts decentraland/marketplace#717

Revert "feat: update bidSucessful args"

---

webapp/src/components/AuctionPage/AuctionPage.css
webapp/src/components/AuctionPage/AuctionPage.js
webapp/src/components/AuctionPage/Token/Token.css
webapp/src/components/Footer/Footer.css
webapp/src/components/Page/Page.css
webapp/src/themes/variables.css

I don't think it completely closes #696 but it's a start
I did some nasty stuff in this PR I know 🙈 🕙 🔥

style: first iteration in mobile support

---

webapp/src/components/AuctionPage/AuctionPage.css
webapp/src/components/AuctionPage/AuctionPage.js

fix: max land warning on mobile

---

webapp/src/components/AuctionCountdown/AuctionCountdown.css
webapp/src/components/HomePage/HomePage.css

Fixes #740 
without banner
with banner

fix: homepage on tablet/mobile

---

webapp/src/components/AuctionPage/AuctionPage.js
webapp/src/components/Modal/AuctionModal/AuctionModal.css
webapp/src/components/Modal/AuctionModal/AuctionModal.js
webapp/src/modules/auction/utils.js

feat: update video link

---

webapp/src/components/HomePage/HomePage.container.js
webapp/src/modules/analytics/track.js
webapp/src/modules/auction/actions.js
webapp/src/modules/auction/sagas.js

feat: auction track

---

monitor/reducers/auctionReducer.js
package-lock.json
package.json
webapp/package-lock.json
webapp/package.json

We should wait until a new contract deployment

Feat: update land auction events params

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/AuctionCountdown/AuctionCountdown.container.js
webapp/src/components/AuctionCountdown/AuctionCountdown.js
webapp/src/components/AuctionCountdown/index.js
webapp/src/components/HomePage/HomePage.container.js
webapp/src/components/HomePage/HomePage.js

Closes #741
This PR makes the countdown refresh the page when it reaches zero. Also I added a state for when the auction is already started and another one for when it has finished. This is for the homepage (so the banner doesn't disappear).

feat: added banner for started and finished auction

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/Footer/Footer.css
webapp/src/components/Footer/Footer.js

feat: add code of ethics

---

webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelDetail.js
webapp/src/modules/location/selectors.js

feat: colorKey as modal

---

webapp/src/components/MarketplacePage/utils.js

fix: translation at dropdown

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json

Change `Gas price` to `Max gas price`

chore: gas price translation

---

webapp/src/components/Navbar/Navbar.js
webapp/src/modules/wallet/utils.js

- Hide `auction` menu item at the navbar
- Always connect LANDAuction contract for the activity page

fix: auction ff

---

src/Tile/Tile.model.js
webapp/src/modules/estates/selectors.js
webapp/src/modules/tile/reducer.js

fix: iterate over tiles

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/HomePage/HomePage.css

chore: updated hero subtitle

---

webapp/src/components/Footer/Footer.js

Update FAQ link as requested by Mat

fix: FAQ link

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/SignInPage/SignInPage.js

chore: add Trust Wallet to suggested

---

monitor/reducers/estateReducer.js
src/Tile/Tile.model.js

Update tiles owner when transferring an Estate

fix: update owner when transfer an estate

---

shared/mortgage.js
shared/publication.js

Show expired mortgages so the user can cancel them

fix: expired mortgages

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/AcceptBidAssetPage/AcceptBidAssetPage.js
webapp/src/components/AcceptBidAssetPage/AcceptBidEstatePage/AcceptBidEstatePage.js
webapp/src/components/AcceptBidAssetPage/AcceptBidParcelPage/AcceptBidParcelPage.js
webapp/src/components/EditEstatePage/EstateSelect/EstateSelect.css
webapp/src/modules/wallet/utils.js

Check bidder MANA balance when accepting a bid to mitigate transactions failure

Feat: check bidder balance

---

monitor/reducers/bidReducer.js
webapp/src/components/Bid/Bid.css
webapp/src/components/Bid/Bid.js
webapp/src/components/BidCard/BidCard.css
webapp/src/components/BidCard/BidCard.js
webapp/src/components/BidCard/index.js
webapp/src/components/ProfilePage/ProfilePage.css
webapp/src/components/ProfilePage/ProfilePage.js
webapp/src/modules/wallet/utils.js

Feat: bid detail

---

shared/listing.js
webapp/src/components/AcceptBidAssetPage/AcceptBidAssetPage.container.js
webapp/src/components/BidAssetPage/BidAssetPage.container.js
webapp/src/components/CancelBidAssetPage/CancelBidAssetPage.container.js
webapp/src/components/EstateDetailPage/EstateActions/EstateActions.js
webapp/src/components/ParcelDetailPage/ParcelActions/ParcelActions.js
webapp/src/components/PublishAssetForm/PublishAssetForm.css
webapp/src/components/PublishAssetForm/PublishAssetForm.js
webapp/src/modules/location/selectors.js

- Go Back when click on cancel on bid modals
- Place, Accept and Cancel Bid are missing the back button
- `price` to `Price` when listing an asset
- Asset detail button orders and types

Feat: bid fix design

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/Bid/Bid.js
webapp/src/components/BidAssetPage/BidAssetPage.container.js
webapp/src/components/Modal/FatfingerModal/FatfingerModal.js
webapp/src/components/PublishEstatePage/PublishEstatePage.container.js
webapp/src/components/PublishParcelPage/PublishParcelPage.container.js

- The fatfinger modal says "publish" instead of "bid". This also happens when I update the bid.
- The label should say either "Parcel" or "Estate" instead of "ERC721"
- Missing accepted price unit

Fix: bid internal testing

---

webapp/src/components/AcceptBidAssetPage/AcceptBidEstatePage/AcceptBidEstatePage.js
webapp/src/components/AcceptBidAssetPage/AcceptBidParcelPage/AcceptBidParcelPage.js
webapp/src/components/Bid/Bid.js
webapp/src/components/BidAssetPage/BidAssetForm.js
webapp/src/modules/address/reducer.js

Feat: bids small fixes

---

webapp/src/modules/address/sagas.js

If you bid directly by the contract you can bid empty estates.
This PRs will hide that bids

fix: bids empty estates

---

shared/listing.js
shared/map/TileType.js
shared/parcel.js
src/Tile/Tile.model.js
src/Tile/TileAttributes.js
webapp/src/components/ParcelDetailPage/ParcelActions/ParcelActions.js
webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.js

Hide `bid` button when the parcel is part of an estate

feat: check if parcel is part of an estate

---

scripts/maintenance/index.html
src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json

feat: update copyright

---

src/Translation/locales/en.json
src/Translation/locales/es.json
src/Translation/locales/fr.json
src/Translation/locales/ja.json
src/Translation/locales/ko.json
src/Translation/locales/zh.json
webapp/src/components/BidAssetPage/BidAssetPage.js
webapp/src/components/BuyParcelPage/BuyParcelPage.js

feat: show connect if user is logged out

---

package.json
scripts/restoreDump.js

Run it like this:
```
npm run restore-dump '/absolute/path/to/dump.sql'
```
⚠️ it **WILL** DROP and reCREATE your database if the dump file exists

feat: restore dump script

---

sanity/SanityActions.js
sanity/doctors/Diagnosis.js
sanity/doctors/EstateDoctor.js
sanity/doctors/ParcelDoctor.js
sanity/doctors/PublicationDoctor.js
sanity/program.js
src/Asset/Estate/Estate.model.js
src/BlockchainEvent/BlockchainEvent.model.js
src/BlockchainEvent/BlockchainEvent.queries.js

Sanitize getting events from`latest - N` to latest blocks. This will make the sanity process faster

Feat: sanitize from block

---

webapp/public/manifest.json

fix: favicon dimension

---

monitor/reducers/estateReducer.js

fix: update Estate metadata

---

src/Asset/Parcel/Parcel.model.js
src/Asset/Parcel/Parcel.router.js

`GET /parcels/:x/:y/encodedId`
```json
{"ok":true,"encoded_id": "0xffffffffffffffffffffffffffffffd0ffffffffffffffffffffffffffffffe3"}
```
`GET /parcels/:tokenId`
```json
{
"ok": true,
"data": {
"id": "-48,-29",
"x": -48,
"y": -29,
"auction_price": 2443,
"district_id": null,
"owner": "0xdeadbeeffaceb00c",
"data": {
"version": 0,
"name": "My Parcel",
"description": "My parcel is awesome",
"ipns": ""
},
"auction_owner": "0xdeadbeeffaceb00c",
"tags": {
"proximity": {
"plaza": {
"district_id": "55327350-d9f0-4cae-b0f3-8745a0431099",
"distance": 2
},
"road": {
"district_id": "f77140f9-c7b4-4787-89c9-9fa0e219b079",
"distance": 0
}
}
},
"last_transferred_at": null,
"in_estate": false
}
}
```

feat: add encode and decode parcel id endpoints

---

sanity/doctors/Doctor.js
sanity/doctors/EstateDoctor.js
sanity/doctors/ParcelDoctor.js

- Sanitize Asset `updateOperators` and `operators`

feat: sanitize assets operators

---

sanity/SanityActions.js
sanity/doctors/ApprovalDoctor.js
sanity/doctors/Diagnosis.js
sanity/doctors/index.js
src/BlockchainEvent/BlockchainEvent.model.js

The code can be reviewed, tests are pending (blocked from dev VPN 😢)

feat: sanitize approvals
