decentraland/marketplace

webapp/src/components/HomePage/Sidebar/Sidebar.container.js, webapp/src/modules/address/sagas.js, webapp/src/modules/parcels/actions.js, webapp/src/modules/parcels/reducer.js, webapp/src/modules/ui/map/sagas.js
This keeps the decentraland logo in loader mode if there are pending requests to `GET /parcels`, before this, if the user dragged the map for a while, say, for 4 times, 4 requests would be sent, but as soon as the first request comes back that would unset the loader.
I changed the boolean `loading` prop to `loading_count` and made each `FETCH_PARCELS_REQUEST` increment it, and each `FETCH_PARCELS_FAILURE` or `FETCH_PARCELS_SUCCESS` decrement it.
We were using `FETCH_PARCELS_SUCCESS` to merge the addresses returned by `/addresses/:address/parcels` into the state, but this was screwing up the `loading_count`, so I added a new `MERGE_PARCELS` action that merges them into the app state without touching the count.
=> [fix] Show loader if there are pending requests to GET /parcels

webapp/src/components/HomePage/Sidebar/CollapsedSidebar/CollapsedSidebar.css
moved color codes button up so it doesnt overlap with intercom
=> [fix] moved color codes button up so it doesnt overlap with intercom

webapp/src/locations.js, webapp/src/modules/location/sagas.js
Prevent firing multiple `"Navigate to url"` actions to the same url. It happens for example when you go to the atlas page from a parcel detail page, then you have to click "back" three times in order to go to the previous page. It also happens inside the atlas map, if you drag the map three times and you click back it should take you to the previous position, but sometimes you have to click back several times. After this change it works ok.
=> [Fix] Prevent navigating to the current location

webapp/src/components/BuyParcelPage/BuyParcelPage.js
Simplified the message, looks like this:
=> fix: Remove un-used translation

webapp/src/components/Footer/Footer.css, webapp/src/index.css
This fixes the position and size of the Intercom launcher on the footer. ~The background color needs to be set to `#202433` from the Interdom's admin panel.~ [Done](https://github.com/decentraland/marketplace/pull/109#issuecomment-374010077).
=> fix: intercom position and size

src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/src/components/ColorKeyPage/ColorKeyPage.js, webapp/src/lib/parcelUtils.js
Fixed a broken tranlsation in Chinese (`transaction.approved`) and another one in Korean (`atlas.owner`) and added missing translations on atlas page and color key.
=> chore: fixed and added missing translations

webapp/src/components/MarketplacePage/MarketplacePage.js, webapp/src/lib/parcelUtils.js
This PR makes the page go back to 1 when sorting on the Marketplace page.
Also it improves the contrast of the text on the Genesis Plaza tooltips (black over green instead of white over green).
=> fix: reset page when sorting

webapp/src/components/AtlasPage/Map/ParcelsMap/ParcelsMap.js
This PR prevents the two most commons rollbar errors:
```
TypeError: Cannot read property 'classList' of undefined
1
File "../node_modules/leaflet/dist/leaflet-src.js" line 2654 col 1 in me
if (el.classList !== undefined) {
2
File "../node_modules/leaflet/dist/leaflet-src.js" line 4489 col 1 in n._onPanTransitionEnd
removeClass(this._mapPane, 'leaflet-pan-anim');
3
File "../node_modules/leaflet/dist/leaflet-src.js" line 593 col 1 in n.fire
l.fn.call(l.ctx || this, event);
4
File "../node_modules/leaflet/dist/leaflet-src.js" line 2965 col 1 in n._complete
this.fire('end');
5
File "../node_modules/leaflet/dist/leaflet-src.js" line 2943 col 1 in n._step
this._complete();
6
File "../node_modules/leaflet/dist/leaflet-src.js" line 2932 col 1 in n._animate
this._step();
```
and this:
``` …
```
=> fix: safeguard against undefined reference in leaflet _onPanTransitionEnd

webapp/src/components/AtlasPage/Map/Map.container.js
Every url that has to two parts, like `addressStats/0x1234`, will end up matching our `/:x/:y` route, and our map is going to try to use those parts as coords, and converting `"addressStats` to number thru a parseInt will end up in NaN, which is what's causing [rollbar issue 330](https://rollbar.com/decentraland/Marketplace/items/330/?item_page=0&#instances)
This fixes the problem for any url that has two parts and one (or both) of them is NaN
=> fix: broken redirect

scripts/translate.js, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json
Tests on master are not working cause there are extra keys on non-default locales.
When keys on `en.json` are deleted and translate script is executed it only adds new keys to other locales but doesn't delete extra ones.
This PR adds the clean functionality.
=> chore: clean extra translations

shared/asset.js, shared/mortgage.js, webapp/config/webpack.config.dev.js, webapp/config/webpack.config.prod.js, webapp/package-lock.json, webapp/package.json, webapp/src/lib/webworker/WebWorkerFactory.js, webapp/src/lib/webworker/webworker.js, webapp/src/modules/mortgage/sagas.js
The production build is currently broken with a runtime error `Reference Error: exports is not defined`.
This is because `webpack.optimize.UglifyJsPlugin` fails to minify correctly the dependency `decentraland-eth`. I couldn't figure out why, I tried compiling `decentraland-eth` with both `tsc` and `babel` using `es2017` and `es5` and also tried exporting it as `commonjs`, `umd` and `amd` and the problem persisted on all the attempts.
This PR fixes it by introducing the following changes:
- Stopped using `webpack.optimize.UglifyJsPlugin` (this also allowed me to stop using `babel-loader` for `decentraland-eth` and `web3-provider-engine`)
- Minified the bundle in a `postbuild` step using `uglify-es`. This minifier works fine with `decentraland-eth` but screws up our WebWorker bundler …
=> fix: build

shared/map/render/Map.js, webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.js
The marketplace is now showing wallet parcels on red
=> fix: add missing wallet parameter to MapRenderer on ParcelCanvas

.vscode/settings.json
If you find on all files of the project with VSCode you will get triplicates results if found on shared folder because we know have symlinks on src paths.
=> chore: avoid vscode searchs on symlinks

webapp/src/components/HomePage/HomePage.css
This PR fixes two things in the homepage:
- After adding the tutorial link, the footer started to show up below the fold, adding a scrollbar to the full page when it should not have scroll.
- After the refactor around `.ParcelCard` the "Newest LAND" slider started to have a vertical scrollbar that should not be there.
Here's a GIF of what's in production now and how this PR fixes it:
=> fix: homepage scroll

webapp/src/components/Parcel/Parcel.js
This PR changes the `<Parcel>` component to show the `<Loading>` spinner only if it needed to be connected to Ethereum to determine wether the `children` is accessible or not. 
This makes the `ParcelDetailPage` render right away while connecting, but it doesn't change the behaviour of other pages like `BuyParcelPage`, `TransferParcelPage` or any of those that use the `ownerOnly` prop.
=> fix: prevent showing spinner if it's not needed

docs/http-api.md, migrations/1519215027247_publications-add-status-buyer-owner.js, migrations/1526295211848_publications-add-asset-support.js, migrations/1527536462876_mortgage-create.js, scripts/monitor/processEvents.js, scripts/sanityCheck.js, scripts/seed.js, src/Asset/Asset.js, src/Asset/Asset.router.js, src/Contribution/Contribution.router.js, src/District/District.router.js, src/Estate/Estate.router.js, src/Map/Map.router.js, src/Mortgage/Mortgage.model.js, src/Mortgage/Mortgage.router.js, src/Parcel/Parcel.router.js, src/Publication/Publication.model.js, src/Publication/Publication.queries.js, src/Publication/Publication.router.js, src/Publication/PublicationRequestFilters.js, src/Translation/Translation.router.js, src/server.js, webapp/src/lib/api.js
In this PR I added a `docs/http-api.md` file with some documentation for our HTTP API (Mortgages docs are still missing) 
I made a few fixes and changes along the way:
- Removed the duplicated static constants `Publication.STATUS`, `Publication.TYPES`, `Mortgage.STATUS` and `Mortgage.TYPES`
- Added default values to the `PublicationRequestFilter`'s parameters and allowed requests
- Added support for requests without a `status` param
=> chore: HTTP API docs

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/modules/analytics/track.js, webapp/src/modules/transaction/sagas.js
This PR increases the timeout for transactions to be considered dropped from 30 seconds to ~5 minutes~ 2 minutes ([.getConfimedTransaction](https://github.com/decentraland/decentraland-eth/blob/master/src/ethereum/txUtils.ts#L28) default is [15 retries](https://github.com/decentraland/decentraland-eth/blob/master/src/ethereum/txUtils.ts#L74) every [2 seconds](https://github.com/decentraland/decentraland-eth/blob/master/src/ethereum/txUtils.ts#L12), I changed it to ~150~ 60 retries). 
I also bumped `decentraland-eth` to `v3.4.0` which sends a different error message for dropped transactions instead of sending the same as when it actually fails.
Finally I also added the `error.message` from failed transactions to the "Transaction Failed" events in Segment, so we can easily filter dropped …
=> fix: dropped tx

docs/http-api.md, src/Map/Map.router.js, src/Parcel/Parcel.router.js, src/lib/index.js, src/lib/unsafeParseInt.js, webapp/src/components/ParcelTags/ParcelTags.css, webapp/src/lib/api.js, webapp/src/modules/parcels/sagas.js
This PR improves de HTTP API documentation (more importantly it adds the missing `/map` endpoint), refactors a little bit the way we use the API so it makes more sense (like I stopped fetching single parcels like `/parcels?nw=x,y&se=x,y` and doing `/parcels/:x/:y` instead) and fixes a mobile issue with the highlights:
before:
after:
**IMPORTANT**
**I did not remove any functionality** from the API, so folks using our API like `/parcels?nw=x,y&se=x,y` can still do so, but I just didn't add that to the docs to discourage misuse and added the preferred `/parcels/:x/:y` for that purpose
=> chore: tech debt

package-lock.json, package.json
Bump `newrelic` to avoid a potential security vulnerability from one of its dependencies: `https-proxy-agent@0.3.6`
=> chore: bump newrelic

shared/estate.js, webapp/src/components/EstateDetailPage/EstateDetail.js, webapp/src/components/EstateDetailPage/EstateSelect/EstateSelect.js
Fixes #386 
The current implementation of `areConnected` used to determine if all the parcels in an Estate are connected is broken:
I replaced that implementation with an equivalent that uses graph theory to determine if all the parcels are connected: do depth first search to travel the graph and collect all the visited nodes, if all the parcels in the estate are visited it means they are all connected.
This is the result:
=> fix: unconnected estates

shared/parcel.js
Closes #388
Adjacent estates from different owners were shown as one single estate:
This PR fixes that:
=> fix: show adjacent estates separated

src/Estate/Estate.router.js, src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ja.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/src/components/ActivityPage/Transaction/Transaction.js, webapp/src/components/Asset/Asset.js, webapp/src/components/DeleteEstatePage/DeleteEstatePage.js, webapp/src/components/Estate/Estate.container.js, webapp/src/components/EstateDetailPage/EstateDetail.css, webapp/src/components/EstateDetailPage/EstateDetail.js, webapp/src/components/EstateDetailPage/EstateDetailPage.js, webapp/src/components/EstateDetailPage/EstateSelect/EstateSelect.js
Closes #384 
Currently empty (aka deleted) estates show a broken page (only navbar and footer, and footer is _en cualquiera_)
This PR adds a screen for empty estates:
=> fix: handle empty estate

shared/estate.js, src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ja.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/src/components/DeleteEstatePage/DeleteEstatePage.js, webapp/src/components/EstateDetailPage/EstateSelect/EstateSelect.js
Closes #385 
This shows a warning if a single transaction reaches the limit of parcels, which is 12, ie: adding 12 parcels or removing 12 parcels. This doesn't mean 12 "modifications", because you can still add 10 parcels and remove 10 parcels in the same edition (since those are done in two different transactions).
This is an screenshot of how it looks like:
This limit also applies when the user tries to dissolve an estate that is too big:
=> feat: limit maximum parcels per transaction

shared/parcel.js, webapp/src/lib/webworker/WebWorkerOnMessage.js, webapp/src/modules/parcels/reducer.js
This fixes the race condition that caused you to become the king of decentraland
Basically the change that made `toParcelObject` return all the parcels in the state instead of just the ones in `parcelArray` was making the `FETCH_ADDRESS_PARCELS_REQUEST` case in the WebWorker to return all the parcels in the state in the `FETCH_ADDRESS_PARCELS_SUCCESS` action.
I reverted this change that was only to avoid some loops in a few cases of the parcel reducer and the bug vanishes.
=> fix: own all the landz

webapp/src/lib/localStorage.js, webapp/src/modules/estates/actions.js, webapp/src/modules/estates/utils.js, webapp/src/modules/transaction/sagas.js, webapp/src/modules/transaction/utils.js
Remove `receipt` from old `transactions` and save `receipt` on demand. In this PR for `createEstate` action
=> feat: migrate ls v2

shared/mortgage.js
- Use `Date.now()` instead of `new Date.getTime()`
- Wrong math when checking if mortgage is defaulted
=> Fix: defaulted mortgage

webapp/package-lock.json, webapp/package.json
Bumped `decentraland-dapps`. This fixes the bug that caused dropped transactions to be repeated in the app state.
=> chore: bump decentraland-dapps to v3.4.2

webapp/src/lib/webworker/WebWorkerOnMessage.js, webapp/src/modules/address/sagas.js, webapp/src/modules/estates/reducer.js, webapp/src/modules/map/sagas.js
This PR fixes a bug in the branch `fix/list-estates` that causes the publications of Estates fetched by the `FETCH_MAP_REQUEST` to be left out of the app state. This resulted in Estate publications not showing up in the Atlas or in the EstateDetail page.
=> fix: estate publications on map

webapp/src/index.css
Fixes #520 
Removes the whilte line that appears in the `/marketplace` page between the table and the footer
=> fix: white line on footer

webapp/src/components/TxStatus/TxStatusAsset/utils.js
Fixes #514 
When there's any pending transaction that is neither from a parcel nor an estate (ie authorizing the marketplace) the `payloadAssetId` in [this line](https://github.com/decentraland/marketplace/blob/master/webapp/src/components/TxStatus/TxStatusAsset/utils.js#L7) is `undefined`, and so is the `asset.id` from an Estate the the user is creating (since it hasn't been created yet it doesn't have an id). So [this condition](https://github.com/decentraland/marketplace/blob/master/webapp/src/components/TxStatus/TxStatusAsset/utils.js#L11) end up being `undefined === undefined` triggering the warning message.
This PR fixes that.
=> fix: prevent showing the TxStatusAsset component when creating a new Estate

shared/estate.js, webapp/src/components/ActivityPage/Transaction/Transaction.js
Fixes #516 
The current implementation of `calculateMapProps` returns `>1` zoom levels for small estates. This causes them to be too zoomed in, and it looks bad when shown next to regular parcels.
Like this:
This PR makes the zoom level to never go above 1, so they look like this:
It also changes the formula for zoom level to be `(x + y) / (x * y)` which works nicer for regular sized estates, this is a 2x1 estate followed by a 5x3 estate followed by a single parcel:
It keeps the old zoom formula for disproportioned estates (with way more parcels in one axis than the other) because it works better for those scenarios (like [this one](https://market.decentraland.org/estates/38/detail))
=> fix: prevent estates from being zoomed in

webapp/src/components/ActivityPage/ActivityPage.js, webapp/src/components/Estate/Estate.container.js, webapp/src/components/HomePage/HomePage.js, webapp/src/components/MarketplacePage/MarketplacePage.container.js, webapp/src/components/MarketplacePage/MarketplacePage.css, webapp/src/components/MarketplacePage/MarketplacePage.js, webapp/src/components/MarketplacePage/utils.js, webapp/src/components/Navbar/Navbar.js, webapp/src/components/ProfilePage/ProfilePage.container.js, webapp/src/lib/Location.js, webapp/src/lib/api.js, webapp/src/locations.js, webapp/src/modules/publication/actions.js, webapp/src/modules/publication/sagas.js, webapp/src/modules/publication/utils.js, webapp/src/modules/ui/marketplace/reducer.js, webapp/src/modules/ui/marketplace/selectors.js
This PR refactors the `tab` into a query param `asset_type`. 
This keeps it consistent with the server API, and it lets us use the logic already implemented in the `Location` class to build paths and extract values from the router.
Also it allow us to have a single route for the marketplace (no need for `marketplaceDefaultPage` location)
This PR also refactores the MarketplacePage to work with `assets` instead of `parcels` and `estates`, which reduces repeated logic. 
This PR also fixes a race condition that happened when the MarketplacePage was mounted and the publications for each asset type were fetched: now it relies on the router instead of the order that the actions are dispatched.
=> refactor: marketplace

shared/asset.js, shared/mortgage.js, shared/utils.js, webapp/src/components/Asset/Asset.container.js, webapp/src/components/EstateCard/EstateCard.container.js, webapp/src/components/EstateDetailPage/EstateDetailPage.container.js, webapp/src/components/ParcelCard/ParcelCard.container.js, webapp/src/components/ParcelDetailPage/ParcelDetailPage.container.js, webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.container.js, webapp/src/components/TransferParcelPage/TransferParcelPage.container.js, webapp/src/modules/address/selectors.js, webapp/src/modules/estates/selectors.js, webapp/src/modules/mortgage/selectors.js, webapp/src/modules/parcels/selectors.js, webapp/src/modules/publication/selectors.js, webapp/src/modules/ui/marketplace/selectors.js
Fixes #541
When a publication had a transaction status different than `confirmed` the `isOpen` helper would return `false` causing several parts of the UI to be rendered wrong (like empty For Sale tab in profile, or publications without price).
=> fix: publications with a wrong tx status were shown as not open

webapp/src/components/PublishEstatePage/PublishEstatePage.container.js, webapp/src/components/PublishParcelPage/PublishParcelPage.container.js, webapp/src/modules/analytics/track.js, webapp/src/modules/publication/sagas.js
Now when we send a tx related to a publication, it fails because `assetType` is `undefined`
=> fix: get asset type

webapp/package-lock.json, webapp/package.json
This PR bumps `decentraland-dapps` to version `3.6.0`, which watches reverted transactions for up to an hour and if the transaction is found to be confirmed, it updates its status.
This is because sometimes transactions are found to be reverted at first when they get mined (because they have a `blockNumber` in their tx status but no receipt). This happens more often in mainnet.
Checkout this branch, cd into webapp and npm install, then run this code at the console to turn your confirmed transactions into reverted ones:
```js
const storage = JSON.parse(localStorage['decentraland-marketplace'])
storage.transaction.data.forEach(tx => {
if (tx.status === 'confirmed') {
tx.status = "reverted"
tx.timestamp = Date.now() - 1000
}
})
localStorage['decentraland-marketplace'] = …
```
=> fix: bump decentraland-dapps, fixes failed transactions bug

webapp/src/modules/mortgage/sagas.js
When dispatching `FETH_PARCEL_SUCESS` take the latest but take every `FETCH_ACTIVE_MORTGAGE_PARCELS` actions in order to have the same number of request than success or failed
=> fix: mortgage saga

src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ja.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/src/components/ActivityPage/Transaction/Status/Status.js
Fixes #561 (sort of)
Since we don't store the number of confirmations in the app state, we always have to fetch them to know if a transaction's status is `Accepted` or `N confirmations`. 
I removed the `Waiting for confirmations...` placeholder that shows while we fetch the confirmations. This causes the status to just "appear" when we know the amount of confirmations, but I think it's better than showing the placeholder for a fraction of a second.
Any better ideas?
=> fix: remove "Waiting for confirmations" to prevent flickering

webapp/src/components/EstateDetailPage/EstateDetail.css, webapp/src/components/EstateDetailPage/EstateDetail.js, webapp/src/components/ParcelAttributes/ParcelAttributes.js
Close #583 
- Remove tags from `Parcels included` section 
- Show highlights
I kept the tags from parcel when you edit the Estate's parcels just a way to show the user the attributes of the parcels to be included
=> feat: add estate highlights

webapp/package-lock.json, webapp/package.json, webapp/src/components/SignInPage/SignInPage.js
This PR bumps `decentraland-dapps` to `v3.8.0` which adds support for EIP-1102
I also changed the redirection of the "Sign In" page after signing in, because it used to take you to the"Settings" page, which only has one button to "go back", and it takes you to the "Sign In" page again, which takes you back to the "Settings" page, which only has one button to "go back", and it takes you to you to the "Sign In" page again.. and so forth :P
=> feat: added support for EIP-1102

webapp/package-lock.json, webapp/package.json, webapp/src/modules/analytics/track.js
Currently we are tracking reverted and dropped transactions. Some of the dropped transactions end up being replaced, and some of the reverted transactions are false positives that end up being accepted ("fixed transactions"). We are not keeping track of these scenarios so our analytics show that we have more failures than we actually do.
This PR adds those events to our analytics.
=> chore: track fixed and replaced transactions

webapp/package-lock.json, webapp/package.json
Bump `decentraland-dapps` to `v3.8.2`. This version makes the `Fix Reverted Transaction` action to trigger a `STORE_SAVE` event, saving the state to localStorage. Otherwise fixed transactions are lost when the user refreshes the page (and they are fixed again, so the user doesn't notice, but this screwed up our analytics metrics since we had more Fixed Transaction events than Failed Transaction ones).
=> chore: bumped decentraland-dapps

webapp/src/components/BuyManaPage/BuyManaForm/utils.js
Using the `minimumReturn` feature of Bancor's API started to throw `invalid args` errors on their end since last week. I'm disabling the feature until we hear back from them (it's still possible to convert ETH to MANA without it).
=> fix: disable Bancor minimum return (it breaks their API)

scripts/mktcli.js
It's not trying to be 100% complete with the descriptions
=> feat: show new events and fetch correctly

shared/asset.js, shared/district.js, shared/map/Tile.js, shared/map/index.js, shared/map/render/Map.js, shared/map/render/Parcel.js, shared/map/tile.js, webapp/src/components/Asset/Asset.js, webapp/src/components/AssetDetailPage/AssetDetailPage.container.js, webapp/src/components/AssetLoader/AssetLoader.container.js, webapp/src/components/AtlasPage/Map/Map.container.js, webapp/src/components/AuctionPage/AuctionPage.js, webapp/src/components/EditEstatePage/EstateSelect/EstateSelect.js, webapp/src/components/NotFound/NotFound.css, webapp/src/components/NotFound/NotFound.js, webapp/src/components/NotFound/index.js, webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelDetail.js, webapp/src/components/ParcelDetailPage/ParcelDetail/ParcelOwner/ParcelOwner.js, webapp/src/components/ParcelPreview/ParcelCanvas/ParcelCanvas.js, webapp/src/components/ParcelPreview/ParcelCanvas/utils.js, webapp/src/components/ParcelTags/ParcelTags.js, webapp/src/modules/estates/sagas.js, webapp/src/modules/estates/selectors.js
This PR fixes the map rendered, the click handler and the popup for estates that are deployed within districts (this includes plazas and roads)
Here are some queries to insert estates inside a plaza, a road and a district:
Insert an estate in Genesis Plaza (-4, 8)
```sql
INSERT INTO estates (id, owner, data, last_transferred_at, created_at, updated_at, tx_hash, token_id) VALUES ('9000', '0xfa5ad346a73fcd3defa42c694a710fe3c3dc6405', '{"ipns": "", "name": "TEST", "version": 0, "description": "", "parcels": ""}', 1541071498000, now(), now(), '0xdeadbeef', '9000');
UPDATE parcels SET estate_id = '9000' WHERE id IN ('-4,8', '-4,7');
UPDATE estates E SET data = jsonb_set(
data,
'{parcels}',
(SELECT json_agg(json_build_object('x', P.x, 'y', P.y)) FROM parcels P WHERE P.estate_id = E.id)::jsonb
) …
```
=> fix: estates within districts

src/Translation/locales/en.json, src/Translation/locales/es.json, webapp/src/components/ActivityPage/ActivityPage.container.js, webapp/src/components/ActivityPage/Transaction/Transaction.js, webapp/src/modules/auction/actions.js, webapp/src/modules/auction/sagas.js, webapp/src/modules/parcels/reducer.js
=> feat: use and show gas limit correctly. Fix tx

migrations/1542390528670_parcels-add-auction-timestamp.js, migrations/1542628449294_parcels-populate-auction-timestamp.js, monitor/reducers/auctionReducer.js, monitor/reducers/index.js, scripts/addAuctionTimestamp.sql, scripts/initDb.js, shared/parcel.js, src/Asset/Asset.js, src/Asset/Parcel/Parcel.model.js, src/Marketplace/Marketplace.spec.js, src/Mortgage/Mortgage.model.js, src/Publication/Publication.model.js, src/ethereum/index.js, webapp/src/components/AssetTransactionHistory/AssetTransactionHistory.js, webapp/src/components/ParcelCard/ParcelCard.js
requires a migrate up!
Closes #612
=> feat: handle auction bid success event

webapp/src/components/Page/Page.container.js, webapp/src/components/Page/Page.js, webapp/src/modules/location/selectors.js
This prevents showing the marketplace tos modal on the `/auction`, this is to prevent users from seeing 2 modals if it's the first time they arrive to the marketplace, and they land on the auction page.
They will still see it if they navigate to the rest of the marketplace. 
We could include the market tos into the auction modal checkbox as well if needed.
=> feat: prevent showing market tos in auction

src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, webapp/src/components/AuctionPage/AuctionPage.container.js, webapp/src/components/AuctionPage/AuctionPage.js, webapp/src/components/Modal/BidConfirmationModal/BidConfirmationModal.container.js, webapp/src/components/Modal/BidConfirmationModal/BidConfirmationModal.js, webapp/src/components/SignInPage/WalletIcon.js, webapp/src/modules/auction/actions.js, webapp/src/modules/auction/reducer.js, webapp/src/modules/auction/sagas.js, webapp/src/modules/auction/selectors.js
This PR does a bunch of things:
+ defers the update of the owner of the selected parcel so it can be rendered as selected right away
+ refresh the owners of the selected parcels every 10 seconds (configurable)
+ removes sold parcels from the actual purchase (they are deducted from the total of parcels and the total price)
As you can see in this screen recording, the user can select parcels right away, and some of them change to "sold" status after selecting them. They are not accounted for the total price and total LAND amount. They still show up on the list to let the user know that those parcels have been sold, and the user can click on them to remove them from the list (either by clicking the X on the corner of the chip, or by clicking on the tile on the map). Once they are removed …
=> feat: defer update of the owner, update owners of selection, remove sold parcels from actual purchase

webapp/src/components/AuctionCountdown/AuctionCountdown.css, webapp/src/components/AuctionSplash/AuctionSplash.css, webapp/src/components/AuctionStaticPage/AuctionStaticPage.css, webapp/src/components/AuctionStaticPage/AuctionStaticPage.js, webapp/src/components/Countdown/Countdown.css
This fixes the auction coundown on mobile
before:
after:
=> fix: mobile support

src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ja.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/src/components/Modal/AuctionModal/AuctionModal.css, webapp/src/components/Modal/AuctionModal/AuctionModal.js
Closes #743 
Users who haven't accepted Decentraland's Terms of Service and Privacy Policy will see this checkbox instead of the one that only links to the Auction terms:
And by checking and confirming that modal they won't see the other ToS modal on the rest of the marketplace.
=> feat: accept all terms from auction modal

webapp/src/components/AuctionPage/AuctionPage.js
This also removes the `+ -` buttons, if it's not a good enough tradeoff we can close this issue without merging
Closes #719
=> feat: remove re-center button on mini-map

migrations/1550588222674_estates-add-district-id.js, monitor/consolidateProccesedEvents.js, monitor/reducers/bidReducer.js, shared/district.js, shared/listing.js, shared/parcel.js, src/Asset/Estate/Estate.model.js, webapp/src/components/EditEstatePage/EstateSelect/EstateSelect.container.js, webapp/src/components/EstateDetailPage/EstateActions/EstateActions.js, webapp/src/components/EstateDetailPage/EstateDetailPage.container.js, webapp/src/components/EstateDetailPage/EstateDetailPage.js, webapp/src/components/ParcelDetailPage/ParcelActions/ParcelActions.js, webapp/src/modules/bid/selectors.js
- Add `distrinct_id` to `Estate` column 
- Set Estate `district_ids` once monitor finished
- Do not index bids for districts
- Do not show bid button on a district details
- Hide `owner of` from Estate details if it is a district
`npm run migrate up`
=> feat: add distict_id to estates and filter bids for distrincts

monitor/reducers/bidReducer.js, shared/bid.js, shared/listing.js, src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ja.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/src/components/Bid/Bid.css, webapp/src/components/Bid/Bid.js, webapp/src/components/BidAssetPage/BidAssetForm.css, webapp/src/components/BidAssetPage/BidEstatePage/BidEstatePage.js, webapp/src/components/BidAssetPage/BidParcelPage/BidParcelPage.js, webapp/src/components/CancelBidAssetPage/CancelBidAssetPage.container.js, webapp/src/components/EstateDetailPage/EstateDetailPage.js, webapp/src/components/ParcelDetailPage/ParcelDetailPage.js, webapp/src/modules/address/sagas.js, webapp/src/modules/address/selectors.js, webapp/src/modules/bid/selectors.js, webapp/src/modules/bid/utils.js
=> Feat: handle bid with fingerprint changed

shared/bid.js, webapp/src/components/Bid/Bid.container.js, webapp/src/components/Bid/Bid.js, webapp/src/components/EstateDetailPage/EstateActions/EstateActions.js, webapp/src/components/EstateDetailPage/EstateDetailPage.js, webapp/src/components/ParcelDetailPage/ParcelActions/ParcelActions.js, webapp/src/components/ParcelDetailPage/ParcelDetailPage.js, webapp/src/components/ProfilePage/ProfilePage.container.js, webapp/src/modules/archivedBid/selectors.js, webapp/src/modules/bid/actions.js, webapp/src/modules/bid/reducer.js, webapp/src/modules/bid/sagas.js, webapp/src/modules/bid/selectors.js, webapp/src/modules/estates/sagas.js, webapp/src/modules/parcels/sagas.js
Random user:
Owner of one bid:
Owner of the asset:
=> Feat: make bids public

monitor/processEvents.js
Fix when a short reorg happens and the monitor is watching events.
A new event may have the same tx hash and name. Adding the block number and  log index to the key will make it more specific
=> feat: make event key more specific
